// Generated by delombok at Tue May 19 16:38:52 EDT 2026
package aws.cfn.codegen.json;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.collect.Sets;
import java.io.File;
import java.net.URI;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.Set;

/**
 * This represent the configuration that dictate {@link Codegen} to determine specification
 * by regions and generate appropriate template schemas based on the groups that we specified
 * By default if the tool is not provided with a configuration, it loads the default configuration
 * file that is bundled with that package. See config.yml
 *
 * @see GroupSpec
 */
public final class Config {
    public static Builder builder() {
        return new Builder(null);
    }

    public static Builder builder(Config existing) {
        return new Builder(Objects.requireNonNull(existing));
    }


    public static class Builder {
        private SchemaDraft draft = SchemaDraft.draft07;
        private File outputDir;
        private Set<String> regions;
        private boolean singleResourceSpec = false;
        private boolean includeIntrinsics = true;
        private final Map<String, URI> regionSpecs = new LinkedHashMap<>(12);
        private final Map<String, GroupSpec> groups = new LinkedHashMap<>(5);

        private Builder(Config existing) {
            if (existing != null) {
                mergeOverride(existing);
            }
        }

        public Builder mergeOverride(Config other) {
            Objects.requireNonNull(other);
            Settings settings = other.getSettings();
            if (settings != null) {
                this.draft = settings.getDraft() != null ? settings.getDraft() : this.draft;
                this.outputDir = settings.getOutput() != null ? settings.getOutput() : this.outputDir;
                this.regions = settings.getRegions() != null ? settings.getRegions() : this.regions;
                this.singleResourceSpec = settings.getSingle() != null ? settings.getSingle() : this.singleResourceSpec;
                this.includeIntrinsics = settings.getIncludeIntrinsics() != null ? settings.getIncludeIntrinsics() : this.includeIntrinsics;
            }
            this.regionSpecs.putAll(other.getSpecifications());
            this.groups.putAll(other.getGroups());
            return this;
        }

        public Builder withJsonSchema(SchemaDraft draft) {
            this.draft = draft;
            return this;
        }

        public Builder withRegionSpec(String region, String location) {
            return withRegionSpec(region, URI.create(location));
        }

        public Builder withRegionSpec(String region, URI location) {
            regionSpecs.put(Objects.requireNonNull(region), location);
            return this;
        }

        public Builder addRegion(String region) {
            this.regions.add(Objects.requireNonNull(region));
            return this;
        }

        public Builder addRegions(Set<String> regions) {
            this.regions.addAll(regions);
            return this;
        }

        public Builder setRegions(Set<String> regions) {
            this.regions = Objects.requireNonNull(regions);
            return this;
        }

        public Builder withOutputDirectory(File dir) {
            this.outputDir = Objects.requireNonNull(dir);
            return this;
        }

        public Builder isSingleResourceSpec(boolean single) {
            this.singleResourceSpec = single;
            return this;
        }

        public Builder withIntrinsics(boolean includeIntrinsics) {
            this.includeIntrinsics = includeIntrinsics;
            return this;
        }

        public Builder withGroup(String grpName, GroupSpec spec) {
            groups.put(grpName, spec);
            return this;
        }

        public Config build() {
            return new Config(regionSpecs, new Settings(draft, regions, outputDir, singleResourceSpec, includeIntrinsics), groups);
        }
    }


    public static class Settings {
        private final SchemaDraft draft;
        private final Set<String> regions;
        private final File output;
        private final Boolean single;
        private final Boolean includeIntrinsics;

        @JsonCreator
        public Settings(@JsonProperty("draft") SchemaDraft draft, @JsonProperty("regions") Set<String> regions, @JsonProperty("output") File output, @JsonProperty("single") Boolean single, @JsonProperty("intrinsics") Boolean includeIntrinsics) {
            this.draft = draft;
            this.regions = regions == null ? Sets.newHashSet("us-east-1") : regions;
            this.output = output;
            this.single = single == null ? false : single;
            this.includeIntrinsics = includeIntrinsics == null ? false : includeIntrinsics;
        }

        @java.lang.SuppressWarnings("all")
        
        public SchemaDraft getDraft() {
            return this.draft;
        }

        @java.lang.SuppressWarnings("all")
        
        public Set<String> getRegions() {
            return this.regions;
        }

        @java.lang.SuppressWarnings("all")
        
        public File getOutput() {
            return this.output;
        }

        @java.lang.SuppressWarnings("all")
        
        public Boolean getSingle() {
            return this.single;
        }

        @java.lang.SuppressWarnings("all")
        
        public Boolean getIncludeIntrinsics() {
            return this.includeIntrinsics;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public java.lang.String toString() {
            return "Config.Settings(draft=" + this.getDraft() + ", regions=" + this.getRegions() + ", output=" + this.getOutput() + ", single=" + this.getSingle() + ", includeIntrinsics=" + this.getIncludeIntrinsics() + ")";
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof Config.Settings)) return false;
            final Config.Settings other = (Config.Settings) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            final java.lang.Object this$single = this.getSingle();
            final java.lang.Object other$single = other.getSingle();
            if (this$single == null ? other$single != null : !this$single.equals(other$single)) return false;
            final java.lang.Object this$includeIntrinsics = this.getIncludeIntrinsics();
            final java.lang.Object other$includeIntrinsics = other.getIncludeIntrinsics();
            if (this$includeIntrinsics == null ? other$includeIntrinsics != null : !this$includeIntrinsics.equals(other$includeIntrinsics)) return false;
            final java.lang.Object this$draft = this.getDraft();
            final java.lang.Object other$draft = other.getDraft();
            if (this$draft == null ? other$draft != null : !this$draft.equals(other$draft)) return false;
            final java.lang.Object this$regions = this.getRegions();
            final java.lang.Object other$regions = other.getRegions();
            if (this$regions == null ? other$regions != null : !this$regions.equals(other$regions)) return false;
            final java.lang.Object this$output = this.getOutput();
            final java.lang.Object other$output = other.getOutput();
            if (this$output == null ? other$output != null : !this$output.equals(other$output)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof Config.Settings;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            final java.lang.Object $single = this.getSingle();
            result = result * PRIME + ($single == null ? 43 : $single.hashCode());
            final java.lang.Object $includeIntrinsics = this.getIncludeIntrinsics();
            result = result * PRIME + ($includeIntrinsics == null ? 43 : $includeIntrinsics.hashCode());
            final java.lang.Object $draft = this.getDraft();
            result = result * PRIME + ($draft == null ? 43 : $draft.hashCode());
            final java.lang.Object $regions = this.getRegions();
            result = result * PRIME + ($regions == null ? 43 : $regions.hashCode());
            final java.lang.Object $output = this.getOutput();
            result = result * PRIME + ($output == null ? 43 : $output.hashCode());
            return result;
        }
    }

    private final Map<String, GroupSpec> groups;
    private final Settings settings;
    private final Map<String, URI> specifications;

    @JsonCreator
    public Config(@JsonProperty("specifications") final Map<String, URI> specifications, @JsonProperty("settings") final Settings settings, @JsonProperty("groups") final Map<String, GroupSpec> groups) {
        this.specifications = specifications != null ? specifications : new LinkedHashMap<>(1);
        this.settings = settings;
        this.groups = groups != null ? groups : new LinkedHashMap<>();
        validateRegionSpecs();
        validateGroups();
    }

    private void validateRegionSpecs() {
        if (settings != null && !specifications.isEmpty()) {
            for (String r : settings.getRegions()) {
                if (!specifications.containsKey(r)) {
                    throw new IllegalArgumentException("No regions mapping was found " + settings.getRegions());
                }
            }
        }
    }

    private void validateGroups() {
        if (groups.isEmpty()) {
            GroupSpec spec = GroupSpec.includesOnly("all", "AWS.*");
            groups.put(spec.getGroupName(), spec);
        }
        // Merge as needed
        GroupSpec defaultGrpSpec = groups.containsKey("default") ? groups.remove("default") : GroupSpec.includesOnly("default", "Tag.*");
        Optional<Set<String>> defaultIncludes = Optional.ofNullable(defaultGrpSpec.getIncludes());
        Optional<Set<String>> defaultExcludes = Optional.ofNullable(defaultGrpSpec.getExcludes());
        // merge default and then compile the specifications
        groups.entrySet().stream().map(e -> {
            GroupSpec grp = e.getValue();
            grp.setGroupName(e.getKey());
            grp.setIncludes(Optional.ofNullable(grp.getIncludes()).map(s -> defaultIncludes.map(ds -> {
                s.addAll(ds);
                return s;
            }).orElse(s)).orElseGet(defaultGrpSpec::getIncludes));
            grp.setExcludes(Optional.ofNullable(grp.getExcludes()).map(s -> defaultExcludes.map(ds -> {
                s.addAll(ds);
                return s;
            }).orElse(s)).orElseGet(defaultGrpSpec::getExcludes));
            return e;
        }).map(Map.Entry::getValue).forEach(GroupSpec::compile);
    }

    @java.lang.SuppressWarnings("all")
    
    public Map<String, GroupSpec> getGroups() {
        return this.groups;
    }

    @java.lang.SuppressWarnings("all")
    
    public Settings getSettings() {
        return this.settings;
    }

    @java.lang.SuppressWarnings("all")
    
    public Map<String, URI> getSpecifications() {
        return this.specifications;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    
    public java.lang.String toString() {
        return "Config(groups=" + this.getGroups() + ", settings=" + this.getSettings() + ", specifications=" + this.getSpecifications() + ")";
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Config)) return false;
        final Config other = (Config) o;
        final java.lang.Object this$groups = this.getGroups();
        final java.lang.Object other$groups = other.getGroups();
        if (this$groups == null ? other$groups != null : !this$groups.equals(other$groups)) return false;
        final java.lang.Object this$settings = this.getSettings();
        final java.lang.Object other$settings = other.getSettings();
        if (this$settings == null ? other$settings != null : !this$settings.equals(other$settings)) return false;
        final java.lang.Object this$specifications = this.getSpecifications();
        final java.lang.Object other$specifications = other.getSpecifications();
        if (this$specifications == null ? other$specifications != null : !this$specifications.equals(other$specifications)) return false;
        return true;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $groups = this.getGroups();
        result = result * PRIME + ($groups == null ? 43 : $groups.hashCode());
        final java.lang.Object $settings = this.getSettings();
        result = result * PRIME + ($settings == null ? 43 : $settings.hashCode());
        final java.lang.Object $specifications = this.getSpecifications();
        result = result * PRIME + ($specifications == null ? 43 : $specifications.hashCode());
        return result;
    }
}
