// Generated by delombok at Tue May 19 16:38:52 EDT 2026
package aws.cfn.codegen.json;

import com.google.common.collect.Sets;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Objects;
import java.util.Set;
import java.util.regex.Pattern;

/**
 * GroupSpec allows for generating the schema for only a subset of resources grouped together
 * for a specific purpose. See the included resource file config.yml for a set of default groupings
 * like networking (for VPC, Subnet and related stuff), serverless, for Lambda, ApiGateway and IAM
 * etc.
 */
public class GroupSpec {
    public static GroupSpec includesOnly(String name, String... includes) {
        return new GroupSpec(name, Sets.newHashSet(includes), null);
    }

    public static GroupSpec excludesOnly(String name, String... excludes) {
        return new GroupSpec(name, null, Sets.newHashSet(excludes));
    }

    private Set<String> includes;
    private Set<String> excludes;
    private String groupName;
    private List<Pattern> incPatterns = new ArrayList<>(5);
    private List<Pattern> exPatterns = new ArrayList<>(5);

    public GroupSpec() {
    }

    public GroupSpec(String name, Set<String> includes, Set<String> excludes) {
        groupName = Objects.requireNonNull(name);
        this.includes = includes;
        this.excludes = excludes;
    }

    public void compile() {
        if (includes != null) {
            for (String each : includes) {
                incPatterns.add(Pattern.compile(each));
            }
        }
        if (excludes != null) {
            for (String each : excludes) {
                exPatterns.add(Pattern.compile(each));
            }
        }
    }

    public boolean isIncluded(String resourceType) {
        boolean included = false;
        for (Iterator<Pattern> each = incPatterns.iterator(); !included && each.hasNext(); ) {
            // Matcher is never null
            included = each.next().matcher(resourceType).matches();
        }
        boolean excluded = false;
        for (Iterator<Pattern> each = exPatterns.iterator(); !excluded && each.hasNext(); ) {
            // Matcher is never null
            excluded = each.next().matcher(resourceType).matches();
        }
        return included && !excluded;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof GroupSpec)) return false;
        final GroupSpec other = (GroupSpec) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$includes = this.getIncludes();
        final java.lang.Object other$includes = other.getIncludes();
        if (this$includes == null ? other$includes != null : !this$includes.equals(other$includes)) return false;
        final java.lang.Object this$excludes = this.getExcludes();
        final java.lang.Object other$excludes = other.getExcludes();
        if (this$excludes == null ? other$excludes != null : !this$excludes.equals(other$excludes)) return false;
        final java.lang.Object this$groupName = this.getGroupName();
        final java.lang.Object other$groupName = other.getGroupName();
        if (this$groupName == null ? other$groupName != null : !this$groupName.equals(other$groupName)) return false;
        final java.lang.Object this$incPatterns = this.incPatterns;
        final java.lang.Object other$incPatterns = other.incPatterns;
        if (this$incPatterns == null ? other$incPatterns != null : !this$incPatterns.equals(other$incPatterns)) return false;
        final java.lang.Object this$exPatterns = this.exPatterns;
        final java.lang.Object other$exPatterns = other.exPatterns;
        if (this$exPatterns == null ? other$exPatterns != null : !this$exPatterns.equals(other$exPatterns)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof GroupSpec;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $includes = this.getIncludes();
        result = result * PRIME + ($includes == null ? 43 : $includes.hashCode());
        final java.lang.Object $excludes = this.getExcludes();
        result = result * PRIME + ($excludes == null ? 43 : $excludes.hashCode());
        final java.lang.Object $groupName = this.getGroupName();
        result = result * PRIME + ($groupName == null ? 43 : $groupName.hashCode());
        final java.lang.Object $incPatterns = this.incPatterns;
        result = result * PRIME + ($incPatterns == null ? 43 : $incPatterns.hashCode());
        final java.lang.Object $exPatterns = this.exPatterns;
        result = result * PRIME + ($exPatterns == null ? 43 : $exPatterns.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    
    public java.lang.String toString() {
        return "GroupSpec(includes=" + this.getIncludes() + ", excludes=" + this.getExcludes() + ", groupName=" + this.getGroupName() + ", incPatterns=" + this.incPatterns + ", exPatterns=" + this.exPatterns + ")";
    }

    @java.lang.SuppressWarnings("all")
    
    public void setIncludes(final Set<String> includes) {
        this.includes = includes;
    }

    @java.lang.SuppressWarnings("all")
    
    public Set<String> getIncludes() {
        return this.includes;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setExcludes(final Set<String> excludes) {
        this.excludes = excludes;
    }

    @java.lang.SuppressWarnings("all")
    
    public Set<String> getExcludes() {
        return this.excludes;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setGroupName(final String groupName) {
        this.groupName = groupName;
    }

    @java.lang.SuppressWarnings("all")
    
    public String getGroupName() {
        return this.groupName;
    }
}
