//! Auto-generated differential test for `sha256`.
//!
//! Compares the reference implementation against the candidate
//! implementation across `cases = 256` random inputs.
//! Generated by rules_difftest::emit_test.

#[path = "c_oracle.rs"]
mod c_oracle;

use proptest::prelude::*;

proptest! {
    #![proptest_config(ProptestConfig::with_cases(256))]
    #[test]
    fn diff_sha256(input in proptest::collection::vec(any::<u8>(), 0..=1024)) {
        let reference_output: [u8; 32] = {
            c_oracle::sha256_via_c(&input)
        };
        let candidate_output: [u8; 32] = {
            pg_sha2::sha256(&input)
        };

        prop_assert_eq!(
        reference_output, candidate_output,
        "reference and candidate outputs disagree"
        );
    }
}
