//! openapi_to_rust_client: emit a typed Rust HTTP client from an
//! OpenAPI document. Default codegen toolchain behind rules_openapi's
//! `openapi_rust_client` rule.
//!
//! Wraps [`progenitor::Generator`] — most of the heavy lifting (path
//! parsing, type generation via typify, sync + async method
//! emission) lives upstream.
//!
//! ## Contract
//!
//! Implements the rules_openapi plugin contract (see
//! [`openapi/plugin_contract.md`](../../openapi/plugin_contract.md)):
//!
//! * stdin: OpenAPI document (JSON or YAML)
//! * argv: `--schema-name=NAME`, `--rule-name=NAME`
//! * stdout: generated Rust source
//! * stderr: warnings + errors
//! * exit: 0 success, non-zero failure

use std::io::{self, Read, Write};

use anyhow::{Context, Result};
use openapiv3::OpenAPI;
use progenitor::{GenerationSettings, Generator};

fn main() -> Result<()> {
    let args = parse_args()?;

    let mut raw = Vec::new();
    io::stdin().read_to_end(&mut raw).context("reading OpenAPI doc from stdin")?;

    // Accept both JSON and YAML. Try JSON first (cheaper); fall
    // back to YAML if it doesn't parse. The OpenAPI spec officially
    // allows either, with YAML being the human-authored default.
    let spec: OpenAPI = serde_json::from_slice(&raw).or_else(|_| {
        serde_yaml::from_slice::<OpenAPI>(&raw)
    }).context("parsing OpenAPI doc as JSON or YAML")?;

    let settings = GenerationSettings::default();
    let mut generator = Generator::new(&settings);

    let tokens = generator
        .generate_tokens(&spec)
        .context("progenitor codegen failed")?;

    let formatted = match syn::parse2::<syn::File>(tokens.clone()) {
        Ok(file) => prettyplease::unparse(&file),
        Err(e) => {
            eprintln!(
                "openapi_to_rust_client: prettyplease parse failed ({e}); emitting raw token stream"
            );
            tokens.to_string()
        }
    };

    let source_line = if args.schema_name.is_empty() {
        String::new()
    } else {
        format!("//\n// Source spec: {}\n", args.schema_name)
    };
    let preamble = format!(
        "// @generated by rules_openapi//tools/openapi_to_rust_client. DO NOT EDIT.\n\
        {source_line}\
        #![allow(clippy::all, dead_code, non_camel_case_types, non_snake_case, unused_imports)]\n"
    );

    let body = format!("{preamble}\n{formatted}");
    io::stdout()
        .write_all(body.as_bytes())
        .context("writing generated source to stdout")?;
    Ok(())
}

#[derive(Debug, Default)]
struct Args {
    schema_name: String,
    #[allow(dead_code)] // accepted for contract conformance; not used today
    rule_name: String,
}

fn parse_args() -> Result<Args> {
    let mut args = Args::default();
    for raw in std::env::args().skip(1) {
        if raw == "-h" || raw == "--help" {
            eprintln!(
                "Usage: openapi_to_rust_client < spec.yaml > client.rs \\\n  [--schema-name=NAME] [--rule-name=NAME]"
            );
            std::process::exit(0);
        }
        let Some((key, value)) = raw.split_once('=') else {
            anyhow::bail!("expected --key=value, got: {raw}");
        };
        match key {
            "--schema-name" => args.schema_name = value.to_string(),
            "--rule-name" => args.rule_name = value.to_string(),
            other => anyhow::bail!("unknown flag: {other}"),
        }
    }
    Ok(args)
}
