# @generated by rules_jsonschema//tools/schema_to_starlark. DO NOT EDIT.
#
# Source schema: person.json
#
# Refresh via the generating rule's `update` script;
# the diff_test will fail until you do.

load("@rules_jsonschema//runtime:helpers.bzl", "parse_json_or_none", "strip_unset")

PersonInfo = provider(
    doc = "A person contributed by a target. Shard JSON matches the person schema.",
    fields = {
        "person_name": "string: top-level key for this person in the rendered project.",
        "json": "File: the JSON shard.",
    },
)

def _smoke_person_impl(ctx):
    item_name = ctx.attr.person_name or ctx.label.name
    payload = {
        "addresses": parse_json_or_none(ctx.attr.addresses),
        "age": ctx.attr.age,
        "favourite_colour": ctx.attr.favourite_colour,
        "name": ctx.attr.name_override,
    }
    payload = strip_unset(payload)
    shard = ctx.actions.declare_file(ctx.label.name + ".person.json")
    ctx.actions.write(shard, json.encode(payload))
    return [
        DefaultInfo(files = depset([shard])),
        PersonInfo(person_name = item_name, json = shard),
    ]

smoke_person = rule(
    implementation = _smoke_person_impl,
    doc = "Schema-derived rule for one `person` entry.",
    provides = [PersonInfo],
    attrs = {
        "person_name": attr.string(
            doc = "Top-level key for this person in the rendered project. Defaults to the rule name.",
        ),
        "addresses": attr.string(
            doc = "Zero or more mailing addresses. (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "age": attr.int(
            doc = "Age in completed years.",
        ),
        "favourite_colour": attr.string(
            values = ["red", "green", "blue"],
            doc = "Closed set of accepted values.",
        ),
        "name_override": attr.string(
            doc = "Full legal name.",
        ),
    },
)

AddressInfo = provider(
    doc = "A address contributed by a target. Shard JSON matches the address schema.",
    fields = {
        "address_name": "string: top-level key for this address in the rendered project.",
        "json": "File: the JSON shard.",
    },
)

def _smoke_address_impl(ctx):
    item_name = ctx.attr.address_name or ctx.label.name
    payload = {
        "country": ctx.attr.country,
        "line1": ctx.attr.line1,
        "line2": ctx.attr.line2,
    }
    payload = strip_unset(payload)
    shard = ctx.actions.declare_file(ctx.label.name + ".address.json")
    ctx.actions.write(shard, json.encode(payload))
    return [
        DefaultInfo(files = depset([shard])),
        AddressInfo(address_name = item_name, json = shard),
    ]

smoke_address = rule(
    implementation = _smoke_address_impl,
    doc = "Schema-derived rule for one `address` entry.",
    provides = [AddressInfo],
    attrs = {
        "address_name": attr.string(
            doc = "Top-level key for this address in the rendered project. Defaults to the rule name.",
        ),
        "country": attr.string(
            doc = "ISO-3166 alpha-2 country code.",
        ),
        "line1": attr.string(),
        "line2": attr.string(),
    },
)

