#!/usr/bin/env node
// Internal helper for rules_nextjs's `next_build` action.
//
// Writes a thin `next.config.mjs` wrapper at `dstConfig` that imports
// the user's original `next.config.*` (`srcConfig`) and composes a
// webpack hook adding two resolver tweaks:
//
//  * `resolve.extensionAlias`: lets `.js` imports fall through to
//    `.jsx`/`.ts`/`.tsx`. The workspace's shared tsconfig sets
//    `"jsx": "preserve"` so ts_project emits `.jsx` (not `.js`) for
//    `.tsx` sources; compiled `.ts` modules in the npm_package still
//    import siblings with `.js` (tsc doesn't rewrite specifiers),
//    and webpack doesn't auto-fall-back without this alias. Harmless
//    for `.js` files that *do* exist — webpack tries each candidate
//    in order.
//
//  * `resolve.modules`: also search the app's own `node_modules` (an
//    absolute path) so peer deps surface during transitive resolution.
//    Webpack realpaths workspace package symlinks into
//    aspect_rules_js's content store at
//    `bazel-out/.../bin/node_modules/.aspect_rules_js/@scope+pkg@v/node_modules/...`
//    and then walks parent dirs from there looking for `node_modules`
//    — the parents never include the app's `node_modules`, so packages
//    declared only as `peerDependencies` (e.g. `@mui/material` in
//    `@savvi-studio/ui`) aren't reachable from inside the store entry.
//    Naming the app's node_modules explicitly in `resolve.modules`
//    lets webpack find them.
//
// And one Next.js-level tweak:
//
//  * `transpilePackages`: extended to include every `workspace:*` dep
//    from the app's package.json. ts_project ships compiled `.jsx`
//    files (because the workspace's shared tsconfig sets
//    `"jsx": "preserve"`); webpack with Next.js's defaults doesn't run
//    a JSX transform on files inside `node_modules`, so those
//    compiled `.jsx` files hit `Module parse failed: Unexpected
//    token`. Adding the workspace packages to `transpilePackages`
//    routes them through Next.js's SWC loader, which handles JSX.
//
// Usage: node write_next_config_wrapper.mjs <srcConfig> <dstConfig>

import fs from 'node:fs';
import path from 'node:path';

const [, , src, dst] = process.argv;
if (!src || !dst) {
  console.error('usage: write_next_config_wrapper.mjs <srcConfig> <dstConfig>');
  process.exit(1);
}

const absSrc = path.isAbsolute(src) ? src : path.resolve(path.dirname(dst), src);
const srcLit = JSON.stringify(absSrc);

// Pull `workspace:*` deps from the app's package.json so the wrapper
// can list them in `transpilePackages`. The app's package.json is the
// sibling of the *original* next.config (its absolute path resolves
// into the workspace tree).
const workspacePkgs = [];
const pkgPath = path.join(path.dirname(absSrc), 'package.json');
if (fs.existsSync(pkgPath)) {
  const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
  for (const section of ['dependencies', 'devDependencies']) {
    const deps = pkg[section] || {};
    for (const [name, spec] of Object.entries(deps)) {
      if (typeof spec === 'string' && spec.startsWith('workspace:')) {
        workspacePkgs.push(name);
      }
    }
  }
}
const workspacePkgsLit = JSON.stringify(workspacePkgs);

const wrapper = `// Generated by rules_nextjs. Wraps the user's next.config to add
// resolve.extensionAlias (.js -> .jsx/.ts/.tsx fallback), an absolute
// node_modules entry in resolve.modules (peer-dep visibility), and
// extends transpilePackages with every workspace:* dep so Next.js's
// SWC loader handles the compiled .jsx output of ts_project.
// See defs.bzl + private/write_next_config_wrapper.mjs for context.
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import userConfigModule from ${srcLit};
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const resolved = typeof userConfigModule === 'function'
    ? await userConfigModule({ defaultConfig: {} })
    : userConfigModule;
const cfg = { ...resolved };
const _workspacePkgs = ${workspacePkgsLit};
cfg.transpilePackages = [
    ...(cfg.transpilePackages || []),
    ..._workspacePkgs.filter(p => !(cfg.transpilePackages || []).includes(p)),
];
const userWebpack = cfg.webpack;
cfg.webpack = (config, ctx) => {
    if (userWebpack) config = userWebpack(config, ctx);
    config.resolve = config.resolve || {};
    config.resolve.extensionAlias = {
        ...(config.resolve.extensionAlias || {}),
        '.js': ['.js', '.jsx', '.ts', '.tsx'],
        '.mjs': ['.mjs', '.mts', '.js'],
        // .ts here covers workspace packages whose package.json
        // exports map points at .ts entry files (the source-tree
        // shape) while ts_project ships compiled .js outputs.
        '.ts': ['.ts', '.tsx', '.js', '.jsx'],
        '.tsx': ['.tsx', '.ts', '.jsx', '.js'],
    };
    config.resolve.modules = [
        ...(config.resolve.modules || ['node_modules']),
        path.resolve(__dirname, 'node_modules'),
    ];
    return config;
};
export default cfg;
`;

fs.writeFileSync(dst, wrapper);
