"""Auto-generated by rules_cc_cross arm_gnu_toolchain repo rule."""

load(
    "@rules_cc_cross//cc_cross/private:cc_toolchain_config.bzl",
    "cross_cc_toolchain_config",
)

# Generated repo doesn't inherit @rules_cc visibility from our
# bazel_dep graph — use the canonical name.
load("@@rules_cc+//cc:defs.bzl", "cc_toolchain")

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "all_files",
    srcs = glob(
        [
            "bin/**",
            "lib/**",
            "libexec/**",
            "{target}/**",
        ],
        allow_empty = True,
    ),
)

cross_cc_toolchain_config(
    name = "cc_toolchain_config",
    toolchain_identifier = "arm_gnu_{target_underscored}",
    target_system_name = "{target}",
    target_cpu = "{target_cpu}",
    tool_prefix = "{tool_prefix}",
    sysroot = "{sysroot}",
)

cc_toolchain(
    name = "cc_toolchain",
    all_files = ":all_files",
    ar_files = ":all_files",
    as_files = ":all_files",
    compiler_files = ":all_files",
    dwp_files = ":all_files",
    linker_files = ":all_files",
    objcopy_files = ":all_files",
    strip_files = ":all_files",
    toolchain_config = ":cc_toolchain_config",
    toolchain_identifier = "arm_gnu_{target_underscored}",
)

toolchain(
    name = "{target_underscored}_toolchain",
    exec_compatible_with = [],
    target_compatible_with = [
        "@platforms//cpu:{target_cpu}",
        "@platforms//os:none",
    ],
    toolchain = ":cc_toolchain",
    toolchain_type = "@bazel_tools//tools/cpp:toolchain_type",
)
