// schema_to_go: emit Go type definitions from a JSON Schema.
// Default codegen toolchain behind rules_jsonschema's
// jsonschema_go_library rule.
//
// Implements the rules_jsonschema plugin contract:
//
//	stdin: schema file contents (JSON)
//	argv:  --schema-name=NAME, --rule-name=NAME, --package=NAME
//	stdout: generated Go source (formatted with go/format)
//	stderr: warnings + errors
//	exit:  0 success, non-zero failure
//
// Coverage is minimal — primitives, structs, slices, maps, optional
// pointers, refs to named definitions. Enums collapse to their
// underlying type. The intent is "validate the plugin contract works
// for a Go-language plugin"; consumers wanting fuller JSON-Schema-to-Go
// support can register their own toolchain pointing at
// atombender/go-jsonschema or similar.
package main

import (
	"encoding/json"
	"fmt"
	"go/format"
	"io"
	"os"
	"sort"
	"strings"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "schema_to_go:", err)
		os.Exit(1)
	}
}

// --- entry ----------------------------------------------------------

type args struct {
	schemaName string
	ruleName   string
	pkg        string
}

func run() error {
	a, err := parseArgs()
	if err != nil {
		return err
	}

	schemaBytes, err := io.ReadAll(os.Stdin)
	if err != nil {
		return fmt.Errorf("read stdin: %w", err)
	}
	var schema map[string]any
	if err := json.Unmarshal(schemaBytes, &schema); err != nil {
		return fmt.Errorf("parse schema: %w", err)
	}

	pkg := a.pkg
	if pkg == "" {
		// Prefer the rule name (Bazel target), fall back to a
		// generic placeholder. The rule name is more useful than a
		// raw schema filename because it's already Go-ident-shaped.
		pkg = a.ruleName
		if pkg == "" {
			pkg = "generated"
		}
		pkg = sanitizePkg(pkg)
	}

	var src strings.Builder
	fmt.Fprintln(&src, "// @generated by rules_jsonschema//tools/schema_to_go. DO NOT EDIT.")
	if a.schemaName != "" {
		fmt.Fprintln(&src, "//")
		fmt.Fprintln(&src, "// Source schema:", a.schemaName)
	}
	fmt.Fprintln(&src)
	fmt.Fprintln(&src, "package", pkg)
	fmt.Fprintln(&src)

	emitTypes(&src, schema)

	// go/format makes the output canonical regardless of how the
	// emitter spaced things. If formatting fails we still emit the
	// raw source (a syntax error is more useful than no output) and
	// warn on stderr.
	formatted, ferr := format.Source([]byte(src.String()))
	if ferr != nil {
		fmt.Fprintf(os.Stderr,
			"schema_to_go: go/format failed (%v); emitting unformatted source\n", ferr)
		formatted = []byte(src.String())
	}
	if _, err := os.Stdout.Write(formatted); err != nil {
		return fmt.Errorf("write stdout: %w", err)
	}
	return nil
}

// --- argv -----------------------------------------------------------

func parseArgs() (args, error) {
	var a args
	for _, raw := range os.Args[1:] {
		if raw == "-h" || raw == "--help" {
			fmt.Fprintln(os.Stderr,
				"Usage: schema_to_go < schema.json > types.go \\\n  [--schema-name=NAME] [--rule-name=NAME] [--package=NAME]")
			os.Exit(0)
		}
		key, value, ok := strings.Cut(raw, "=")
		if !ok {
			return a, fmt.Errorf("expected --key=value, got: %s", raw)
		}
		switch key {
		case "--schema-name":
			a.schemaName = value
		case "--rule-name":
			a.ruleName = value
		case "--package":
			a.pkg = value
		default:
			return a, fmt.Errorf("unknown flag: %s", key)
		}
	}
	return a, nil
}

// --- emission -------------------------------------------------------

// emitTypes walks the schema's root + every $defs / definitions entry
// and emits one Go struct per (named) object type, in sorted order.
func emitTypes(w *strings.Builder, schema map[string]any) {
	emitted := map[string]bool{}
	// Root type: schema is an object with a `title` and `properties`.
	if title, ok := schema["title"].(string); ok {
		if props, ok := schema["properties"].(map[string]any); ok {
			name := goTypeName(title)
			emitStruct(w, name, props, requiredSet(schema), schema)
			emitted[name] = true
		}
	}
	// Definitions (both keys; merge).
	for _, defsKey := range []string{"$defs", "definitions"} {
		defs, ok := schema[defsKey].(map[string]any)
		if !ok {
			continue
		}
		names := make([]string, 0, len(defs))
		for k := range defs {
			names = append(names, k)
		}
		sort.Strings(names)
		for _, defName := range names {
			def, ok := defs[defName].(map[string]any)
			if !ok {
				continue
			}
			props, ok := def["properties"].(map[string]any)
			if !ok {
				continue
			}
			typeName := goTypeName(defName)
			if emitted[typeName] {
				continue
			}
			emitStruct(w, typeName, props, requiredSet(def), schema)
			emitted[typeName] = true
		}
	}
}

func emitStruct(w *strings.Builder, name string, props map[string]any, required map[string]bool, root map[string]any) {
	fmt.Fprintf(w, "type %s struct {\n", name)
	keys := make([]string, 0, len(props))
	for k := range props {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, key := range keys {
		prop, _ := props[key].(map[string]any)
		field := goFieldName(key)
		isRequired := required[key]
		goType := goTypeFor(prop, root, isRequired)
		tag := fmt.Sprintf("`json:%q`", key)
		if !isRequired {
			tag = fmt.Sprintf("`json:%q`", key+",omitempty")
		}
		if desc, ok := prop["description"].(string); ok && desc != "" {
			cleaned := strings.ReplaceAll(strings.ReplaceAll(desc, "\n", " "), "\r", " ")
			fmt.Fprintf(w, "\t// %s: %s\n", field, cleaned)
		}
		fmt.Fprintf(w, "\t%s %s %s\n", field, goType, tag)
	}
	fmt.Fprintln(w, "}")
	fmt.Fprintln(w)
}

// --- type mapping ---------------------------------------------------

func goTypeFor(prop map[string]any, root map[string]any, required bool) string {
	base := baseGoType(prop, root)
	if required || isContainer(base) {
		// Slices and maps have nil zero values already; pointers
		// would only add noise.
		return base
	}
	return "*" + base
}

func isContainer(t string) bool {
	return strings.HasPrefix(t, "[]") || strings.HasPrefix(t, "map[")
}

func baseGoType(prop map[string]any, root map[string]any) string {
	// $ref → resolved type name.
	if ref, ok := prop["$ref"].(string); ok {
		if i := strings.LastIndex(ref, "/"); i >= 0 {
			return goTypeName(ref[i+1:])
		}
	}

	// Multi-type union (`type: ["string", "number"]`). Same preference
	// order schema_to_starlark / schema_to_rust use.
	if types, ok := prop["type"].([]any); ok {
		names := make([]string, 0, len(types))
		for _, t := range types {
			if s, ok := t.(string); ok {
				names = append(names, s)
			}
		}
		switch {
		case containsStr(names, "boolean"):
			return "bool"
		case containsStr(names, "string"):
			return "string"
		case containsStr(names, "integer"):
			return "int"
		case containsStr(names, "number"):
			return "float64"
		}
		return "any"
	}

	t, _ := prop["type"].(string)
	switch t {
	case "string":
		return "string"
	case "integer":
		return "int"
	case "number":
		return "float64"
	case "boolean":
		return "bool"
	case "array":
		items, _ := prop["items"].(map[string]any)
		if items == nil {
			return "[]any"
		}
		return "[]" + baseGoType(items, root)
	case "object":
		// additionalProperties: T → map[string]T. Otherwise fall
		// back to `any`.
		if ap, ok := prop["additionalProperties"].(map[string]any); ok {
			return "map[string]" + baseGoType(ap, root)
		}
		return "any"
	}
	return "any"
}

// --- name munging ---------------------------------------------------

// goFieldName turns a schema property name into an exported Go
// identifier: snake_case → CamelCase, leading non-letter → `_`-prefixed.
func goFieldName(s string) string {
	var b strings.Builder
	capitalize := true
	for _, r := range s {
		if r == '_' || r == '-' || r == '.' || r == ' ' {
			capitalize = true
			continue
		}
		if capitalize {
			if r >= 'a' && r <= 'z' {
				r = r - 'a' + 'A'
			}
			capitalize = false
		}
		b.WriteRune(r)
	}
	out := b.String()
	if out == "" || !isASCIIAlpha(rune(out[0])) {
		out = "_" + out
	}
	return out
}

func goTypeName(s string) string { return goFieldName(s) }

// sanitizePkg makes `s` a valid Go package identifier: lowercased,
// non-alphanumeric → `_`, leading-digit prefixed with `_`.
func sanitizePkg(s string) string {
	var b strings.Builder
	for _, r := range s {
		switch {
		case r >= 'A' && r <= 'Z':
			b.WriteRune(r - 'A' + 'a')
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			b.WriteRune(r)
		default:
			b.WriteRune('_')
		}
	}
	out := b.String()
	if out == "" {
		return "generated"
	}
	if out[0] >= '0' && out[0] <= '9' {
		out = "_" + out
	}
	return out
}

// --- helpers --------------------------------------------------------

func isASCIIAlpha(r rune) bool {
	return (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z')
}

func containsStr(s []string, want string) bool {
	for _, v := range s {
		if v == want {
			return true
		}
	}
	return false
}

func requiredSet(def map[string]any) map[string]bool {
	out := map[string]bool{}
	if arr, ok := def["required"].([]any); ok {
		for _, v := range arr {
			if s, ok := v.(string); ok {
				out[s] = true
			}
		}
	}
	return out
}
