#!/usr/bin/env python3
"""Wrapper invoked by `meson_configure` as the action's executable.

Imports `mesonbuild.mesonmain` directly (no nested py_binary
subprocess), invokes `meson setup`, and copies the resulting
`build/compile_commands.json` to the declared Bazel output. Paths in
the compdb are relativized so the artifact is portable across
sandboxes (downstream consumers like `c_ast_dump_from_compdb` see
workspace-relative paths instead of one-shot tmp build dirs).

Why in-process meson invocation: Bazel py_binary wrappers need their
.runfiles tree, which is set up automatically when the py_binary is
the action's `executable` but NOT when it's a subprocess of another
binary. So we keep mesonbuild as a library dep of THIS py_binary, no
nested invocation.
"""

from __future__ import annotations

import argparse
import json
import os
import shlex
import shutil
import sys
import tempfile


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--src-root", required=True,
                   help="Sandbox path to the source tree (dir containing meson.build).")
    p.add_argument("--out-compdb", required=True,
                   help="Path to write compile_commands.json.")
    p.add_argument("--out-log", required=True,
                   help="Path to write meson setup's stdout+stderr.")
    p.add_argument("--out-introspect", required=True,
                   help="Path to write `meson introspect --targets` JSON.")
    p.add_argument("--out-headers-dir", required=True,
                   help="Directory to populate with meson's generated "
                        "headers (.h, .in templates, .pc files). "
                        "Downstream consumers add this dir's path to "
                        "clang's -I via the ${MESON_HEADERS_TREE} sentinel.")
    p.add_argument("--ninja-bin", required=True,
                   help="Path to the ninja binary; its dir is added to PATH.")
    p.add_argument(
        "--meson-option",
        action="append",
        default=[],
        help="Repeated; appended to `meson setup` argv after build_dir + src_root.",
    )
    p.add_argument(
        "--pre-remove",
        action="append",
        default=[],
        help="Repeated; source-root-relative paths to delete before "
             "invoking meson. Use for projects whose source tree carries "
             "files (e.g. autoconf-generated headers, IDE state) that "
             "confuse meson's clean-checkout heuristic. Files that "
             "don't exist are silently skipped.",
    )
    p.add_argument(
        "--build-custom-targets",
        action="store_true",
        help="After meson setup, invoke ninja to build every custom_target "
             "the project declares. Required for codebases whose TUs "
             "#include headers generated by code-gen scripts (e.g. "
             "Postgres' Perl `generate-errcodes.pl` → utils/errcodes.h). "
             "Only the custom_target outputs are built — not object files "
             "or final binaries — so the wall-clock cost stays bounded.",
    )
    args = p.parse_args()

    # Put ninja's directory on PATH so meson's subprocesses find it.
    # Keep /usr/bin and /bin so meson can shell out to system tools
    # (sh, env, etc.) it expects to be ambient.
    ninja_dir = os.path.dirname(os.path.abspath(args.ninja_bin))
    os.environ["PATH"] = "{}:{}".format(
        ninja_dir, os.environ.get("PATH", "/usr/bin:/bin")
    )
    # meson sniffs $NINJA before falling back to PATH search.
    os.environ["NINJA"] = os.path.abspath(args.ninja_bin)

    # Optional pre-cleanup. Generic mechanism — useful for projects
    # whose source tree carries files that confuse meson's "is this a
    # clean checkout" check (Postgres' autoconf-style pg_config.h
    # overlay is the canonical example).
    for rel in args.pre_remove:
        path = os.path.join(args.src_root, rel)
        if os.path.islink(path) or os.path.exists(path):
            try:
                os.unlink(path)
            except OSError as e:
                sys.stderr.write(
                    "warning: --pre-remove %s failed: %s\n" % (path, e)
                )

    with tempfile.TemporaryDirectory(prefix="meson_configure_") as build_dir:
        argv = ["setup", build_dir, args.src_root] + args.meson_option

        # Tee meson's output to the log file. Need to swap BOTH
        # sys.stdout/sys.stderr (Python's print() target, internally
        # buffered) AND fd 1/2 (for subprocesses meson spawns + direct
        # os.write callers). Doing only the fd-level dup2 lets buffered
        # writes leak to the *restored* fd after our redirect window.
        from mesonbuild import mesonmain
        rc = _run_with_stdout_to_file(args.out_log,
                                      lambda: mesonmain.run(argv, "meson"),
                                      also_stderr=True)

        if rc != 0:
            sys.stderr.write("meson setup failed (exit %d). tail of log:\n" % rc)
            with open(args.out_log, "r", encoding="utf-8", errors="replace") as fh:
                lines = fh.readlines()
            sys.stderr.write("".join(lines[-80:]))
            return rc

        compdb_src = os.path.join(build_dir, "compile_commands.json")
        if not os.path.exists(compdb_src):
            sys.stderr.write(
                "meson setup succeeded but %s was not produced.\n" % compdb_src
            )
            return 1

        # Capture meson's target graph (the M2 input). Same trick as
        # mesonmain.run() for setup: invoke via mintro module. We do
        # this BEFORE codegen so we have the custom_target list to
        # drive `ninja`.
        rc = _capture_introspect(build_dir, args.out_introspect)
        if rc != 0:
            return rc

        # If requested, run ninja to build the project's custom_targets
        # (codegen scripts). This is the M4 mechanism: Postgres' Perl
        # codegen produces errcodes.h / fmgrtab.c / kwlist_d.h / etc.
        # via meson custom_target declarations; ninja knows how to
        # execute them. We pass only custom_target output paths, so
        # ninja skips object files + link steps.
        if args.build_custom_targets:
            rc = _run_custom_targets(
                ninja_bin=os.path.abspath(args.ninja_bin),
                build_dir=build_dir,
                introspect_path=args.out_introspect,
                log_path=args.out_log,
            )
            if rc != 0:
                return rc

        # Capture generated headers AFTER codegen. The TreeArtifact thus
        # contains BOTH the meson-generated config headers (pg_config.h
        # etc.) and the script-generated ones (errcodes.h, fmgroids.h,
        # nodetags.h, ...).
        _capture_generated_headers(build_dir, args.out_headers_dir)

        _relativize_compdb(
            compdb_src, args.out_compdb, args.src_root, build_dir,
        )
    return 0


def _capture_generated_headers(build_dir: str, out_dir: str) -> None:
    """Walk build_dir and copy generated header-ish files into out_dir,
    preserving the relative directory structure. Captures .h, .in (meson
    templates that downstream tooling may need), .pc (pkg-config), and
    .def (defines files some projects emit)."""
    os.makedirs(out_dir, exist_ok=True)
    HEADER_EXTS = (".h", ".hpp", ".inc", ".in", ".pc", ".def")
    for root, _dirs, files in os.walk(build_dir):
        # Skip meson's own bookkeeping dirs — they hold internal state,
        # not artifacts downstream consumers need.
        rel_root = os.path.relpath(root, build_dir)
        if rel_root.startswith("meson-info") or rel_root.startswith("meson-private") \
           or rel_root.startswith("meson-logs"):
            continue
        for f in files:
            if not f.endswith(HEADER_EXTS):
                continue
            src = os.path.join(root, f)
            dst_dir = os.path.join(out_dir, rel_root) if rel_root != "." else out_dir
            os.makedirs(dst_dir, exist_ok=True)
            shutil.copy2(src, os.path.join(dst_dir, f))


def _create_meson_shim_dir(build_dir: str) -> str:
    """Create a `meson` executable in a fresh subdir of build_dir.

    The shim invokes the same Python interpreter (sys.executable) and
    sys.path as the runner — so when ninja shells out to `meson`, it
    finds the same hermetic meson the runner just used. Returns the
    shim's parent dir (for PATH augmentation)."""
    shim_dir = os.path.join(build_dir, ".meson_shim")
    os.makedirs(shim_dir, exist_ok=True)
    shim_path = os.path.join(shim_dir, "meson")
    # Quote sys.path entries safely via repr() so the shim parses even
    # if a path contains spaces.
    shim_content = (
        "#!" + sys.executable + "\n"
        "import sys\n"
        "sys.path[:0] = " + repr(sys.path) + "\n"
        "from mesonbuild import mesonmain\n"
        "sys.exit(mesonmain.run(sys.argv[1:], sys.argv[0]))\n"
    )
    with open(shim_path, "w", encoding="utf-8") as f:
        f.write(shim_content)
    os.chmod(shim_path, 0o755)
    return shim_dir


def _run_custom_targets(
    ninja_bin: str, build_dir: str, introspect_path: str, log_path: str,
) -> int:
    """Invoke ninja to build every custom_target the project declares.

    Reads the introspect.json we just wrote, extracts each custom_target's
    output filename(s), converts to build_dir-relative paths (ninja's
    target-name convention when invoked with `-C build_dir`), and runs
    `ninja -C build_dir -k 0 <targets...>`. The `-k 0` keeps going past
    failures so one broken codegen script doesn't abort the rest.

    Output is appended to log_path (after meson setup's own log content).
    """
    import subprocess

    try:
        with open(introspect_path, "r", encoding="utf-8") as fh:
            entries = json.load(fh)
    except (OSError, json.JSONDecodeError) as e:
        sys.stderr.write("can't read introspect.json for codegen: %s\n" % e)
        return 1

    # Canonicalize the build_dir for prefix comparison. On macOS,
    # `tempfile.TemporaryDirectory` returns paths under `/var/folders/...`
    # but meson resolves and stores them as `/private/var/folders/...`
    # (the real path behind the /var symlink). Without canonicalization
    # the prefix-strip silently fails and we'd pass absolute paths to
    # ninja, which doesn't recognize them as targets.
    real_build_dir = os.path.realpath(build_dir)
    candidate_prefixes = {build_dir + "/", real_build_dir + "/"}

    targets: list[str] = []
    for entry in entries:
        if entry.get("type") != "custom":
            continue
        for f in entry.get("filename") or []:
            stripped = None
            for prefix in candidate_prefixes:
                if f.startswith(prefix):
                    stripped = f[len(prefix):]
                    break
            if stripped is not None:
                targets.append(stripped)
            elif os.path.isabs(f):
                # Last resort: pass absolute path; ninja may or may not
                # accept it.
                targets.append(f)
            else:
                targets.append(f)

    if not targets:
        # No custom_targets in this project — nothing to do.
        return 0

    sys.stderr.write(
        "[meson_runner] building %d custom_target outputs via ninja...\n"
        % len(targets)
    )

    # Custom_targets with `capture: true` get wrapped by meson in a
    # `meson --internal exe --capture <out> -- <cmd>` invocation
    # (meson redirects the cmd's stdout to <out>). For that to work,
    # `meson` needs to be on PATH when ninja runs the rule. Our meson is
    # a py_library, not a system binary, so we drop a tiny shim into
    # build_dir/.meson_shim/ that invokes mesonbuild via the same
    # interpreter (and sys.path) that runs this runner.
    shim_dir = _create_meson_shim_dir(build_dir)
    env = os.environ.copy()
    env["PATH"] = shim_dir + ":" + env.get("PATH", "")

    # Append ninja's output to the meson log.
    with open(log_path, "a", encoding="utf-8") as logf:
        logf.write("\n=== ninja codegen ===\n")
        logf.flush()
        result = subprocess.run(
            [ninja_bin, "-C", build_dir, "-k", "0"] + targets,
            stdout=logf,
            stderr=subprocess.STDOUT,
            env=env,
            check=False,
        )

    if result.returncode != 0:
        # `-k 0` means we tried everything but some failed. Report the
        # exit code but don't abort — partial codegen is still useful
        # (frontend files generated even if backend ones failed).
        sys.stderr.write(
            "[meson_runner] ninja codegen exited %d (some custom_targets "
            "failed; see meson log). Continuing.\n" % result.returncode
        )
    return 0


def _capture_introspect(build_dir: str, out_path: str) -> int:
    """Run `meson introspect --targets <build_dir>`, capture JSON output.

    Uses mesonmain.run() the same way setup does — same in-process pattern,
    no nested py_binary subprocess. The introspection JSON is the input
    M2 needs to generate per-target cc_library targets.
    """
    from mesonbuild import mesonmain
    rc = _run_with_stdout_to_file(
        out_path,
        lambda: mesonmain.run(
            ["introspect", "--targets", "--indent", build_dir], "meson",
        ),
        also_stderr=False,
    )
    if rc != 0:
        sys.stderr.write("meson introspect --targets failed (exit %d)\n" % rc)
    return rc


def _run_with_stdout_to_file(out_path: str, fn, also_stderr: bool) -> int:
    """Redirect Python's sys.stdout (text-buffered) + the OS-level fd 1
    to `out_path` while `fn()` runs, restore on exit. Optionally
    redirect stderr too.

    Doing BOTH levels of redirection is the only safe pattern: pure-
    Python writers (`print`, `sys.stdout.write`) go through sys.stdout's
    text buffer; subprocesses inherit the OS-level fds. Redirecting only
    one of them leaks output to the other.
    """
    f = open(out_path, "w", encoding="utf-8")
    old_sys_stdout = sys.stdout
    old_fd1 = os.dup(1)
    if also_stderr:
        old_sys_stderr = sys.stderr
        old_fd2 = os.dup(2)
    sys.stdout = f
    os.dup2(f.fileno(), 1)
    if also_stderr:
        sys.stderr = f
        os.dup2(f.fileno(), 2)
    try:
        rc = fn()
        f.flush()
    finally:
        # Restore in reverse order.
        if also_stderr:
            sys.stderr = old_sys_stderr
            os.dup2(old_fd2, 2)
            os.close(old_fd2)
        sys.stdout = old_sys_stdout
        os.dup2(old_fd1, 1)
        os.close(old_fd1)
        f.close()
    return rc


def _relativize_compdb(src: str, dst: str, src_root: str, build_dir: str) -> None:
    """Rewrite compile_commands.json so paths are stable across sandboxes.

    Meson writes entries with absolute sandbox paths (build_dir for
    `directory`, sandbox execroot for `file` and arguments's -I/-o
    paths). After this action ends, both are gone — the `directory`
    field points at a deleted tmp dir, and the `file` field uses an
    absolute path that won't exist in the *next* action's sandbox.

    Downstream consumers (`c_ast_dump_from_compdb` etc.) run in their
    own sandbox where the source tree is staged at a workspace-relative
    path. We rewrite:
      - directory → "."  (the workspace root in the downstream action)
      - file → src_root-relative or workspace-relative
      - arguments → strip the dead build_dir prefix from -I / -o paths,
                    drop output-only flags (-o, -MD, -MF, -MT, -MQ)
                    since meson recorded them for its build cycle and
                    downstream tooling chooses its own.
    """
    with open(src, "r", encoding="utf-8") as fh:
        entries = json.load(fh)

    abs_src_root = os.path.abspath(src_root)
    if abs_src_root.endswith(src_root):
        sandbox_root = abs_src_root[: -len(src_root)].rstrip("/")
    else:
        # Fallback: cwd is the sandbox root.
        sandbox_root = os.getcwd()

    def _rewrite_token(tok: str) -> str | None:
        # Strip sandbox-absolute prefixes so the path becomes
        # workspace-relative.
        if tok.startswith(sandbox_root + "/"):
            return tok[len(sandbox_root) + 1:]
        # build_dir paths get replaced with the ${MESON_HEADERS_TREE}
        # sentinel. Downstream consumers (rules_lang's
        # c_ast_dump_from_compdb etc.) substitute the sentinel with the
        # actual headers-TreeArtifact path when invoking clang.
        if tok.startswith(build_dir):
            return "${MESON_HEADERS_TREE}" + tok[len(build_dir):]
        return tok

    def _rewrite_flag(flag: str) -> str | None:
        """A `-I<path>` (no space) needs path-rewriting on the inner
        part only, not on the `-I` prefix.

        Critically: a relative inner is recorded relative to meson's
        build_dir (because meson's `directory` field IS build_dir). To
        categorize the path correctly (build-dir-internal vs source-tree
        vs system), we resolve it against build_dir BEFORE applying
        sandbox-stripping or sentinel substitution.
        """
        for prefix in ("-I", "-isystem=", "-iquote=", "-isysroot="):
            if flag.startswith(prefix) and len(flag) > len(prefix):
                inner = flag[len(prefix):]
                if not os.path.isabs(inner):
                    # Relative to build_dir per meson's convention.
                    inner = os.path.normpath(os.path.join(build_dir, inner))
                rewritten = _rewrite_token(inner)
                if rewritten is None:
                    return None
                return prefix + rewritten
        return _rewrite_token(flag)

    # Output-only flags whose argument should be discarded along with them.
    DROP_PAIRED = {"-o", "-MD", "-MF", "-MT", "-MQ"}

    for entry in entries:
        entry["directory"] = "."

        if "file" in entry:
            f = entry["file"]
            if not os.path.isabs(f):
                f = os.path.normpath(os.path.join(build_dir, f))
            entry["file"] = _rewrite_token(f) or f

        # Meson emits EITHER `arguments` (list) or `command` (shell
        # string). Normalize both into a rewritten list and store as
        # `arguments` only (consumers can rely on a uniform shape).
        argv = entry.get("arguments")
        if argv is None and "command" in entry:
            argv = shlex.split(entry["command"])
            entry.pop("command", None)
        if argv is None:
            continue

        new_argv: list[str] = []
        i = 0
        while i < len(argv):
            a = argv[i]
            if a in DROP_PAIRED:
                # Drop this flag and its paired argument.
                i += 2
                continue
            tok = _rewrite_flag(a)
            if tok is None:
                # Output-only artifact under build_dir (object file etc.);
                # drop. We DO preserve -I/-isystem flags pointing into
                # build_dir as ${MESON_HEADERS_TREE} sentinels (see
                # _rewrite_flag).
                i += 1
                continue
            new_argv.append(tok)
            i += 1
        entry["arguments"] = new_argv

    with open(dst, "w", encoding="utf-8") as fh:
        json.dump(entries, fh, indent=2)


if __name__ == "__main__":
    sys.exit(main())
