"""The `vm` rule — declare and boot a virtual machine.

`vm` is both a launchable target (`bazel run //:dev` boots it via the
resolved VMM backend) and a `VmInfo` provider other rules can consume.
It emits a deterministic `<name>.argv` manifest of the VMM command line
for golden testing and `bazel build`-time inspection.

The backend is resolved from the `provider` attribute if set, else from
a registered `//vm:toolchain_type` toolchain. Common devices are typed
attributes; `devices` / `extra_args` are raw passthroughs for the long
tail (virtio-net, virtio-vsock, virtio-gpu, …).
"""

load("//vm:providers.bzl", "VmInfo", "VmProviderInfo")
load("//vm/private:argv.bzl", "build_tokens")

_TOOLCHAIN_TYPE = "@rules_macvm//vm:toolchain_type"

def _parse_mib(s):
    """Parse a memory string like \"2GiB\" / \"512MiB\" / \"1024\" into MiB."""
    s = s.strip()
    for suffix, mult in (("GiB", 1024), ("G", 1024), ("MiB", 1), ("M", 1)):
        if s.endswith(suffix):
            n = s[:-len(suffix)].strip()
            if not n.isdigit():
                fail("vm: bad memory value %r" % s)
            return int(n) * mult
    if not s.isdigit():
        fail("vm: bad memory value %r (use e.g. \"2GiB\", \"512MiB\", or a MiB integer)" % s)
    return int(s)

def _sq(s):
    return "'" + s.replace("'", "'\\''") + "'"

def _render_launch(frags):
    out = []
    for fk, val in frags:
        if fk == "lit":
            out.append(val.replace("\\", "\\\\").replace('"', '\\"'))
        else:
            out.append("$(resolve '%s')" % val.short_path)
    return '"' + "".join(out) + '"'

def _render_manifest(frags):
    return "".join([(val if fk == "lit" else val.short_path) for fk, val in frags])

_PREAMBLE = """\
#!/usr/bin/env bash
# Generated by rules_macvm.
set -euo pipefail

if [[ -z "${{RUNFILES_DIR:-}}" ]]; then
  if [[ -d "$0.runfiles" ]]; then
    RUNFILES_DIR="$0.runfiles"
  fi
fi

WS_NAME={ws_name}

resolve() {{
  local sp="$1"
  if [[ "$sp" == ../* ]]; then
    printf '%s/%s' "${{RUNFILES_DIR}}" "${{sp#../}}"
  else
    printf '%s/%s/%s' "${{RUNFILES_DIR}}" "${{WS_NAME}}" "$sp"
  fi
}}

VMM="$(resolve {vmm_sp})"
if [[ ! -x "$VMM" ]]; then
  echo "rules_macvm: VMM not executable at $VMM" >&2
  exit 2
fi
"""

def _validate(spec, supports, label):
    if spec.kernel and not supports.linux_boot:
        fail("%s: provider lacks Linux direct-boot; drop `kernel`/`initrd` or pick another provider" % label)
    if spec.efi and not supports.efi_boot:
        fail("%s: provider lacks EFI boot; drop `efi = True` or pick another provider" % label)
    if spec.rosetta and not supports.rosetta:
        fail("%s: provider lacks Rosetta; drop `rosetta = True`" % label)
    if spec.nested and not supports.nested:
        fail("%s: provider lacks nested virtualization; drop `nested = True`" % label)

def _vm_impl(ctx):
    # Resolve the backend: explicit attr wins, else the registered toolchain.
    if ctx.attr.provider:
        prov = ctx.attr.provider[VmProviderInfo]
    else:
        tc = ctx.toolchains[_TOOLCHAIN_TYPE]
        if tc == None:
            fail("%s: no VMM provider. Set `provider = ...` or register a " % ctx.label +
                 "`//vm:toolchain_type` toolchain (e.g. @vfkit//:vfkit_toolchain_def).")
        prov = tc.vmprovider

    if len(ctx.files.cloud_init) > 2:
        fail("%s: cloud_init takes at most 2 files (user-data, meta-data)" % ctx.label)

    spec = struct(
        cpus = ctx.attr.cpus,
        memory_mib = _parse_mib(ctx.attr.memory),
        kernel = ctx.file.kernel,
        initrd = ctx.file.initrd,
        kernel_cmdline = ctx.attr.kernel_cmdline,
        efi = ctx.attr.efi,
        disks = ctx.files.disks,
        rosetta = ctx.attr.rosetta,
        ignition = ctx.file.ignition,
        cloud_init = ctx.files.cloud_init,
        nested = ctx.attr.nested,
        gui = ctx.attr.gui,
        restful_uri = ctx.attr.restful_uri,
        devices = ctx.attr.devices,
        extra_args = ctx.attr.extra_args,
    )
    _validate(spec, prov.supports, ctx.label)

    tokens = build_tokens(prov.kind, spec)

    # Deterministic manifest (short_paths) for golden tests + inspection.
    manifest_lines = ["# kind: %s" % prov.kind] + [_render_manifest(tok) for tok in tokens]
    ctx.actions.write(ctx.outputs.argv_manifest, "\n".join(manifest_lines) + "\n")

    # Runtime launcher (resolved absolutes).
    vmm_exe = prov.vmm[DefaultInfo].files_to_run.executable
    launch_tokens = " ".join([_render_launch(tok) for tok in tokens])
    body = """
VM_RUNTIME="$(mktemp -d "${{TMPDIR:-/tmp}}/macvm.XXXXXX")"
trap 'rm -rf "$VM_RUNTIME"' EXIT

exec "$VMM" {tokens} "$@"
""".format(tokens = launch_tokens)

    launcher = ctx.actions.declare_file(ctx.label.name + ".sh")
    ctx.actions.write(
        output = launcher,
        is_executable = True,
        content = _PREAMBLE.format(
            ws_name = _sq(ctx.workspace_name),
            vmm_sp = _sq(vmm_exe.short_path),
        ) + body,
    )

    spec_files = [f for f in [ctx.file.kernel, ctx.file.initrd, ctx.file.ignition] if f]
    spec_files += ctx.files.disks + ctx.files.cloud_init
    runfiles = ctx.runfiles(files = [launcher] + spec_files).merge(
        prov.vmm[DefaultInfo].default_runfiles,
    )

    return [
        DefaultInfo(
            executable = launcher,
            files = depset([launcher, ctx.outputs.argv_manifest]),
            runfiles = runfiles,
        ),
        VmInfo(
            kind = prov.kind,
            cpus = spec.cpus,
            memory_mib = spec.memory_mib,
            launcher = launcher,
            argv_manifest = ctx.outputs.argv_manifest,
        ),
        OutputGroupInfo(argv = depset([ctx.outputs.argv_manifest])),
    ]

vm = rule(
    implementation = _vm_impl,
    executable = True,
    outputs = {"argv_manifest": "%{name}.argv"},
    attrs = {
        "cpus": attr.int(default = 1, doc = "Number of virtual CPUs."),
        "memory": attr.string(default = "512MiB", doc = "RAM, e.g. \"2GiB\" / \"512MiB\" / a MiB integer."),
        "kernel": attr.label(allow_single_file = True, doc = "Linux kernel image for direct boot."),
        "initrd": attr.label(allow_single_file = True, doc = "initrd/initramfs for direct boot."),
        "kernel_cmdline": attr.string(default = "", doc = "Linux kernel command line."),
        "efi": attr.bool(default = False, doc = "EFI-boot a disk image (instead of a direct kernel)."),
        "disks": attr.label_list(allow_files = True, doc = "Disk images attached as virtio-blk devices."),
        "rosetta": attr.bool(default = False, doc = "Expose Rosetta x86-64 translation (virtio share `rosetta`)."),
        "ignition": attr.label(allow_single_file = True, doc = "Ignition provisioning file (FCOS-style)."),
        "cloud_init": attr.label_list(allow_files = True, doc = "cloud-init files: user-data and (optionally) meta-data."),
        "nested": attr.bool(default = False, doc = "Enable nested virtualization (M3+)."),
        "gui": attr.bool(default = False, doc = "Open a graphical window for the VM."),
        "restful_uri": attr.string(default = "", doc = "URI for the VMM's RESTful lifecycle control plane."),
        "devices": attr.string_list(default = [], doc = "Raw `--device` specs (virtio-net, virtio-vsock, virtio-gpu, …)."),
        "extra_args": attr.string_list(default = [], doc = "Raw flags appended to the VMM invocation."),
        "provider": attr.label(
            providers = [VmProviderInfo],
            doc = "VMM backend override. If unset, the registered //vm:toolchain_type toolchain is used.",
        ),
    },
    toolchains = [config_common.toolchain_type(_TOOLCHAIN_TYPE, mandatory = False)],
    doc = "Declare and boot a VM via a resolved VMM backend. Emits VmInfo + a `<name>.argv` manifest.",
)
