"""Module extension that produces the @uv repo with the uv binary.

Two interchangeable paths, picked via the `toolchain` tag's
`source` attribute:

  source = "build"      (default)
     Fetches astral-sh/uv source as @uv_source, then bootstraps a
     release-mode build with rules_rust's `cargo_bootstrap_repository`.
     ~12-minute cold build; cached across subsequent ones. Highest
     hermeticity (Rust toolchain + uv source revision both pinned).

  source = "prebuilt"
     http_archive's the official release tarball for the host
     platform from `astral-sh/uv` releases. Skips the cold build.
     Requires a sha256 in `private/known_versions.bzl` for the
     active version + host platform.

Both modes produce the same target shape: `@uv//:binary` is the uv
executable. The build path also exposes `@uv//:install` (a
`rust_binary` wrapper from `cargo_bootstrap_repository`); the
prebuilt path doesn't, but the toolchain refers to `:binary` so
downstream rules don't notice the difference.

Pin a different uv version or switch to prebuilt:

    uv = use_extension("@rules_uv//uv:extensions.bzl", "uv")
    uv.toolchain(version = "0.11.15", source = "prebuilt")
    use_repo(uv, "uv", "uv_source")

`uv_source` is always exported. When `source = "prebuilt"`, the
repo is empty (a stub BUILD with no targets) — it's kept in the
`use_repo` list so consumers don't have to vary their `use_repo`
call by source choice.
"""

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
load("@rules_rust//cargo:defs.bzl", "cargo_bootstrap_repository")
load(
    "//uv/private:known_versions.bzl",
    "DEFAULT_VERSION",
    "KNOWN_PREBUILT_SHAS",
    "KNOWN_VERSIONS",
    "PREBUILT_PLATFORMS",
    "PREBUILT_URL_TEMPLATE",
    "URL_TEMPLATE",
)

# Canonical names returned by `mctx.os` are not stable across hosts —
# macOS reports "mac os x", Linux returns "linux"; arch is "aarch64",
# "x86_64", or sometimes "amd64". Normalize once at the top.
def _host_platform(mctx):
    os_name = mctx.os.name.lower()
    arch = mctx.os.arch.lower()
    if "mac os" in os_name or "darwin" in os_name:
        os_canonical = "darwin"
    elif "linux" in os_name:
        os_canonical = "linux"
    elif "windows" in os_name:
        os_canonical = "windows"
    else:
        fail("rules_uv: unsupported host OS: {}".format(mctx.os.name))

    if arch in ("aarch64", "arm64"):
        arch_canonical = "aarch64"
    elif arch in ("x86_64", "amd64"):
        arch_canonical = "x86_64"
    else:
        fail("rules_uv: unsupported host arch: {}".format(mctx.os.arch))

    return "{}_{}".format(os_canonical, arch_canonical)

# Bazel-extension overlay for the @uv_source repo (build path). For
# the prebuilt path, this is a stub so `use_repo(uv, "uv_source")`
# still resolves to *something*.
_UV_SOURCE_STUB_BUILD = """\
# Placeholder generated by rules_uv when source = "prebuilt". The
# build path overlays a richer BUILD; this stub just keeps @uv_source
# resolvable from `use_repo` calls that don't vary by mode.
package(default_visibility = ["//visibility:public"])
"""

# Per-platform BUILD content for the prebuilt @uv repo. The release
# tarball unpacks into `uv-<triple>/uv`, which `strip_prefix` strips
# down to just `uv`.
_PREBUILT_UV_BUILD = """\
package(default_visibility = ["//visibility:public"])

# Match the cargo_bootstrap_repository BUILD shape so downstream
# rules can reference `@uv//:binary` identically across modes.
exports_files(["uv"])

alias(
    name = "binary",
    actual = ":uv",
)
"""

def _build_path(version):
    sha256 = KNOWN_VERSIONS.get(version, "")
    if not sha256:
        print(  # buildifier: disable=print
            "rules_uv: uv source sha256 for {} is not pinned; fetching unpinned".format(version),
        )

    http_archive(
        name = "uv_source",
        url = URL_TEMPLATE.format(version = version),
        sha256 = sha256,
        strip_prefix = "uv-{}".format(version),
        build_file = "@rules_uv//uv/private:uv_source.BUILD.bazel",
    )

    # rules_rust under bzlmod canonicalizes the toolchain tools repos
    # as `@@rules_rust++rust+rust_<system>_<arch>__<triple>__<channel>_tools`,
    # so the default templates (`@rust_..._tools//...`) don't resolve.
    # Inline the canonical prefix so cargo_bootstrap_repository finds
    # `cargo` / `rustc` regardless of the consumer's repo namespace.
    canonical_template = "@@rules_rust++rust+rust_{system}_{arch}__{triple}__{channel}_tools//:bin/{tool}"

    cargo_bootstrap_repository(
        name = "uv",
        cargo_lockfile = "@uv_source//:Cargo.lock",
        cargo_toml = "@uv_source//:Cargo.toml",
        srcs = ["@uv_source//:srcs"],
        binary = "uv",
        version = "1.95.0",
        build_mode = "release",
        rust_toolchain_cargo_template = canonical_template,
        rust_toolchain_rustc_template = canonical_template,
        # uv's build occasionally takes longer than the default 600s
        # ceiling on cold builds (clean crates.io cache, no sccache).
        timeout = 1800,
    )

def _prebuilt_path(mctx, version):
    platform = _host_platform(mctx)
    triple = PREBUILT_PLATFORMS.get(platform)
    if not triple:
        fail(
            "rules_uv: source = \"prebuilt\" doesn't yet support {} " +
            "(supported: {}). Fall back to source = \"build\" or add an " +
            "entry to PREBUILT_PLATFORMS + KNOWN_PREBUILT_SHAS.".format(
                platform,
                sorted(PREBUILT_PLATFORMS.keys()),
            ),
        )
    sha = KNOWN_PREBUILT_SHAS.get(version, {}).get(platform, "")
    if not sha:
        print(  # buildifier: disable=print
            "rules_uv: prebuilt sha for uv {} on {} is not pinned; fetching unpinned".format(
                version,
                platform,
            ),
        )

    http_archive(
        name = "uv",
        url = PREBUILT_URL_TEMPLATE.format(version = version, triple = triple),
        sha256 = sha,
        # The asset unpacks to `uv-<triple>/uv`; strip the wrapper
        # directory so `@uv//:uv` is the executable at repo root.
        strip_prefix = "uv-{}".format(triple),
        build_file_content = _PREBUILT_UV_BUILD,
    )

    # Stub @uv_source so the consumer's `use_repo(uv, "uv", "uv_source")`
    # call resolves regardless of mode.
    _empty_repo(name = "uv_source")

def _uv_extension_impl(mctx):
    version = DEFAULT_VERSION
    source = "build"
    for mod in mctx.modules:
        for tag in mod.tags.toolchain:
            if tag.version:
                version = tag.version
            if tag.source:
                source = tag.source

    if source == "build":
        _build_path(version)
    elif source == "prebuilt":
        _prebuilt_path(mctx, version)
    else:
        fail("rules_uv: unknown source {!r} (want \"build\" or \"prebuilt\")".format(source))

_toolchain_tag = tag_class(attrs = {
    "version": attr.string(
        default = "",
        doc = "Override uv version. Defaults to known_versions.DEFAULT_VERSION.",
    ),
    "source": attr.string(
        default = "",
        values = ["", "build", "prebuilt"],
        doc = "Where the uv binary comes from. " +
              "`build` (default) bootstraps from source via " +
              "rules_rust's `cargo_bootstrap_repository`. " +
              "`prebuilt` fetches the official release asset for " +
              "the host platform.",
    ),
})

uv = module_extension(
    implementation = _uv_extension_impl,
    tag_classes = {"toolchain": _toolchain_tag},
    doc = "Materialize the uv binary (build from source or fetch prebuilt).",
)

def _empty_repo_impl(rctx):
    rctx.file("BUILD.bazel", _UV_SOURCE_STUB_BUILD)
    rctx.file("WORKSPACE", "")

_empty_repo = repository_rule(
    implementation = _empty_repo_impl,
    doc = "Stub repo used when @uv_source is not needed for the active mode.",
)
