//! Starlark `.bzl` emission from classified schema definitions.
//!
//! Two responsibilities split out of `main.rs`:
//!
//!   * `emit_preamble` writes the file-header comment + `load(...)`
//!     of `strip_unset` / `parse_json_or_none`.
//!
//! ⛔ `strip_unset`, NOT `strip_empty`. The latter also drops `False`/`0`/`[]`/`{}`,
//! which makes an explicitly requested `false` indistinguishable from an omission —
//! and that fails OPEN whenever the schema default is truthy. Measured in
//! tomato-bazel/rules_cloudformation#2 on `EmptyOnDelete = "false"`, which rendered
//! as no key at all. `strip_empty` remains exported for already-generated files.
//!   * `emit_rule` writes one `provider() + def _impl(): + rule()`
//!     trio per schema definition the caller requested.
//!
//! Stays schema-agnostic — no compose-spec assumptions leak into
//! the generated docstrings. Callers wanting consumer-specific text
//! can post-process the output.

use std::fmt::Write as _;

use anyhow::Result;
use serde_json::Value;

use crate::classifier::{property_to_attr, AttrSpec};
use crate::Kind;

pub fn emit_preamble(out: &mut String, schema_path: &str) {
    let _ = writeln!(out, "# @generated by rules_jsonschema//tools/schema_to_starlark. DO NOT EDIT.");
    let _ = writeln!(out, "#");
    let _ = writeln!(out, "# Source schema: {}", schema_path);
    let _ = writeln!(out, "#");
    let _ = writeln!(out, "# Refresh via the generating rule's `update` script;");
    let _ = writeln!(out, "# the diff_test will fail until you do.");
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        r#"load("@rules_jsonschema//runtime:helpers.bzl", "parse_json_or_none", "strip_unset")"#
    );
    let _ = writeln!(out);
}

pub fn emit_rule(out: &mut String, kind: &Kind, def: &Value, root: &Value) -> Result<()> {
    let properties = def
        .get("properties")
        .and_then(Value::as_object)
        .ok_or_else(|| anyhow::anyhow!("definition {} has no `properties`", kind.pointer))?;

    // Sort property names for deterministic output. Diff_test relies
    // on this being stable across builds.
    let mut prop_names: Vec<&String> = properties.keys().collect();
    prop_names.sort();

    let attr_specs: Vec<(String, AttrSpec, String)> = prop_names
        .iter()
        .map(|name| {
            let raw_prop = &properties[*name];
            // Take the description from the property's own slot if
            // it has one (e.g. "Override the image's ENTRYPOINT.");
            // fall back to the referenced definition's description
            // only when the property didn't author its own.
            let doc = raw_prop
                .get("description")
                .and_then(Value::as_str)
                .map(String::from)
                .unwrap_or_default();
            let resolved = crate::classifier::deref(raw_prop, root);
            let ref_name = raw_prop.get("$ref").and_then(Value::as_str);
            let spec = property_to_attr(resolved, ref_name, root);
            ((*name).clone(), spec, doc)
        })
        .collect();

    // --- provider ---
    let _ = writeln!(
        out,
        r#"{prov} = provider(
    doc = "A {id} contributed by a target. Shard JSON matches the {id} schema.",
    fields = {{
        "{id}_name": "string: top-level key for this {id} in the rendered project.",
        "json": "File: the JSON shard.",
    }},
)
"#,
        prov = kind.provider_name,
        id = kind.id
    );

    // --- impl ---
    let _ = writeln!(out, "def _{}_impl(ctx):", kind.rule_name);
    let _ = writeln!(out, "    item_name = ctx.attr.{}_name or ctx.label.name", kind.id);
    let _ = writeln!(out, "    payload = {{");
    for (name, spec, _doc) in &attr_specs {
        let attr_name = sanitize_attr_name(name);
        let getter = format!("ctx.attr.{attr_name}");
        match spec {
            AttrSpec::JsonString => {
                let _ = writeln!(out, "        \"{name}\": parse_json_or_none({getter}),");
            }
            _ => {
                let _ = writeln!(out, "        \"{name}\": {getter},");
            }
        }
    }
    let _ = writeln!(out, "    }}");
    let _ = writeln!(out, "    payload = strip_unset(payload)");
    let _ = writeln!(
        out,
        r#"    shard = ctx.actions.declare_file(ctx.label.name + ".{id}.json")"#,
        id = kind.id
    );
    let _ = writeln!(out, "    ctx.actions.write(shard, json.encode(payload))");
    let _ = writeln!(out, "    return [");
    let _ = writeln!(out, "        DefaultInfo(files = depset([shard])),");
    let _ = writeln!(
        out,
        "        {prov}({id}_name = item_name, json = shard),",
        prov = kind.provider_name,
        id = kind.id
    );
    let _ = writeln!(out, "    ]");
    let _ = writeln!(out);

    // --- rule definition ---
    let _ = writeln!(out, "{} = rule(", kind.rule_name);
    let _ = writeln!(out, "    implementation = _{}_impl,", kind.rule_name);
    if let Some(desc) = def.get("description").and_then(Value::as_str) {
        let _ = writeln!(out, "    doc = {},", starlark_str_literal(desc));
    } else {
        let _ = writeln!(
            out,
            "    doc = \"Schema-derived rule for one `{}` entry.\",",
            kind.id
        );
    }
    let _ = writeln!(out, "    provides = [{prov}],", prov = kind.provider_name);
    let _ = writeln!(out, "    attrs = {{");
    let _ = writeln!(
        out,
        "        \"{id}_name\": attr.string(\n            doc = \"Top-level key for this {id} in the rendered project. Defaults to the rule name.\",\n        ),",
        id = kind.id
    );
    for (name, spec, doc) in &attr_specs {
        let attr_name = sanitize_attr_name(name);
        let attr_call = attr_spec_starlark(spec, doc);
        let _ = writeln!(out, "        \"{attr_name}\": {attr_call},");
    }
    let _ = writeln!(out, "    }},");
    let _ = writeln!(out, ")");
    let _ = writeln!(out);
    Ok(())
}

/// Render an `AttrSpec` as the Starlark `attr.*(...)` call site.
pub fn attr_spec_starlark(spec: &AttrSpec, doc: &str) -> String {
    let doc_arg = if doc.is_empty() {
        String::new()
    } else {
        format!("\n            doc = {},\n        ", starlark_str_literal(doc))
    };
    match spec {
        AttrSpec::String => format!("attr.string({doc_arg})"),
        AttrSpec::EnumString(values) => {
            let v: Vec<String> = values.iter().map(|s| starlark_str_literal(s)).collect();
            format!(
                "attr.string(\n            values = [{}],{doc_arg})",
                v.join(", ")
            )
        }
        AttrSpec::Int => format!("attr.int({doc_arg})"),
        AttrSpec::Bool => format!("attr.bool({doc_arg})"),
        AttrSpec::StringList => format!("attr.string_list({doc_arg})"),
        AttrSpec::StringDict => format!("attr.string_dict({doc_arg})"),
        AttrSpec::JsonString => {
            let doc_text = if doc.is_empty() {
                "JSON-encoded value. The shard reader deserialises the parsed JSON straight into the typed schema model.".to_string()
            } else {
                format!(
                    "{} (JSON-encoded; the Rust shard reader parses this verbatim.)",
                    doc
                )
            };
            format!(
                "attr.string(\n            doc = {},\n        )",
                starlark_str_literal(&doc_text)
            )
        }
    }
}

/// Map a schema property name to a safe Bazel attr name. The schema
/// key in the emitted JSON shard is always the original name; only
/// the `ctx.attr.<...>` Starlark binding changes. Two collision
/// sources:
///
///   * `name` — Bazel forbids overriding the built-in `name` attr.
///     Compose-spec uses `name` for the runtime resource override
///     (the Compose project name on volumes/networks). We rename to
///     `name_override` so user code can still set it.
///   * Starlark keywords — none are in compose-spec today but this
///     future-proofs against schemas that use them.
pub fn sanitize_attr_name(name: &str) -> String {
    const RESERVED: &[&str] = &[
        "True", "False", "None", "and", "or", "not", "if", "else", "for", "in",
        "return", "def", "load", "pass", "break", "continue", "lambda",
    ];
    if name == "name" {
        return "name_override".to_string();
    }
    if RESERVED.contains(&name) {
        format!("{name}_")
    } else {
        name.to_string()
    }
}

/// Emit a Starlark string literal that safely encodes the input.
/// Always uses double-quotes; escapes `"` and `\`. Newlines collapse
/// into spaces because Bazel attr docs render on a single line in
/// stardoc anyway.
pub fn starlark_str_literal(s: &str) -> String {
    let cleaned: String = s
        .chars()
        .map(|c| match c {
            '\n' | '\r' => ' ',
            c => c,
        })
        .collect();
    let escaped: String = cleaned
        .chars()
        .map(|c| match c {
            '\\' => "\\\\".to_string(),
            '"' => "\\\"".to_string(),
            c => c.to_string(),
        })
        .collect();
    format!("\"{escaped}\"")
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn sanitize_attr_name_renames_name() {
        assert_eq!(sanitize_attr_name("name"), "name_override");
    }

    #[test]
    fn sanitize_attr_name_keyword_renaming() {
        assert_eq!(sanitize_attr_name("return"), "return_");
        assert_eq!(sanitize_attr_name("plain_field"), "plain_field");
    }

    #[test]
    fn starlark_str_literal_escapes() {
        assert_eq!(starlark_str_literal(r#"he said "hi""#), r#""he said \"hi\"""#);
        assert_eq!(starlark_str_literal("a\\b"), r#""a\\b""#);
        assert_eq!(starlark_str_literal("a\nb"), r#""a b""#);
    }

    #[test]
    fn attr_spec_starlark_strings_have_no_doc_arg_when_empty() {
        let out = attr_spec_starlark(&AttrSpec::String, "");
        assert_eq!(out, "attr.string()");
    }

    #[test]
    fn attr_spec_starlark_enum_renders_values() {
        let out = attr_spec_starlark(&AttrSpec::EnumString(vec!["a".into(), "b".into()]), "");
        assert!(out.contains("values = [\"a\", \"b\"]"), "got: {out}");
    }

    #[test]
    fn attr_spec_starlark_json_string_describes_purpose() {
        let with_doc = attr_spec_starlark(&AttrSpec::JsonString, "Build context.");
        assert!(with_doc.contains("Build context."), "{with_doc}");
        assert!(
            with_doc.contains("JSON-encoded"),
            "JsonString fallback should explain itself: {with_doc}",
        );

        let no_doc = attr_spec_starlark(&AttrSpec::JsonString, "");
        assert!(no_doc.contains("JSON-encoded"), "{no_doc}");
    }

    // --- emit_rule snapshot ------------------------------------------

    #[test]
    fn emit_rule_smoke_snapshot() {
        // Synthetic schema with one property of each interesting
        // shape — this is the regression net for the emission path.
        let def = json!({
            "description": "A person record.",
            "properties": {
                "name": {"type": "string", "description": "Their full name."},
                "age": {"type": "integer", "description": "Age in years."},
                "active": {"type": "boolean"},
                "tags": {"type": "array", "items": {"type": "string"}},
                "labels": {
                    "type": "object",
                    "additionalProperties": {"type": "string"}
                },
                "role": {"enum": ["admin", "guest", "service"]},
                "address": {
                    "type": "object",
                    "properties": {"line1": {"type": "string"}}
                }
            }
        });
        let kind = Kind {
            id: "person".into(),
            pointer: "#".into(),
            rule_name: "person".into(),
            provider_name: "PersonInfo".into(),
        };

        let mut out = String::new();
        emit_rule(&mut out, &kind, &def, &Value::Null).unwrap();

        // Provider + impl + rule should all be present.
        assert!(out.contains("PersonInfo = provider("), "{out}");
        assert!(out.contains("def _person_impl(ctx):"), "{out}");
        assert!(out.contains("person = rule("), "{out}");

        // Rule doc is sourced from definition.description.
        assert!(out.contains(r#"doc = "A person record.""#), "{out}");

        // `name` schema property → `name_override` Bazel attr but
        // JSON key stays `name`.
        assert!(out.contains(r#""name": ctx.attr.name_override,"#), "{out}");
        assert!(out.contains(r#""name_override": attr.string("#), "{out}");

        // Each property type maps correctly.
        assert!(out.contains("\"age\": attr.int("), "{out}");
        assert!(out.contains("\"active\": attr.bool("), "{out}");
        assert!(out.contains("\"tags\": attr.string_list("), "{out}");
        assert!(out.contains("\"labels\": attr.string_dict("), "{out}");
        // Enum renders values list.
        assert!(
            out.contains(r#"values = ["admin", "guest", "service"]"#),
            "{out}"
        );
        // Nested object → JsonString fallback at top-level.
        assert!(
            out.contains(r#"parse_json_or_none(ctx.attr.address)"#),
            "{out}"
        );

        // No compose-specific leakage in the generic emitter.
        assert!(
            !out.contains("compose"),
            "generic emitter shouldn't mention 'compose': {out}"
        );
    }
}
