package main

import "os"

// getenvDefault is vendored from rules_go's gopackagesdriver/utils.go. The rest
// of that file serves the bazel-subprocess path and is not vendored.
//
// build_context.go reads GOTAGS through this to build the tag set that filters
// source files. Note rules_go's driver takes tags from this env var and NOT from
// DriverRequest.BuildFlags, so a caller passing `-tags foo` through go/packages
// is silently ignored. That's upstream behavior we inherit deliberately: for CRD
// generation it is verifiably harmless (feeding zz_generated.deepcopy.go in
// yields a byte-identical CRD, so `-tags ignore_autogenerated` changes nothing),
// but it WOULD matter if this driver is ever reused for object/deepcopy gen.
func getenvDefault(key, defaultValue string) string {
	if v, ok := os.LookupEnv(key); ok {
		return v
	}
	return defaultValue
}
