// Generated by delombok at Tue May 19 16:38:52 EDT 2026
package aws.cfn.codegen;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Optional;

/**
 * Describes the higher level Attributes in CFN.
 * @see <a href="http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification-format.html>Specification</a>
 */
public class AttributeType {
    @JsonProperty(required = true)
    private String type;
    private String itemType;
    private String primitiveType;
    private String primitiveItemType;

    public boolean isCollectionType() {
        return !isPrimitive() && "List".equals(type);
    }

    public boolean isMapType() {
        return !isPrimitive() && "Map".equals(type);
    }

    public boolean isPrimitive() {
        return primitiveType != null || "Json".equals(type);
    }

    public boolean isContainerType() {
        return "List".equals(type) || "Map".equals(type);
    }

    public boolean isObjectType() {
        return !isContainerType() && !isPrimitive() && type != null;
    }

    public boolean isContainerInnerTypePrimitive() {
        return isContainerType() && primitiveItemType != null;
    }

    public Optional<String> getListOrMapPrimitiveType() {
        return Optional.ofNullable(primitiveItemType);
    }

    public Optional<String> getComplexType() {
        // If type is primitive then type == null
        if ("List".equals(type) || "Map".equals(type)) {
            return Optional.ofNullable(itemType);
        }
        // Json shows up in type but CFN calls this primitive type. Let us honor it
        return Optional.ofNullable("Json".equals(type) ? null : type);
    }

    public String getPrimitiveType() {
        return primitiveType;
    }

    @java.lang.SuppressWarnings("all")
    
    public String getType() {
        return this.type;
    }

    @java.lang.SuppressWarnings("all")
    
    public String getItemType() {
        return this.itemType;
    }

    @java.lang.SuppressWarnings("all")
    
    public String getPrimitiveItemType() {
        return this.primitiveItemType;
    }

    @JsonProperty(required = true)
    @java.lang.SuppressWarnings("all")
    
    public void setType(final String type) {
        this.type = type;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setItemType(final String itemType) {
        this.itemType = itemType;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setPrimitiveType(final String primitiveType) {
        this.primitiveType = primitiveType;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setPrimitiveItemType(final String primitiveItemType) {
        this.primitiveItemType = primitiveItemType;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    
    public java.lang.String toString() {
        return "AttributeType(type=" + this.getType() + ", itemType=" + this.getItemType() + ", primitiveType=" + this.getPrimitiveType() + ", primitiveItemType=" + this.getPrimitiveItemType() + ")";
    }

    @java.lang.SuppressWarnings("all")
    
    public AttributeType() {
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof AttributeType)) return false;
        final AttributeType other = (AttributeType) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$type = this.getType();
        final java.lang.Object other$type = other.getType();
        if (this$type == null ? other$type != null : !this$type.equals(other$type)) return false;
        final java.lang.Object this$itemType = this.getItemType();
        final java.lang.Object other$itemType = other.getItemType();
        if (this$itemType == null ? other$itemType != null : !this$itemType.equals(other$itemType)) return false;
        final java.lang.Object this$primitiveType = this.getPrimitiveType();
        final java.lang.Object other$primitiveType = other.getPrimitiveType();
        if (this$primitiveType == null ? other$primitiveType != null : !this$primitiveType.equals(other$primitiveType)) return false;
        final java.lang.Object this$primitiveItemType = this.getPrimitiveItemType();
        final java.lang.Object other$primitiveItemType = other.getPrimitiveItemType();
        if (this$primitiveItemType == null ? other$primitiveItemType != null : !this$primitiveItemType.equals(other$primitiveItemType)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof AttributeType;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $type = this.getType();
        result = result * PRIME + ($type == null ? 43 : $type.hashCode());
        final java.lang.Object $itemType = this.getItemType();
        result = result * PRIME + ($itemType == null ? 43 : $itemType.hashCode());
        final java.lang.Object $primitiveType = this.getPrimitiveType();
        result = result * PRIME + ($primitiveType == null ? 43 : $primitiveType.hashCode());
        final java.lang.Object $primitiveItemType = this.getPrimitiveItemType();
        result = result * PRIME + ($primitiveItemType == null ? 43 : $primitiveItemType.hashCode());
        return result;
    }
}
