// Generated by delombok at Tue May 19 16:38:52 EDT 2026
package aws.cfn.codegen;

import java.util.AbstractCollection;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

/**
 * A simple class the represents CFN resource specification. Properties defined within CFN specification
 * are also defined exactly like a Resource.
 *
 * @see <a href="https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification-format.html>CFN Spec</a>
 */
public class CfnSpecification {
    private String resourceSpecificationVersion;
    private Map<String, ResourceType> propertyTypes = new HashMap<>(256);
    private Map<String, ResourceType> resourceTypes = new HashMap<>(256);

    public void validate() throws CfnSpecificationException {
        resourceTypes.forEach((name, type) -> {
            type.getProperties().forEach((propName, propType) -> {
                propType.getComplexType().ifPresent(cplx -> {
                    if (!propertyTypes.containsKey(name + "." + cplx) && !propertyTypes.containsKey(cplx)) {
                        throw new CfnSpecificationException(cplx + " referenced but not defined in " + name);
                    }
                });
            });
        });
    }


    public static class Difference {
        private String fromVersion;
        private ResourceType fromType;
        private String toVersion;
        private ResourceType toType;

        @java.lang.SuppressWarnings("all")
        
        public Difference() {
        }

        @java.lang.SuppressWarnings("all")
        
        public String getFromVersion() {
            return this.fromVersion;
        }

        @java.lang.SuppressWarnings("all")
        
        public ResourceType getFromType() {
            return this.fromType;
        }

        @java.lang.SuppressWarnings("all")
        
        public String getToVersion() {
            return this.toVersion;
        }

        @java.lang.SuppressWarnings("all")
        
        public ResourceType getToType() {
            return this.toType;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setFromVersion(final String fromVersion) {
            this.fromVersion = fromVersion;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setFromType(final ResourceType fromType) {
            this.fromType = fromType;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setToVersion(final String toVersion) {
            this.toVersion = toVersion;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setToType(final ResourceType toType) {
            this.toType = toType;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public java.lang.String toString() {
            return "CfnSpecification.Difference(fromVersion=" + this.getFromVersion() + ", fromType=" + this.getFromType() + ", toVersion=" + this.getToVersion() + ", toType=" + this.getToType() + ")";
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof CfnSpecification.Difference)) return false;
            final CfnSpecification.Difference other = (CfnSpecification.Difference) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            final java.lang.Object this$fromVersion = this.getFromVersion();
            final java.lang.Object other$fromVersion = other.getFromVersion();
            if (this$fromVersion == null ? other$fromVersion != null : !this$fromVersion.equals(other$fromVersion)) return false;
            final java.lang.Object this$fromType = this.getFromType();
            final java.lang.Object other$fromType = other.getFromType();
            if (this$fromType == null ? other$fromType != null : !this$fromType.equals(other$fromType)) return false;
            final java.lang.Object this$toVersion = this.getToVersion();
            final java.lang.Object other$toVersion = other.getToVersion();
            if (this$toVersion == null ? other$toVersion != null : !this$toVersion.equals(other$toVersion)) return false;
            final java.lang.Object this$toType = this.getToType();
            final java.lang.Object other$toType = other.getToType();
            if (this$toType == null ? other$toType != null : !this$toType.equals(other$toType)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof CfnSpecification.Difference;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            final java.lang.Object $fromVersion = this.getFromVersion();
            result = result * PRIME + ($fromVersion == null ? 43 : $fromVersion.hashCode());
            final java.lang.Object $fromType = this.getFromType();
            result = result * PRIME + ($fromType == null ? 43 : $fromType.hashCode());
            final java.lang.Object $toVersion = this.getToVersion();
            result = result * PRIME + ($toVersion == null ? 43 : $toVersion.hashCode());
            final java.lang.Object $toType = this.getToType();
            result = result * PRIME + ($toType == null ? 43 : $toType.hashCode());
            return result;
        }
    }

    public Set<Difference> findDiff(CfnSpecification toSpec) {
        return resourceTypes.entrySet().stream().filter(entry -> toSpec.resourceTypes.containsKey(entry.getKey())).collect(HashSet::new, (diffSet, e) -> {
            if (!toSpec.getResourceTypes().get(e.getKey()).equals(e)) {
                Difference diff = new Difference();
                diff.setFromType(e.getValue());
                diff.setFromVersion(resourceSpecificationVersion);
                diff.setToType(toSpec.getResourceTypes().get(e.getKey()));
                diff.setToVersion(toSpec.getResourceSpecificationVersion());
                diffSet.add(diff);
            }
        }, AbstractCollection::addAll);
    }

    @java.lang.SuppressWarnings("all")
    
    public CfnSpecification() {
    }

    @java.lang.SuppressWarnings("all")
    
    public String getResourceSpecificationVersion() {
        return this.resourceSpecificationVersion;
    }

    @java.lang.SuppressWarnings("all")
    
    public Map<String, ResourceType> getPropertyTypes() {
        return this.propertyTypes;
    }

    @java.lang.SuppressWarnings("all")
    
    public Map<String, ResourceType> getResourceTypes() {
        return this.resourceTypes;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setResourceSpecificationVersion(final String resourceSpecificationVersion) {
        this.resourceSpecificationVersion = resourceSpecificationVersion;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setPropertyTypes(final Map<String, ResourceType> propertyTypes) {
        this.propertyTypes = propertyTypes;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setResourceTypes(final Map<String, ResourceType> resourceTypes) {
        this.resourceTypes = resourceTypes;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof CfnSpecification)) return false;
        final CfnSpecification other = (CfnSpecification) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$resourceSpecificationVersion = this.getResourceSpecificationVersion();
        final java.lang.Object other$resourceSpecificationVersion = other.getResourceSpecificationVersion();
        if (this$resourceSpecificationVersion == null ? other$resourceSpecificationVersion != null : !this$resourceSpecificationVersion.equals(other$resourceSpecificationVersion)) return false;
        final java.lang.Object this$propertyTypes = this.getPropertyTypes();
        final java.lang.Object other$propertyTypes = other.getPropertyTypes();
        if (this$propertyTypes == null ? other$propertyTypes != null : !this$propertyTypes.equals(other$propertyTypes)) return false;
        final java.lang.Object this$resourceTypes = this.getResourceTypes();
        final java.lang.Object other$resourceTypes = other.getResourceTypes();
        if (this$resourceTypes == null ? other$resourceTypes != null : !this$resourceTypes.equals(other$resourceTypes)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof CfnSpecification;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $resourceSpecificationVersion = this.getResourceSpecificationVersion();
        result = result * PRIME + ($resourceSpecificationVersion == null ? 43 : $resourceSpecificationVersion.hashCode());
        final java.lang.Object $propertyTypes = this.getPropertyTypes();
        result = result * PRIME + ($propertyTypes == null ? 43 : $propertyTypes.hashCode());
        final java.lang.Object $resourceTypes = this.getResourceTypes();
        result = result * PRIME + ($resourceTypes == null ? 43 : $resourceTypes.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    
    public java.lang.String toString() {
        return "CfnSpecification(resourceSpecificationVersion=" + this.getResourceSpecificationVersion() + ", propertyTypes=" + this.getPropertyTypes() + ", resourceTypes=" + this.getResourceTypes() + ")";
    }
}
