// Generated by delombok at Tue May 19 16:38:52 EDT 2026
package aws.cfn.codegen;

/**
 * This defines a CFN's Resource's Property Type.
 *
 * @see <a href="http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification-format.html>Specification</a>
 */
public class PropertyType extends AttributeType {
    private String documentation;
    private Boolean duplicatesAllowed;
    private String updateType;
    private Boolean required;

    @java.lang.SuppressWarnings("all")
    
    public String getDocumentation() {
        return this.documentation;
    }

    @java.lang.SuppressWarnings("all")
    
    public Boolean getDuplicatesAllowed() {
        return this.duplicatesAllowed;
    }

    @java.lang.SuppressWarnings("all")
    
    public String getUpdateType() {
        return this.updateType;
    }

    @java.lang.SuppressWarnings("all")
    
    public Boolean getRequired() {
        return this.required;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setDocumentation(final String documentation) {
        this.documentation = documentation;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setDuplicatesAllowed(final Boolean duplicatesAllowed) {
        this.duplicatesAllowed = duplicatesAllowed;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setUpdateType(final String updateType) {
        this.updateType = updateType;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setRequired(final Boolean required) {
        this.required = required;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    
    public java.lang.String toString() {
        return "PropertyType(documentation=" + this.getDocumentation() + ", duplicatesAllowed=" + this.getDuplicatesAllowed() + ", updateType=" + this.getUpdateType() + ", required=" + this.getRequired() + ")";
    }

    @java.lang.SuppressWarnings("all")
    
    public PropertyType() {
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof PropertyType)) return false;
        final PropertyType other = (PropertyType) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (!super.equals(o)) return false;
        final java.lang.Object this$duplicatesAllowed = this.getDuplicatesAllowed();
        final java.lang.Object other$duplicatesAllowed = other.getDuplicatesAllowed();
        if (this$duplicatesAllowed == null ? other$duplicatesAllowed != null : !this$duplicatesAllowed.equals(other$duplicatesAllowed)) return false;
        final java.lang.Object this$required = this.getRequired();
        final java.lang.Object other$required = other.getRequired();
        if (this$required == null ? other$required != null : !this$required.equals(other$required)) return false;
        final java.lang.Object this$documentation = this.getDocumentation();
        final java.lang.Object other$documentation = other.getDocumentation();
        if (this$documentation == null ? other$documentation != null : !this$documentation.equals(other$documentation)) return false;
        final java.lang.Object this$updateType = this.getUpdateType();
        final java.lang.Object other$updateType = other.getUpdateType();
        if (this$updateType == null ? other$updateType != null : !this$updateType.equals(other$updateType)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof PropertyType;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    
    public int hashCode() {
        final int PRIME = 59;
        int result = super.hashCode();
        final java.lang.Object $duplicatesAllowed = this.getDuplicatesAllowed();
        result = result * PRIME + ($duplicatesAllowed == null ? 43 : $duplicatesAllowed.hashCode());
        final java.lang.Object $required = this.getRequired();
        result = result * PRIME + ($required == null ? 43 : $required.hashCode());
        final java.lang.Object $documentation = this.getDocumentation();
        result = result * PRIME + ($documentation == null ? 43 : $documentation.hashCode());
        final java.lang.Object $updateType = this.getUpdateType();
        result = result * PRIME + ($updateType == null ? 43 : $updateType.hashCode());
        return result;
    }
}
