// Generated by delombok at Tue May 19 16:38:52 EDT 2026
package aws.cfn.codegen;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.HashMap;
import java.util.Map;

/**
 * Defines a resource type from CFN specification file
 */
public class ResourceType {
    private Map<String, AttributeType> attributes = new HashMap<>();
    private String documentation;
    private Map<String, PropertyType> properties = new HashMap<>();

    @java.lang.SuppressWarnings("all")
    
    public Map<String, AttributeType> getAttributes() {
        return this.attributes;
    }

    @java.lang.SuppressWarnings("all")
    
    public String getDocumentation() {
        return this.documentation;
    }

    @java.lang.SuppressWarnings("all")
    
    public Map<String, PropertyType> getProperties() {
        return this.properties;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setAttributes(final Map<String, AttributeType> attributes) {
        this.attributes = attributes;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setDocumentation(final String documentation) {
        this.documentation = documentation;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setProperties(final Map<String, PropertyType> properties) {
        this.properties = properties;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    
    public java.lang.String toString() {
        return "ResourceType(attributes=" + this.getAttributes() + ", documentation=" + this.getDocumentation() + ", properties=" + this.getProperties() + ")";
    }

    @java.lang.SuppressWarnings("all")
    
    public ResourceType() {
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof ResourceType)) return false;
        final ResourceType other = (ResourceType) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$attributes = this.getAttributes();
        final java.lang.Object other$attributes = other.getAttributes();
        if (this$attributes == null ? other$attributes != null : !this$attributes.equals(other$attributes)) return false;
        final java.lang.Object this$documentation = this.getDocumentation();
        final java.lang.Object other$documentation = other.getDocumentation();
        if (this$documentation == null ? other$documentation != null : !this$documentation.equals(other$documentation)) return false;
        final java.lang.Object this$properties = this.getProperties();
        final java.lang.Object other$properties = other.getProperties();
        if (this$properties == null ? other$properties != null : !this$properties.equals(other$properties)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof ResourceType;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $attributes = this.getAttributes();
        result = result * PRIME + ($attributes == null ? 43 : $attributes.hashCode());
        final java.lang.Object $documentation = this.getDocumentation();
        result = result * PRIME + ($documentation == null ? 43 : $documentation.hashCode());
        final java.lang.Object $properties = this.getProperties();
        result = result * PRIME + ($properties == null ? 43 : $properties.hashCode());
        return result;
    }
}
