// Generated by delombok at Tue May 19 16:38:52 EDT 2026
package aws.cfn.codegen;

import java.util.HashMap;
import java.util.Map;

public class SingleCfnSpecification {
    private String resourceSpecificationVersion;
    private Map<String, ResourceType> propertyTypes = new HashMap<>(256);
    private Map<String, ResourceType> resourceType;

    public void validate() throws CfnSpecificationException {
        resourceType.values().iterator().next().getProperties().forEach((name, type) -> {
            type.getComplexType().ifPresent(propName -> {
                if (!propertyTypes.containsKey(propName)) {
                    throw new CfnSpecificationException("Property name " + name + " referenced but not defined " + " Names = " + propertyTypes.keySet());
                }
            });
        });
    }

    @java.lang.SuppressWarnings("all")
    
    public SingleCfnSpecification() {
    }

    @java.lang.SuppressWarnings("all")
    
    public String getResourceSpecificationVersion() {
        return this.resourceSpecificationVersion;
    }

    @java.lang.SuppressWarnings("all")
    
    public Map<String, ResourceType> getPropertyTypes() {
        return this.propertyTypes;
    }

    @java.lang.SuppressWarnings("all")
    
    public Map<String, ResourceType> getResourceType() {
        return this.resourceType;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setResourceSpecificationVersion(final String resourceSpecificationVersion) {
        this.resourceSpecificationVersion = resourceSpecificationVersion;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setPropertyTypes(final Map<String, ResourceType> propertyTypes) {
        this.propertyTypes = propertyTypes;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setResourceType(final Map<String, ResourceType> resourceType) {
        this.resourceType = resourceType;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof SingleCfnSpecification)) return false;
        final SingleCfnSpecification other = (SingleCfnSpecification) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$resourceSpecificationVersion = this.getResourceSpecificationVersion();
        final java.lang.Object other$resourceSpecificationVersion = other.getResourceSpecificationVersion();
        if (this$resourceSpecificationVersion == null ? other$resourceSpecificationVersion != null : !this$resourceSpecificationVersion.equals(other$resourceSpecificationVersion)) return false;
        final java.lang.Object this$propertyTypes = this.getPropertyTypes();
        final java.lang.Object other$propertyTypes = other.getPropertyTypes();
        if (this$propertyTypes == null ? other$propertyTypes != null : !this$propertyTypes.equals(other$propertyTypes)) return false;
        final java.lang.Object this$resourceType = this.getResourceType();
        final java.lang.Object other$resourceType = other.getResourceType();
        if (this$resourceType == null ? other$resourceType != null : !this$resourceType.equals(other$resourceType)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof SingleCfnSpecification;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $resourceSpecificationVersion = this.getResourceSpecificationVersion();
        result = result * PRIME + ($resourceSpecificationVersion == null ? 43 : $resourceSpecificationVersion.hashCode());
        final java.lang.Object $propertyTypes = this.getPropertyTypes();
        result = result * PRIME + ($propertyTypes == null ? 43 : $propertyTypes.hashCode());
        final java.lang.Object $resourceType = this.getResourceType();
        result = result * PRIME + ($resourceType == null ? 43 : $resourceType.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    
    public java.lang.String toString() {
        return "SingleCfnSpecification(resourceSpecificationVersion=" + this.getResourceSpecificationVersion() + ", propertyTypes=" + this.getPropertyTypes() + ", resourceType=" + this.getResourceType() + ")";
    }
}
