# Generated by rules_uv//pip:extensions.bzl for the {NAME} package
# (version {VERSION}). Do not edit by hand — re-run `bazel build`
# after editing the lockfile to regenerate.

load("@rules_python//python:defs.bzl", "py_library")

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "whl",
    srcs = glob(["**/*.whl", "**/*.tar.gz"], allow_empty = True),
)

# `:pkg` is the unconditional dep set — every consumer of this
# package picks this up. Per-extra targets (`:<extra>`) layer on
# extra dependencies and re-export `:pkg`. Markers are evaluated at
# extension time, so the `{DEPS}` and per-extra dep lists here are
# already filtered against the host + python_version.
py_library(
    name = "pkg",
    srcs = glob(
        ["**/*.py"],
        allow_empty = True,
    ),
    data = glob(
        ["**/*"],
        exclude = [
            "**/*.py",
            "**/__pycache__/**",
            "**/*.dist-info/RECORD",
            "BUILD.bazel",
            "WORKSPACE",
        ],
        allow_empty = True,
    ),
    imports = ["."],
    deps = [{DEPS}],
)
{EXTRA_TARGETS}
