"""repository_rule that downloads + installs a Python sdist via uv.

`uv pip install --target=. --no-deps <sdist>` lets uv handle the
build (PEP 517 backend invocation, native compile if needed, wheel
unpack) and lands the result as an importable tree at the repo
root. From Bazel's perspective the repo is then just a `py_library`
globbing `**/*.py`.

The rule chooses a Python interpreter based on the `python_strategy`
attr:

  * `"host"`     — Resolve via `repository_ctx.which("python3")`.
                   Fast; trusts the user's host Python is ≥ the
                   `python_version` they configured.

  * `"uv"`       — Run `<uv> python install <version>` into a
                   per-repo scratch dir and use the resulting
                   interpreter. Hermetic; one-time download per
                   fresh Bazel cache (uv handles caching).

The `--python` flag is only added when an explicit interpreter is
known; otherwise we let uv pick (it has its own discovery order:
`VIRTUAL_ENV`, `UV_PYTHON`, `python3` on PATH, then its own managed
versions).
"""

# BUILD content emitted for the resulting install tree. Mirrors
# pip_package.BUILD.tpl's shape so wheel + sdist consumers share the
# same py_library import surface.
_SDIST_BUILD_TPL = """\
# Generated by rules_uv//pip:sdist_install.bzl for {NAME} ({VERSION}).
# `uv pip install --target=.` materialized this tree from the sdist.

load("@rules_python//python:defs.bzl", "py_library")

package(default_visibility = ["//visibility:public"])

py_library(
    name = "pkg",
    srcs = glob(
        ["**/*.py"],
        allow_empty = True,
    ),
    data = glob(
        ["**/*"],
        exclude = [
            "**/*.py",
            "**/__pycache__/**",
            "**/*.dist-info/RECORD",
            "BUILD.bazel",
            "WORKSPACE",
        ],
        allow_empty = True,
    ),
    imports = ["."],
    deps = [{DEPS}],
)
"""

def _resolve_python(rctx):
    """Return a path to a Python interpreter, per the configured strategy."""
    if rctx.attr.python_strategy == "host":
        python = rctx.which("python3") or rctx.which("python")
        if not python:
            fail(
                "rules_uv/pip: python_strategy = \"host\" but no python3 " +
                "on PATH for {}. Either install python3 or switch to " +
                "python_strategy = \"uv\".".format(rctx.attr.pkg_name),
            )
        return str(python)

    # python_strategy = "uv": ask uv to manage an interpreter.
    uv = str(rctx.path(rctx.attr.uv))
    install_dir = rctx.path("python")
    args = [
        uv,
        "--no-config",
        "python",
        "install",
        rctx.attr.python_version,
        "--install-dir",
        str(install_dir),
    ]
    result = rctx.execute(args)
    if result.return_code != 0:
        fail(
            "rules_uv/pip: `uv python install {ver}` failed for {pkg}:\n{out}\n{err}".format(
                ver = rctx.attr.python_version,
                pkg = rctx.attr.pkg_name,
                out = result.stdout,
                err = result.stderr,
            ),
        )
    # uv's install dir gets a sub-tree like
    # `cpython-<ver>-<triple>/bin/python3`. Find the first python3
    # binary by walking the install dir. `rctx.path().readdir()` is
    # bzlmod-only but stable.
    for child in install_dir.readdir():
        candidate = child.get_child("bin").get_child("python3")
        if candidate.exists:
            return str(candidate)
    fail(
        "rules_uv/pip: uv python install for {} produced no bin/python3 in {}".format(
            rctx.attr.pkg_name,
            install_dir,
        ),
    )

_NATIVE_EXT_SUFFIXES = (".so", ".pyd", ".dylib", ".dll")

def _find_native_extensions(rctx):
    """Walk the repo root looking for compiled extension artifacts.

    Used post-install to detect whether a host-installed sdist is
    truly pure-Python (safe to share across platforms) or has built
    native code (host-specific; unsafe in multi-platform mode).
    Skips dist-info metadata directories and __pycache__ trees.
    """
    # We use `find` because repository_ctx has no native walker and
    # globbing isn't recursive. Quiet failures are fine — if `find`
    # isn't available we return [], which lets the install proceed
    # (the caller will only enforce on platforms where we expect
    # find to exist, i.e. Bazel host platforms = unix-likes).
    result = rctx.execute([
        "find",
        ".",
        "-type",
        "f",
        "(",
        "-name",
        "*.so",
        "-o",
        "-name",
        "*.pyd",
        "-o",
        "-name",
        "*.dylib",
        "-o",
        "-name",
        "*.dll",
        ")",
        "-not",
        "-path",
        "*/__pycache__/*",
        "-not",
        "-path",
        "*.dist-info/*",
    ], quiet = True)
    if result.return_code != 0:
        return []
    return [line for line in result.stdout.split("\n") if line]

def _sdist_install_impl(rctx):
    # Step 1: download the sdist.
    sdist_filename = rctx.attr.url.rsplit("/", 1)[-1]
    rctx.download(
        url = rctx.attr.url,
        sha256 = rctx.attr.sha256,
        output = sdist_filename,
    )

    # Step 2: pick a Python interpreter.
    python_bin = _resolve_python(rctx)

    # Step 3: shell to uv to install into the repo root. `--no-deps`
    # is critical — each package gets installed in isolation, and
    # the dependency graph is reconstructed at Bazel-graph level via
    # the per-pkg BUILD files.
    uv_bin = str(rctx.path(rctx.attr.uv))
    # `--no-config` keeps uv from reading the developer's
    # ~/.config/uv/uv.toml, which on many hosts points at a private
    # index that's unreachable from CI / sandboxed builds. Bazel
    # should be hermetic; the user's uv config is not.
    args = [
        uv_bin,
        "--no-config",
        "pip",
        "install",
        "--target=.",
        "--no-deps",
        "--python",
        python_bin,
        sdist_filename,
    ]
    result = rctx.execute(args, quiet = False)
    if result.return_code != 0:
        fail(
            "rules_uv/pip: `uv pip install {sd}` failed for {pkg}:\n{out}\n{err}".format(
                sd = sdist_filename,
                pkg = rctx.attr.pkg_name,
                out = result.stdout,
                err = result.stderr,
            ),
        )

    # Step 3.5: optional cross-platform safety check. When the sdist
    # is being installed under a multi-platform `pip.parse`, the
    # caller sets forbid_native_extensions=True. If the host install
    # produced any compiled extension (.so / .pyd / .dylib / .dll),
    # the result isn't safe to reuse across other platforms — we'd
    # be silently linking host-arch binaries into a Linux Bazel
    # build. Fail loudly and tell the user to find a wheel.
    if rctx.attr.forbid_native_extensions:
        native = _find_native_extensions(rctx)
        if native:
            fail(
                ("rules_uv/pip: package {pkg} ({ver}) installed from sdist " +
                 "produced platform-specific native extensions on the host " +
                 "({first}, +{rest} more). Multi-platform mode requires " +
                 "pure-Python sdists; pin a lockfile entry that ships native " +
                 "wheels for every target platform, or drop sdist-only " +
                 "packages with native code from `platforms`.").format(
                    pkg = rctx.attr.pkg_name,
                    ver = rctx.attr.pkg_version,
                    first = native[0],
                    rest = len(native) - 1,
                ),
            )

    # Step 4: drop the BUILD file.
    deps_str = ", ".join(['"{}"'.format(d) for d in rctx.attr.deps])
    rctx.file(
        "BUILD.bazel",
        _SDIST_BUILD_TPL \
            .replace("{NAME}", rctx.attr.pkg_name) \
            .replace("{VERSION}", rctx.attr.pkg_version) \
            .replace("{DEPS}", deps_str),
    )

    # Step 5: clean up the downloaded sdist file so it doesn't show
    # up in glob() above. (The dist-info already lives in the unpacked
    # tree post-install.)
    rctx.delete(sdist_filename)

sdist_install_repo = repository_rule(
    implementation = _sdist_install_impl,
    attrs = {
        "url": attr.string(mandatory = True),
        "sha256": attr.string(mandatory = True),
        "pkg_name": attr.string(mandatory = True),
        "pkg_version": attr.string(default = ""),
        "deps": attr.string_list(default = []),
        "uv": attr.label(
            mandatory = True,
            executable = False,
            allow_single_file = True,
            doc = "Label of the uv binary (typically @uv//:binary).",
        ),
        "python_strategy": attr.string(
            default = "host",
            values = ["host", "uv"],
            doc = "Where to find a Python interpreter: `host` " +
                  "(`python3` on PATH) or `uv` (uv-managed install).",
        ),
        "python_version": attr.string(
            default = "3.12",
            doc = "Python version uv should install (only used when " +
                  "python_strategy = \"uv\").",
        ),
        "forbid_native_extensions": attr.bool(
            default = False,
            doc = "When True, fail the install if post-install the " +
                  "repo root contains any .so/.pyd/.dylib/.dll files. " +
                  "Used in multi-platform mode to ensure an sdist " +
                  "install is safe to reuse across platforms.",
        ),
    },
    doc = "Install a Python sdist via `uv pip install --target=.`.",
)
