"""`cloudformation_up` / `cloudformation_down` — `bazel run`-able
deploy wrappers around the aws CLI.

`cloudformation_up` takes a `cloudformation_stack` target and
turns its rendered template into a real CloudFormation stack
deploy. `cloudformation_down` is the symmetric tear-down. Both
shell out via the `aws_cli` toolchain
(`@rules_cloudformation//cloudformation/aws_cli:toolchain_type`)
so consumers can swap the binary source (default: system `aws` on
PATH; future hermetic options via rules_multitool / http_file).

The rules emit a small shell launcher that pipes through to:
  - `aws cloudformation deploy --template-file ... --stack-name ...`
  - `aws cloudformation delete-stack --stack-name ...`

Extra argv passed to `bazel run` flows through to the aws CLI, so
e.g. `bazel run //path:my_up -- --no-execute-changeset` works for
ad-hoc overrides.
"""

load("//cloudformation/aws_cli:toolchain_type.bzl", "AWS_CLI_TOOLCHAIN_TYPE")

_RUNFILES_PRELUDE = """\
# Locate the runfiles tree. Under `bazel run`, $RUNFILES_DIR is
# already set; standalone invocations get `$0.runfiles`. We avoid
# the runfiles.bash library to dodge a transitive dep + a layer of
# bzlmod canonical-name plumbing — direct path resolution is fine
# for our two files.
if [[ -z "${{RUNFILES_DIR:-}}" ]]; then
    if [[ -d "$0.runfiles" ]]; then
        RUNFILES_DIR="$0.runfiles"
    elif [[ -d "${{BASH_SOURCE[0]}}.runfiles" ]]; then
        RUNFILES_DIR="${{BASH_SOURCE[0]}}.runfiles"
    else
        echo "{rule}: cannot locate runfiles directory" >&2
        exit 1
    fi
fi"""

_UP_TEMPLATE = """#!/usr/bin/env bash
# @generated by cloudformation_up. DO NOT EDIT — re-run \\`bazel build\\` after changing the rule.
set -euo pipefail

{runfiles_prelude}

AWS_BIN="$RUNFILES_DIR/{aws_runfile}"
{template_setup}
if [[ ! -x "$AWS_BIN" ]]; then
    echo "cloudformation_up: aws CLI toolchain binary not found at $AWS_BIN" >&2
    exit 1
fi
{template_check}
echo "cloudformation_up: deploying stack '{stack_name}'{from_msg}" >&2

exec "$AWS_BIN" cloudformation deploy \\
  --stack-name {stack_name} \\
  {template_arg} \\
{region_arg}{capabilities_arg}{parameter_overrides_arg}  "$@"
"""

_DOWN_TEMPLATE = """#!/usr/bin/env bash
# @generated by cloudformation_down. DO NOT EDIT — re-run \\`bazel build\\` after changing the rule.
set -euo pipefail

{runfiles_prelude}

AWS_BIN="$RUNFILES_DIR/{aws_runfile}"
if [[ ! -x "$AWS_BIN" ]]; then
    echo "cloudformation_down: aws CLI toolchain binary not found at $AWS_BIN" >&2
    exit 1
fi

echo "cloudformation_down: deleting stack '{stack_name}'" >&2

exec "$AWS_BIN" cloudformation delete-stack \\
  --stack-name {stack_name} \\
{region_arg}  "$@"
"""

def _runfile_path(ctx, f):
    # Compose `<workspace_name>/<short_path>` — what rlocation
    # expects regardless of host/launcher quirks.
    return ctx.workspace_name + "/" + f.short_path if f.short_path[:3] != "../" else f.short_path[3:]

def _format_region(region):
    # Trailing ` \` keeps the bash command on one logical line when
    # this arg is present.
    return "  --region {} \\\n".format(region) if region else ""

def _format_capabilities(capabilities):
    if not capabilities:
        return ""
    return "  --capabilities {} \\\n".format(" ".join(capabilities))

def _format_parameter_overrides(parameter_overrides):
    if not parameter_overrides:
        return ""

    # CFN takes `Key=Value` pairs. We don't shell-quote values
    # because aws-cli's argv parser does its own splitting; users
    # who need spaces or special chars should pass them via
    # `bazel run -- --parameter-overrides ...` instead.
    pairs = ["{}={}".format(k, v) for k, v in parameter_overrides.items()]
    return "  --parameter-overrides {} \\\n".format(" ".join(pairs))

def _cloudformation_up_impl(ctx):
    aws_info = ctx.toolchains[AWS_CLI_TOOLCHAIN_TYPE].aws_cli_info
    aws_exec = aws_info.aws.executable

    if ctx.attr.use_previous_template and ctx.attr.stack:
        fail("cloudformation_up: set either `stack` or `use_previous_template`, not both.")
    if not ctx.attr.use_previous_template and not ctx.attr.stack:
        fail("cloudformation_up: one of `stack` or `use_previous_template = True` is required.")

    launcher = ctx.actions.declare_file(ctx.label.name + ".sh")
    stack_name = ctx.attr.stack_name or ctx.label.name
    region_arg = _format_region(ctx.attr.region)
    capabilities_arg = _format_capabilities(ctx.attr.capabilities)
    parameter_overrides_arg = _format_parameter_overrides(ctx.attr.parameter_overrides)

    runfiles = aws_info.default_runfiles.merge(ctx.runfiles(files = [aws_exec]))

    if ctx.attr.use_previous_template:
        # In-place parameter/image update against an already-deployed stack —
        # `cloudformation deploy --use-previous-template` reuses the live
        # template and keeps every unspecified parameter at its previous value,
        # so callers flip just what they pass via `parameter_overrides` (or
        # `bazel run … -- --parameter-overrides Key=Value`). No template runfile.
        template_setup = ""
        template_check = ""
        from_msg = " (reusing the currently-deployed template)"
        template_arg = "--use-previous-template"
    else:
        template_files = ctx.attr.stack[DefaultInfo].files.to_list()
        if len(template_files) != 1:
            fail("cloudformation_up: stack dep produced {} files (expected 1)".format(len(template_files)))
        template = template_files[0]
        template_setup = "TEMPLATE=\"$RUNFILES_DIR/{}\"\n".format(_runfile_path(ctx, template))
        template_check = (
            "if [[ ! -f \"$TEMPLATE\" ]]; then\n" +
            "    echo \"cloudformation_up: rendered template not found at $TEMPLATE\" >&2\n" +
            "    exit 1\n" +
            "fi\n"
        )
        from_msg = " from $TEMPLATE"
        template_arg = "--template-file \"$TEMPLATE\""
        runfiles = runfiles.merge(ctx.runfiles(files = [template])).merge(
            ctx.attr.stack[DefaultInfo].default_runfiles,
        )

    ctx.actions.write(
        launcher,
        _UP_TEMPLATE.format(
            runfiles_prelude = _RUNFILES_PRELUDE.format(rule = "cloudformation_up"),
            aws_runfile = _runfile_path(ctx, aws_exec),
            template_setup = template_setup,
            template_check = template_check,
            from_msg = from_msg,
            template_arg = template_arg,
            stack_name = stack_name,
            region_arg = region_arg,
            capabilities_arg = capabilities_arg,
            parameter_overrides_arg = parameter_overrides_arg,
        ),
        is_executable = True,
    )

    return [DefaultInfo(executable = launcher, runfiles = runfiles)]

cloudformation_up = rule(
    implementation = _cloudformation_up_impl,
    executable = True,
    doc = "`bazel run`-able stack-deploy. Wraps `aws cloudformation deploy --stack-name ... --template-file <generated>` (or `--use-previous-template` for an in-place parameter update of an already-deployed stack). Extra argv after `--` passes through to the aws CLI.",
    attrs = {
        "stack": attr.label(
            doc = "A `cloudformation_stack` target. Its rendered JSON template is passed to `aws cloudformation deploy`. Required unless `use_previous_template = True`.",
        ),
        "use_previous_template": attr.bool(
            default = False,
            doc = "Deploy with `--use-previous-template` instead of a rendered " +
                  "template: an in-place update of an already-deployed stack that " +
                  "reuses its live template and keeps unspecified parameters at " +
                  "their previous values. Use it to flip a single parameter (e.g. " +
                  "a container image tag) on a stack this repo doesn't own the " +
                  "template for. Mutually exclusive with `stack`; pass the new " +
                  "values via `parameter_overrides` or `bazel run … -- " +
                  "--parameter-overrides Key=Value`.",
        ),
        "stack_name": attr.string(
            doc = "AWS CloudFormation stack name. Defaults to the rule's label name.",
        ),
        "region": attr.string(
            doc = "AWS region. If unset, the aws CLI's resolution chain (env, `~/.aws/config`) decides.",
        ),
        "capabilities": attr.string_list(
            doc = "List of CFN deploy capabilities — e.g. `[\"CAPABILITY_IAM\"]`, `[\"CAPABILITY_NAMED_IAM\"]`, `[\"CAPABILITY_AUTO_EXPAND\"]`. Required when the template contains IAM resources or transforms.",
        ),
        "parameter_overrides": attr.string_dict(
            doc = "`Parameter=Value` overrides passed to `--parameter-overrides`. Useful once template-level `Parameters` lands; the override surface is here ahead of that work so consumers can wire it from environment-specific values.",
        ),
    },
    toolchains = [AWS_CLI_TOOLCHAIN_TYPE],
)

def _cloudformation_down_impl(ctx):
    aws_info = ctx.toolchains[AWS_CLI_TOOLCHAIN_TYPE].aws_cli_info
    aws_exec = aws_info.aws.executable

    launcher = ctx.actions.declare_file(ctx.label.name + ".sh")
    stack_name = ctx.attr.stack_name or ctx.label.name
    region_arg = _format_region(ctx.attr.region)
    if not region_arg.strip():
        region_arg = ""

    ctx.actions.write(
        launcher,
        _DOWN_TEMPLATE.format(
            runfiles_prelude = _RUNFILES_PRELUDE.format(rule = "cloudformation_down"),
            aws_runfile = _runfile_path(ctx, aws_exec),
            stack_name = stack_name,
            region_arg = region_arg,
        ),
        is_executable = True,
    )

    runfiles = ctx.runfiles().merge(
        aws_info.default_runfiles,
    ).merge(ctx.runfiles(files = [aws_exec]))

    return [DefaultInfo(executable = launcher, runfiles = runfiles)]

cloudformation_down = rule(
    implementation = _cloudformation_down_impl,
    executable = True,
    doc = "`bazel run`-able stack-teardown. Wraps `aws cloudformation delete-stack --stack-name ...`. Extra argv after `--` passes through to the aws CLI.",
    attrs = {
        "stack_name": attr.string(
            doc = "AWS CloudFormation stack name. Defaults to the rule's label name.",
        ),
        "region": attr.string(
            doc = "AWS region. If unset, the aws CLI's resolution chain decides.",
        ),
    },
    toolchains = [AWS_CLI_TOOLCHAIN_TYPE],
)
