"""Interactive CloudFormation deploy wrapper.

`cloudformation_up_interactive` runs a cfn_console-style executable against a
rendered `cloudformation_stack` template and optional region/capabilities.
"""

def _cloudformation_up_interactive_impl(ctx):
    template_files = ctx.attr.stack[DefaultInfo].files.to_list()
    if len(template_files) != 1:
        fail("cloudformation_up_interactive: stack {} must produce exactly one file (got {})".format(
            ctx.attr.stack.label,
            len(template_files),
        ))

    template = template_files[0]
    cfn_console = ctx.executable.cfn_console
    stack_name = ctx.attr.stack_name or ctx.label.name

    args = [
        "--template",
        "${RUNFILES_DIR}/{}".format(template.short_path),
        "--stack-name",
        stack_name,
    ]
    if ctx.attr.region:
        args += ["--region", ctx.attr.region]
    for cap in ctx.attr.capabilities:
        args += ["--capability", cap]

    launcher = ctx.actions.declare_file(ctx.label.name + ".sh")
    ctx.actions.write(
        launcher,
        """#!/usr/bin/env bash
# @generated by cloudformation_up_interactive. DO NOT EDIT.
set -euo pipefail
if [[ -z "${RUNFILES_DIR:-}" ]]; then
    if [[ -d "$0.runfiles" ]]; then
        RUNFILES_DIR="$0.runfiles"
    elif [[ -d "${BASH_SOURCE[0]}.runfiles" ]]; then
        RUNFILES_DIR="${BASH_SOURCE[0]}.runfiles"
    else
        echo "cloudformation_up_interactive: cannot locate runfiles" >&2
        exit 1
    fi
fi
BIN="$RUNFILES_DIR/_main/{bin}"
if [[ ! -x "$BIN" ]]; then
    # Fallback when invoked from an external workspace.
    BIN="$(find "$RUNFILES_DIR" -name cfn_console -type f -perm -u+x 2>/dev/null | head -n1)"
fi
exec "$BIN" {args} "$@"
""".format(
            bin = cfn_console.short_path,
            args = " ".join(["'{}'".format(a) for a in args]),
        ),
        is_executable = True,
    )

    runfiles = ctx.runfiles(files = [template, cfn_console]).merge(
        ctx.attr.cfn_console[DefaultInfo].default_runfiles,
    )
    return [DefaultInfo(executable = launcher, runfiles = runfiles)]

cloudformation_up_interactive = rule(
    implementation = _cloudformation_up_interactive_impl,
    executable = True,
    doc = "Interactive CFN deploy driver. Wraps a cfn_console executable with a rendered template + stack name.",
    attrs = {
        "stack": attr.label(
            doc = "Label that emits exactly one CloudFormation JSON template.",
            allow_files = True,
            mandatory = True,
        ),
        "stack_name": attr.string(
            doc = "CloudFormation stack name. Defaults to the rule name.",
        ),
        "region": attr.string(
            doc = "AWS region. If unset, the executable resolves it from ambient AWS configuration.",
        ),
        "capabilities": attr.string_list(
            doc = "CloudFormation capabilities (e.g. CAPABILITY_IAM).",
        ),
        "cfn_console": attr.label(
            doc = "Executable label for the interactive CloudFormation console driver.",
            executable = True,
            cfg = "target",
            mandatory = True,
        ),
    },
)
