# @generated by rules_jsonschema//tools/schema_to_starlark. DO NOT EDIT.
#
# Source schema: code-workspace.schema.json
#
# Refresh via the generating rule's `update` script;
# the diff_test will fail until you do.

load("@rules_jsonschema//runtime:helpers.bzl", "parse_json_or_none", "strip_empty")

VscodeFolderShardInfo = provider(
    doc = "A folder contributed by a target. Shard JSON matches the folder schema.",
    fields = {
        "folder_name": "string: top-level key for this folder in the rendered project.",
        "json": "File: the JSON shard.",
    },
)

def _vscode_folder_shard_impl(ctx):
    item_name = ctx.attr.folder_name or ctx.label.name
    payload = {
        "name": ctx.attr.name_override,
        "path": ctx.attr.path,
    }
    payload = strip_empty(payload)
    shard = ctx.actions.declare_file(ctx.label.name + ".folder.json")
    ctx.actions.write(shard, json.encode(payload))
    return [
        DefaultInfo(files = depset([shard])),
        VscodeFolderShardInfo(folder_name = item_name, json = shard),
    ]

vscode_folder_shard = rule(
    implementation = _vscode_folder_shard_impl,
    doc = "Schema-derived rule for one `folder` entry.",
    provides = [VscodeFolderShardInfo],
    attrs = {
        "folder_name": attr.string(
            doc = "Top-level key for this folder in the rendered project. Defaults to the rule name.",
        ),
        "name_override": attr.string(
            doc = "Display name shown in the VSCode explorer.",
        ),
        "path": attr.string(
            doc = "Workspace-relative folder path (`.` for the root).",
        ),
    },
)

