//! Bulk-lifted `pg_finfo_NAME` stubs from Postgres' PG_FUNCTION_INFO_V1
//! macro. Generated by build.rs from `manifest.json` (871 entries
//! extracted from the full Postgres AST tensor at
//! `bazel-bin/examples/postgres_smoke/postgres_full_tensor.tensor` —
//! see project_c_to_rust_translation.md, 2026-05-25 update).
//!
//! Each stub returns a pointer to a `PgFinfoRecord { api_version: 1 }`
//! and is ABI-compatible with the C-macro-generated original. The
//! whole crate is intentionally trivial: this is the proving ground
//! for "lift N functions from one template" before we tackle the
//! 983-fn `Datum fn(FunctionCallInfo)` companion cluster which has
//! real body logic.

#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(clippy::missing_safety_doc)]

/// Mirror of Postgres' `Pg_finfo_record` struct (see fmgr.h:394).
/// Layout-compat (`#[repr(C)]`) so a `*const PgFinfoRecord` returned
/// from these stubs can be dereferenced by C code expecting a
/// `const Pg_finfo_record *`.
#[repr(C)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct PgFinfoRecord {
    /// Specifies the fmgr call-convention version. v1 is the only
    /// version Postgres still supports; older v0 was removed in PG12.
    pub api_version: i32,
}

include!(concat!(env!("OUT_DIR"), "/generated.rs"));
