"""`write_source_files`: copy generated outputs back into source.

The canonical Bazel pattern for committed-codegen workflows. A typical
setup pairs a codegen rule (whose output sits under `bazel-bin/...`)
with a `write_source_files` target that copies the output to a path
under source control:

    jsonschema_starlark_codegen(
        name = "compose_rules_gen",
        schema = "...",
        kinds = [...],
    )

    write_source_files(
        name = "update_compose_rules",
        files = {
            "compose_rules.bzl": ":compose_rules_gen",
        },
    )

  * `bazel build //compose:update_compose_rules` — no-op.
  * `bazel run //compose:update_compose_rules` — copies each
    generated file to its source-tree destination, respecting
    `BUILD_WORKSPACE_DIRECTORY` so multi-repo workspaces still work.

Pair with a `diff_test` to gate freshness:

    diff_test(
        name = "compose_rules_up_to_date",
        file1 = "compose_rules.bzl",
        file2 = ":compose_rules_gen",
    )

This rule replaces ad-hoc `sh_binary + update.sh` pairs throughout
rules_jsonschema's consumers. Functionally equivalent to
`@aspect_bazel_lib//lib:write_source_files.bzl`, but in-repo so we
don't take on `aspect_bazel_lib` as a dep for a single rule.
"""

def _write_source_files_impl(ctx):
    # Build a small bash runner that materialises each `dest = src`
    # copy from runfiles back to BUILD_WORKSPACE_DIRECTORY/<dest>.
    # We do the resolution at runtime (rather than baking absolute
    # paths in at action time) because Bazel's runfiles tree layout
    # differs between in-repo and external-repo callers.
    runner = ctx.actions.declare_file(ctx.label.name + ".sh")

    package = ctx.label.package
    pairs = []
    runfile_inputs = []
    for dest, src_label in ctx.attr.files.items():
        src_files = src_label.files.to_list()
        if len(src_files) != 1:
            fail("write_source_files: source label {} must produce exactly one file; got {}".format(
                src_label.label,
                len(src_files),
            ))
        src_file = src_files[0]
        runfile_inputs.append(src_file)

        # `dest` is package-relative; combine with the rule's package
        # to get the workspace-relative path.
        full_dest = "{}/{}".format(package, dest) if package else dest
        pairs.append((src_file.short_path, full_dest))

    pair_lines = "\n".join([
        "  copy '{src}' '{dst}'".format(src = src_sp, dst = dst)
        for src_sp, dst in pairs
    ])

    ctx.actions.write(
        output = runner,
        is_executable = True,
        content = """#!/usr/bin/env bash
# Generated by write_source_files. Invoke via `bazel run`.
set -euo pipefail

if [[ -z "${{BUILD_WORKSPACE_DIRECTORY:-}}" ]]; then
  echo "error: must be invoked via 'bazel run'" >&2
  exit 1
fi

RUNFILES_DIR="${{RUNFILES_DIR:-$0.runfiles}}"
WS_NAME="{ws}"

resolve() {{
  local sp="$1"
  if [[ "$sp" == ../* ]]; then
    printf '%s' "$RUNFILES_DIR/${{sp#../}}"
  else
    printf '%s' "$RUNFILES_DIR/$WS_NAME/$sp"
  fi
}}

copy() {{
  local src_sp="$1"
  local dst_rel="$2"
  local src
  src="$(resolve "$src_sp")"
  local dst="$BUILD_WORKSPACE_DIRECTORY/$dst_rel"
  if [[ ! -f "$src" ]]; then
    echo "error: source file not found in runfiles: $src" >&2
    exit 2
  fi
  mkdir -p "$(dirname "$dst")"
  # Source-controlled files are typically read-only after bazel-cp;
  # chmod first so the write doesn't fail.
  if [[ -f "$dst" ]]; then chmod u+w "$dst"; fi
  cp "$src" "$dst"
  chmod u+w "$dst"
  echo "wrote $dst_rel"
}}

{pair_lines}
""".format(
            ws = ctx.workspace_name,
            pair_lines = pair_lines,
        ),
    )

    runfiles = ctx.runfiles(files = runfile_inputs)
    return [DefaultInfo(executable = runner, runfiles = runfiles)]

write_source_files = rule(
    implementation = _write_source_files_impl,
    executable = True,
    attrs = {
        "files": attr.string_keyed_label_dict(
            mandatory = True,
            allow_files = True,
            doc = "Map of package-relative destination path → label whose " +
                  "single output file should be copied there. Each source " +
                  "label must produce exactly one output file.",
        ),
    },
    doc = "`bazel run`-able target that copies generated files back into source control.",
)
