#!/usr/bin/env bash
# Generated by rules_huggingface — do not edit.
#
# Runs one HF Inference Endpoints control-plane verb via the typed
# `hf-endpoints` CLI. Side-effecting (`bazel run` only).
set -uo pipefail

# --- bazel bash runfiles preamble (canonical) ---
set +e
f=bazel_tools/tools/bash/runfiles/runfiles.bash
source "${RUNFILES_DIR:-/dev/null}/$f" 2>/dev/null || \
  source "$(grep -sm1 "^$f " "${RUNFILES_MANIFEST_FILE:-/dev/null}" | cut -f2- -d' ')" 2>/dev/null || \
  source "$0.runfiles/$f" 2>/dev/null || \
  source "$(grep -sm1 "^$f " "$0.runfiles_manifest" | cut -f2- -d' ')" 2>/dev/null || \
  source "$(grep -sm1 "^$f " "$0.exe.runfiles_manifest" | cut -f2- -d' ')" 2>/dev/null || \
  { echo >&2 "ERROR: cannot find $f"; exit 1; }
set -e
# --- end preamble ---

CLI="$(rlocation "%%CLI_RLOCATION%%")"
if [[ -z "${CLI:-}" || ! -x "$CLI" ]]; then
    echo "fatal: hf-endpoints binary not found in runfiles (%%CLI_RLOCATION%%)" >&2
    exit 3
fi

cd "${BUILD_WORKSPACE_DIRECTORY:-$(pwd)}"

if [[ -z "${HF_TOKEN:-}" ]]; then
    echo "warning: HF_TOKEN not set; the Endpoints API call will be unauthenticated" >&2
fi

%%CONFIG_LINE%%
exec "$CLI" %%ARGS%% "$@"
