#!/usr/bin/env bash
# Generated by rules_huggingface — do not edit.
#
# Locates the hermetic `hf` binary in this target's runfiles and runs
# a data-plane verb against the user's workspace. Side-effecting
# (`bazel run` only): talks to the HF Hub.
set -uo pipefail

# --- bazel bash runfiles preamble (canonical) ---
# https://github.com/bazelbuild/bazel/blob/master/tools/bash/runfiles/runfiles.bash
# shellcheck disable=SC1090
set +e
f=bazel_tools/tools/bash/runfiles/runfiles.bash
source "${RUNFILES_DIR:-/dev/null}/$f" 2>/dev/null || \
  source "$(grep -sm1 "^$f " "${RUNFILES_MANIFEST_FILE:-/dev/null}" | cut -f2- -d' ')" 2>/dev/null || \
  source "$0.runfiles/$f" 2>/dev/null || \
  source "$(grep -sm1 "^$f " "$0.runfiles_manifest" | cut -f2- -d' ')" 2>/dev/null || \
  source "$(grep -sm1 "^$f " "$0.exe.runfiles_manifest" | cut -f2- -d' ')" 2>/dev/null || \
  { echo >&2 "ERROR: cannot find $f"; exit 1; }
set -e
# --- end preamble ---

HF_BIN="$(rlocation "%%HF_RLOCATION%%")"
if [[ -z "${HF_BIN:-}" || ! -x "$HF_BIN" ]]; then
    echo "fatal: hermetic hf binary not found in runfiles (%%HF_RLOCATION%%)" >&2
    exit 3
fi

# Run against the user's workspace, not the runfiles tree.
cd "${BUILD_WORKSPACE_DIRECTORY:-$(pwd)}"

if [[ -z "${HF_TOKEN:-}" ]]; then
    echo "warning: HF_TOKEN not set; relying on a prior 'hf auth login'" >&2
fi

exec "$HF_BIN" %%VERB_AND_ARGS%% "$@"
