"""tex_paper — compose a paper from typed section fragments.

```starlark
tex_paper(
    name = "pcc",
    preamble = "preamble.tex",
    sections = [":intro", ":semantics", ":mechanism", ...],
    bibliography = "bibliography.tex",   # optional
)
```

Emits:

  * `<name>_wrapper.tex` — a generated main.tex that `\\input{}`s
    the preamble, each section's source by relative path, and
    the optional bibliography. Closes with `\\end{document}`.
  * `<name>` — the actual `tectonic_pdf` target compiling the
    wrapper plus all section srcs + Lean emits + extras.

The wrapper is a build artifact, not a source file. Sections
remain plain `.tex` fragments that can be edited independently.

v0.0.2 scope: clean wrapper assembly + dep threading. v0.0.3 adds
build-time validation (cite ⊆ bib, unique section labels) on top.
"""

load(":tex_section.bzl", "TexSectionInfo")
load(":tectonic_pdf.bzl", "tectonic_pdf")

def _rel_from(pkg, file_short_path):
    """Compute `file_short_path` relative to `pkg/` (a workspace-relative
    directory). Returns paths like `sections/intro.tex` or
    `../../lean/vickrey_rule.tex` so `\\input{}` resolves correctly
    when the wrapper is staged at `<pkg>/<wrapper_name>`.
    """
    pkg_prefix = (pkg + "/") if pkg else ""
    if file_short_path.startswith(pkg_prefix):
        return file_short_path[len(pkg_prefix):]
    # Climb out of `pkg` (one `..` per path segment).
    up = "../" * (len(pkg.split("/")) if pkg else 0)
    return up + file_short_path

def _tex_paper_wrapper_impl(ctx):
    pkg = ctx.label.package
    out = ctx.actions.declare_file(ctx.label.name + ".tex")

    lines = [
        "%% Generated by tex_paper — DO NOT EDIT.",
        "%% Edit the source sections (and preamble) declared in the BUILD file.",
        "",
        "\\input{{{}}}".format(_rel_from(pkg, ctx.file.preamble.short_path)),
        "",
    ]
    for sec in ctx.attr.sections:
        info = sec[TexSectionInfo]
        lines.append("\\input{{{}}}".format(_rel_from(pkg, info.src.short_path)))
    lines.append("")
    if ctx.file.bibliography:
        lines.append(
            "\\input{{{}}}".format(
                _rel_from(pkg, ctx.file.bibliography.short_path),
            ),
        )
    lines.append("\\end{document}")
    lines.append("")

    ctx.actions.write(output = out, content = "\n".join(lines))
    return [DefaultInfo(files = depset([out]))]

_tex_paper_wrapper = rule(
    implementation = _tex_paper_wrapper_impl,
    attrs = {
        "preamble": attr.label(allow_single_file = [".tex"], mandatory = True),
        "sections": attr.label_list(providers = [TexSectionInfo], mandatory = True),
        "bibliography": attr.label(allow_single_file = [".tex"]),
    },
)

def tex_paper(
        name,
        preamble,
        sections,
        bibliography = None,
        extra_srcs = None,
        visibility = None):
    """Compose a paper PDF from typed section fragments.

    Args:
      name: target name. The PDF lands at `<name>.pdf`.
      preamble: label to a `.tex` containing `\\documentclass{...}`
                through `\\begin{document}` and any front matter
                (\\maketitle, abstract). Stops *before* `\\section`.
      sections: ordered list of `tex_section` labels.
      bibliography: optional label to a `.tex` containing a
                    `\\begin{thebibliography}{...}` block. Future
                    `tex_bibliography` rule will replace this with
                    a typed target.
      extra_srcs: any other inputs (figures, .sty files, embedded
                  data) referenced by the preamble or sections that
                  aren't already wired through `tex_section.extra_srcs`
                  or `tex_section.lean_emits`.
      visibility: standard bazel visibility for the PDF target.
    """
    wrapper_target = name + "_wrapper"
    _tex_paper_wrapper(
        name = wrapper_target,
        preamble = preamble,
        sections = sections,
        bibliography = bibliography,
        visibility = ["//visibility:private"],
    )

    # All extra inputs the staged main needs to see: section sources,
    # their lean_emits, their extra_srcs, plus the bibliography and
    # paper-level extras.
    srcs = [preamble] + list(sections)
    if bibliography:
        srcs.append(bibliography)
    if extra_srcs:
        srcs.extend(extra_srcs)

    # `tex_section`'s `DefaultInfo.files` includes the section's
    # `src`, its `lean_emits`, and any `extra_srcs`. Passing a
    # section label into `tectonic_pdf.srcs` therefore stages
    # everything the section needs — no separate threading.

    tectonic_pdf(
        name = name,
        main = ":" + wrapper_target,
        srcs = srcs,
        visibility = visibility,
    )
