load("@bazel_skylib//:bzl_library.bzl", "bzl_library")

package(default_visibility = ["//visibility:public"])

bzl_library(
    name = "defs",
    srcs = ["defs.bzl"],
    deps = [
        ":diagram",
        ":library",
        ":providers",
    ],
)

bzl_library(name = "providers", srcs = ["providers.bzl"])

bzl_library(
    name = "diagram",
    srcs = ["diagram.bzl"],
    deps = [":providers"],
)

bzl_library(
    name = "library",
    srcs = ["library.bzl"],
    deps = [":providers"],
)
