//! Forward projection: turn the `aide:OutputFile` filespec graph
//! (produced by the per-IDE SPARQL CONSTRUCT queries) into actual
//! on-disk agent-config files. The inverse of the harvest parsers.
//!
//! Pipeline: authored RDF → per-IDE CONSTRUCT (a `sparql_query` bazel
//! target) → N-Triples filespec → [`parse_filespec`] → [`write_all`].
//! The serializer branches only on `aide:fileFormat`, so one code path
//! handles skills, agents, rulesets, and commands alike.

mod filespec;
mod manifest;
mod serialize;

pub use filespec::{parse_filespec, Body, FileFormat, FrontmatterEntry, OutputFile};
pub use manifest::{Drift, Manifest};
pub use serialize::{render, sha256_hex, write_all, GeneratedFile, Status};

use std::collections::BTreeSet;
use std::path::{Path, PathBuf};
use std::process::Command;

use anyhow::{Context, Result};

/// The committed content-hash snapshot of the generated files.
const MANIFEST_REL: &str = ".agents/generated.lock";

fn manifest_path(repo_root: &Path) -> PathBuf {
    repo_root.join(MANIFEST_REL)
}

/// Parse the N-Triples filespec at `filespec_path` and materialize each
/// described file under `repo_root`. With `dry_run`, nothing is written.
/// On a real run, generated files are added to `.gitignore` (they're
/// derived) and the `.agents/generated.lock` manifest is rewritten — the
/// review surface for output drift.
pub fn generate(filespec_path: &Path, repo_root: &Path, dry_run: bool) -> Result<Vec<GeneratedFile>> {
    let files = load_filespec(filespec_path)?;
    let results = write_all(&files, repo_root, dry_run)?;
    if !dry_run {
        let paths: Vec<&str> = results.iter().map(|f| f.path.as_str()).collect();
        for p in ensure_gitignored(&paths, repo_root)? {
            eprintln!("gitignore  {p}");
        }
        write_manifest(&results, repo_root)?;
    }
    Ok(results)
}

/// Render the filespec WITHOUT writing, and diff the resulting content
/// hashes against the committed `.agents/generated.lock`. The drift —
/// from a graph edit or a framework-version bump — is what a reviewer /
/// CI gate inspects. Returns the drift; the caller decides the exit code.
pub fn check(filespec_path: &Path, repo_root: &Path) -> Result<Drift> {
    let files = load_filespec(filespec_path)?;
    let rendered = write_all(&files, repo_root, /*dry_run=*/ true)?;
    let current = Manifest::from_files(&rendered);
    let prev = std::fs::read_to_string(manifest_path(repo_root))
        .map(|t| Manifest::parse_textproto(&t))
        .unwrap_or_default();
    Ok(current.diff(&prev))
}

fn load_filespec(filespec_path: &Path) -> Result<Vec<OutputFile>> {
    let nt = std::fs::read_to_string(filespec_path)
        .with_context(|| format!("reading filespec {}", filespec_path.display()))?;
    let mut files = parse_filespec(&nt)
        .with_context(|| format!("parsing filespec {}", filespec_path.display()))?;
    // Deterministic order → stable output, manifest, and diffs.
    files.sort_by(|a, b| a.target_path.cmp(&b.target_path));
    Ok(files)
}

fn write_manifest(files: &[GeneratedFile], repo_root: &Path) -> Result<()> {
    let mp = manifest_path(repo_root);
    if let Some(parent) = mp.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("creating {}", parent.display()))?;
    }
    std::fs::write(&mp, Manifest::from_files(files).to_textproto())
        .with_context(|| format!("writing {}", mp.display()))
}

/// Add the generated paths to `<repo_root>/.gitignore`, skipping ones git
/// already ignores (via `git check-ignore`) and ones already listed.
/// Best-effort: a no-op outside a git work tree or if git is unavailable.
/// Returns the lines actually appended.
fn ensure_gitignored(paths: &[&str], repo_root: &Path) -> Result<Vec<String>> {
    if !is_git_worktree(repo_root) {
        return Ok(Vec::new());
    }
    let not_ignored: BTreeSet<String> = paths
        .iter()
        .filter(|p| !is_ignored(p, repo_root))
        .map(|p| p.to_string())
        .collect();
    if not_ignored.is_empty() {
        return Ok(Vec::new());
    }
    let gi_path = repo_root.join(".gitignore");
    let existing = std::fs::read_to_string(&gi_path).unwrap_or_default();
    let present: BTreeSet<&str> = existing.lines().map(str::trim).collect();
    let to_add: Vec<String> = not_ignored
        .into_iter()
        .filter(|p| !present.contains(p.as_str()))
        .collect();
    if to_add.is_empty() {
        return Ok(Vec::new());
    }
    let mut out = existing;
    if !out.is_empty() && !out.ends_with('\n') {
        out.push('\n');
    }
    out.push_str("\n# Generated by agentic-ide (regenerate with `bazel run … -- generate`)\n");
    for p in &to_add {
        out.push_str(p);
        out.push('\n');
    }
    std::fs::write(&gi_path, out).with_context(|| format!("writing {}", gi_path.display()))?;
    Ok(to_add)
}

fn is_git_worktree(repo_root: &Path) -> bool {
    Command::new("git")
        .arg("-C")
        .arg(repo_root)
        .args(["rev-parse", "--is-inside-work-tree"])
        .output()
        .map(|o| o.status.success() && o.stdout.starts_with(b"true"))
        .unwrap_or(false)
}

/// True iff git already ignores `path` (so we don't re-add it).
fn is_ignored(path: &str, repo_root: &Path) -> bool {
    Command::new("git")
        .arg("-C")
        .arg(repo_root)
        .args(["check-ignore", "-q", path])
        .status()
        .map(|s| s.success())
        .unwrap_or(false)
}
