"""Repository rule that stages a `node_modules` tree with Bun.

`bun_install` is the Bun-native answer to aspect_rules_js's
`npm_translate_lock` + `npm_link_all_packages`: it fetches a
host-platform Bun binary, copies the consumer's `package.json` +
`bun.lock` into the repo root, runs `bun install --frozen-lockfile`,
and exposes the resulting `node_modules/` tree via a generated
`BUILD.bazel`. No pnpm-lock, no aspect_rules_js.

Hermeticity: determinism comes from the lockfile. `--frozen-lockfile`
makes `bun install` fail rather than mutate the lock, so the staged
tree is exactly what `bun.lock` pins. `package.json` + `bun.lock` are
declared rule inputs (read via `rctx.path`), so editing either
re-triggers the install. Lifecycle scripts are skipped by default
(`--ignore-scripts`) — opt specific packages back in with
`trusted_dependencies`. The Bun binary itself is sha256-pinned
per-platform via the same `known_versions.bzl` table the toolchain
extension uses; the only network I/O is the registry fetch the
lockfile pins (exactly like aspect's npm extension + http_archive).

Wired up through the `bun_deps` module extension (`bun_deps.install`
tag) in `bun/extensions.bzl`.
"""

load("//bun/private:known_versions.bzl", "DEFAULT_VERSION", "KNOWN_VERSIONS")

# Canonical platform id -> Bun-release asset platform name. Kept in sync
# with `_PLATFORM_ALIASES` in extensions.bzl — Bun's release assets are
# `bun-darwin-aarch64.zip`, `bun-linux-x64.zip`, etc. (The toolchain
# extension maps these via rules_github; here we resolve the host directly
# inside the repo rule, so we keep a self-contained copy rather than load
# rules_github's private `detect_platform`.)
_PLATFORM_ALIASES = {
    "darwin_aarch64": "darwin-aarch64",
    "darwin_x86_64": "darwin-x64",
    "linux_aarch64": "linux-aarch64",
    "linux_x86_64": "linux-x64",
}

def _detect_platform(rctx):
    """Canonical host-platform id (mirrors rules_github's detect_platform)."""
    os = rctx.os.name.lower()
    arch = rctx.os.arch.lower()
    if "linux" in os and arch in ("x86_64", "amd64"):
        return "linux_x86_64"
    if "linux" in os and arch in ("aarch64", "arm64"):
        return "linux_aarch64"
    if ("mac" in os or "darwin" in os) and arch in ("aarch64", "arm64"):
        return "darwin_aarch64"
    if ("mac" in os or "darwin" in os) and arch in ("x86_64", "amd64"):
        return "darwin_x86_64"
    fail("bun_install: unsupported host os={os} arch={arch}".format(os = os, arch = arch))

_BUILD_TEMPLATE = """\
# Generated by bun_install ({name}). Do not edit.
package(default_visibility = ["//visibility:public"])

# The full installed node_modules closure as a flat set of files. Consume
# as `data` (e.g. `bun_test(node_modules = "@{name}//:node_modules")`); the
# consuming rule stages it at the sandbox workspace root so Bun's resolver
# finds it by walking up from the entry/test files.
filegroup(
    name = "node_modules",
    srcs = glob(
        ["node_modules/**"],
        # node_modules routinely contains symlinks (.bin, workspace links);
        # keep them as-is rather than failing the glob.
        allow_empty = True,
    ),
)

# Convenience alias so `@{name}` (bare repo label) resolves to the closure.
alias(
    name = "{name}",
    actual = ":node_modules",
)

exports_files(["package.json", "bun.lock"])
"""

def _fetch_bun(rctx, version):
    """Download + extract a host-platform Bun into the repo, return its path.

    Mirrors `github_binary_repository`'s URL shape + sha-pinning so the
    fetched binary matches the toolchain extension's. Returns the
    repo-relative path to the executable (`bun/bun`).
    """
    platform = _detect_platform(rctx)
    alias = _PLATFORM_ALIASES.get(platform, platform)
    sha = KNOWN_VERSIONS.get(version, {}).get(platform, "")
    if not sha:
        # buildifier: disable=print
        print("bun_install: WARNING — downloading bun@{v} for {p} unverified".format(
            v = version,
            p = platform,
        ))

    url = "https://github.com/oven-sh/bun/releases/download/bun-v{version}/bun-{platform}.zip".format(
        version = version,
        platform = alias,
    )

    # Extract into a private subdir so it never collides with the installed
    # node_modules tree (and never lands in the `node_modules/**` glob).
    rctx.download_and_extract(
        url = url,
        sha256 = sha,
        stripPrefix = "bun-{platform}".format(platform = alias),
        output = "bun",
    )
    return "bun/bun"

def _bun_install_impl(rctx):
    version = rctx.attr.bun_version or DEFAULT_VERSION
    bun = _fetch_bun(rctx, version)

    # Copy the consumer's manifest + lock to the repo root. Reading them via
    # `rctx.path` registers them as inputs so edits re-trigger the install
    # (Bazel re-runs the repo rule when a watched input changes).
    pkg_json = rctx.path(rctx.attr.package_json)
    lock = rctx.path(rctx.attr.lock)
    rctx.file("package.json", rctx.read(pkg_json))
    rctx.file(rctx.attr.lock.name, rctx.read(lock))

    # Pin the install cache inside the repo so it can't reach outside the
    # sandbox / leak host state, and never mutate the lock under us.
    args = [
        rctx.path(bun),
        "install",
        "--frozen-lockfile",
        "--no-progress",
    ]
    if rctx.attr.ignore_scripts:
        args.append("--ignore-scripts")
    for dep in rctx.attr.trusted_dependencies:
        args.append("--trust")
        args.append(dep)
    for flag in rctx.attr.install_flags:
        args.append(flag)

    env = {
        "BUN_INSTALL_CACHE_DIR": str(rctx.path(".bun-cache")),
        "NO_COLOR": "1",
        "DO_NOT_TRACK": "1",
        "BUN_INSTALL_NO_TRACK": "1",
        # Keep Bun out of the user's real home (telemetry/global config).
        "HOME": str(rctx.path(".bun-home")),
    }

    result = rctx.execute(args, environment = env, quiet = rctx.attr.quiet, timeout = rctx.attr.timeout)
    if result.return_code != 0:
        fail(
            "bun_install ({name}): `bun install --frozen-lockfile` failed " +
            "(exit {code}).\nSTDOUT:\n{out}\nSTDERR:\n{err}".format(
                name = rctx.name,
                code = result.return_code,
                out = result.stdout,
                err = result.stderr,
            ),
        )

    rctx.file("BUILD.bazel", _BUILD_TEMPLATE.format(name = rctx.name))

bun_install = repository_rule(
    implementation = _bun_install_impl,
    attrs = {
        "package_json": attr.label(
            mandatory = True,
            allow_single_file = True,
            doc = "The consumer's `package.json`. Copied to the repo root " +
                  "and read as a rule input (edits re-trigger install).",
        ),
        "lock": attr.label(
            mandatory = True,
            allow_single_file = True,
            doc = "The consumer's `bun.lock` (or `bun.lockb`). Copied to the " +
                  "repo root; `--frozen-lockfile` pins the install to it.",
        ),
        "bun_version": attr.string(
            default = "",
            doc = "Bun version to fetch for the install. Empty = the " +
                  "`DEFAULT_VERSION` in known_versions.bzl (same default the " +
                  "toolchain extension uses).",
        ),
        "ignore_scripts": attr.bool(
            default = True,
            doc = "Pass `--ignore-scripts` so dependency lifecycle scripts " +
                  "(postinstall, …) do NOT run during the hermetic install. " +
                  "Default True. Opt specific packages back in via " +
                  "`trusted_dependencies`.",
        ),
        "trusted_dependencies": attr.string_list(
            default = [],
            doc = "Package names to `--trust` (run their lifecycle scripts) " +
                  "even when `ignore_scripts` is True. Use for deps that need " +
                  "a postinstall to function (native builds, etc.).",
        ),
        "install_flags": attr.string_list(
            default = [],
            doc = "Extra raw flags appended to the `bun install` invocation " +
                  "(escape hatch; e.g. `--production`).",
        ),
        "quiet": attr.bool(
            default = True,
            doc = "Suppress the install command's live output. Set False to " +
                  "stream it (debugging).",
        ),
        "timeout": attr.int(
            default = 600,
            doc = "Seconds before the `bun install` execution is killed.",
        ),
    },
    doc = "Stage a `node_modules` tree with `bun install --frozen-lockfile`, " +
          "exposed as `@<name>//:node_modules`. The Bun-native replacement " +
          "for aspect_rules_js's npm_translate_lock + npm_link_all_packages.",
)
