"""User-facing Bazel rules for rules_chrome.

Exports two `bazel run`-friendly launchers:

- `chrome_run`: launches Chrome for Testing with an isolated user-data-dir
  and the standard testing flags pre-applied. Reusable across smoke
  tests, screenshot tools, scripted browser sessions.
- `chromedriver_run`: launches chromedriver on a configurable port; used
  as the WebDriver backend for selenium / playwright / pytest-selenium.

Both rules resolve their binaries through
`@rules_chrome//chrome:toolchain_type`, so consumers can swap in a
locally-built or alternate-channel chrome via
`register_toolchains(...)` without editing target attributes.

For the bare binaries (without launcher ergonomics) consumers can
depend directly on `@chrome//:chrome` and `@chromedriver//:chromedriver`.
"""

# Flags every CI/automation run almost always wants. Tests can extend
# via `extra_args`; nothing here is force-applied — `chrome_run` always
# appends user-supplied args last so they can override.
_DEFAULT_TESTING_ARGS = (
    "--no-first-run",
    "--no-default-browser-check",
    "--disable-background-networking",
    "--disable-component-update",
    "--disable-default-apps",
    "--disable-features=Translate",
    "--disable-sync",
    "--metrics-recording-only",
    "--no-pings",
    "--password-store=basic",
    "--use-mock-keychain",
)

def _shell_quote(s):
    """Single-quote a string for safe inclusion in /bin/sh -c contexts."""
    return "'" + s.replace("'", "'\\''") + "'"

def _runner_script(*, ctx, binary_short_path, binary_runfiles, default_args, extra_setup):
    """Emit a runfiles-aware shell launcher for a binary inside @chrome / @chromedriver.

    `extra_setup` is verbatim bash inserted after the binary is located,
    before exec. Both rules use it to seed/clean a user-data-dir or to
    choose a free port.
    """
    runner = ctx.actions.declare_file(ctx.label.name + ".sh")

    default_args_quoted = " ".join([_shell_quote(a) for a in default_args])
    extra_args_quoted = " ".join([_shell_quote(a) for a in ctx.attr.extra_args])

    ctx.actions.write(
        output = runner,
        is_executable = True,
        content = """\
#!/usr/bin/env bash
# Generated by rules_chrome.
set -euo pipefail

if [[ -z "${{RUNFILES_DIR:-}}" ]]; then
  if [[ -d "$0.runfiles" ]]; then
    RUNFILES_DIR="$0.runfiles"
  fi
fi

WS_NAME={ws_name}
binary_sp={binary_sp}
# External-repo runfiles paths are short_path-prefixed with "../".
# Resolve them under RUNFILES_DIR without the workspace folder; keep
# main-repo paths nested under WS_NAME.
if [[ "$binary_sp" == ../* ]]; then
  BIN="${{RUNFILES_DIR}}/${{binary_sp#../}}"
else
  BIN="${{RUNFILES_DIR}}/${{WS_NAME}}/${{binary_sp}}"
fi
if [[ ! -x "$BIN" ]]; then
  echo "rules_chrome: binary not executable at $BIN" >&2
  exit 2
fi

{extra_setup}

exec "$BIN" {default_args} {extra_args} "$@"
""".format(
            ws_name = _shell_quote(ctx.workspace_name),
            binary_sp = _shell_quote(binary_short_path),
            default_args = default_args_quoted,
            extra_args = extra_args_quoted,
            extra_setup = extra_setup,
        ),
    )

    runfiles = ctx.runfiles(files = [runner]).merge(binary_runfiles)
    return [DefaultInfo(executable = runner, runfiles = runfiles)]

def _chrome_run_impl(ctx):
    tc = ctx.toolchains["@rules_chrome//chrome:toolchain_type"].chromeinfo
    chrome_target = tc.chrome
    chrome_executable = chrome_target[DefaultInfo].files_to_run.executable
    chrome_runfiles = chrome_target[DefaultInfo].default_runfiles

    # --user-data-dir strategy
    # - "ephemeral" (default): mktemp under $TMPDIR per invocation; cleaned
    #   on exit. Safe for tests and parallel runs.
    # - "workspace": rooted at $BUILD_WORKSPACE_DIRECTORY/<path>; persists
    #   across runs. Useful for interactive `bazel run` sessions where
    #   you want logged-in cookies / extensions to survive.
    # - "system": don't touch --user-data-dir; chrome uses its real
    #   per-user profile. Almost never what you want for automation.
    mode = ctx.attr.user_data_dir_mode
    if mode not in ("ephemeral", "workspace", "system"):
        fail("rules_chrome: user_data_dir_mode must be one of " +
             "'ephemeral'/'workspace'/'system' (got %r)" % mode)

    extra_setup_lines = []
    default_args = list(_DEFAULT_TESTING_ARGS)
    if ctx.attr.headless:
        default_args.append("--headless=new")

    if mode == "ephemeral":
        extra_setup_lines.append(
            'USER_DATA_DIR="$(mktemp -d "${TMPDIR:-/tmp}/chrome_run.XXXXXX")"',
        )
        extra_setup_lines.append('trap \'rm -rf "$USER_DATA_DIR"\' EXIT')
        default_args.append("--user-data-dir=$USER_DATA_DIR")
    elif mode == "workspace":
        rel = ctx.attr.user_data_dir or ".cache/rules_chrome/" + ctx.label.name
        extra_setup_lines.append(
            'if [[ -z "${BUILD_WORKSPACE_DIRECTORY:-}" ]]; then',
        )
        extra_setup_lines.append('  echo "rules_chrome: user_data_dir_mode=\\"workspace\\" requires bazel run" >&2')
        extra_setup_lines.append("  exit 3")
        extra_setup_lines.append("fi")
        extra_setup_lines.append('USER_DATA_DIR="$BUILD_WORKSPACE_DIRECTORY/' + rel + '"')
        extra_setup_lines.append('mkdir -p "$USER_DATA_DIR"')
        default_args.append("--user-data-dir=$USER_DATA_DIR")

    # mode == "system" → no --user-data-dir injected

    extra_setup = "\n".join(extra_setup_lines)

    return _runner_script(
        ctx = ctx,
        binary_short_path = chrome_executable.short_path,
        binary_runfiles = chrome_runfiles,
        default_args = default_args,
        extra_setup = extra_setup,
    )

chrome_run = rule(
    implementation = _chrome_run_impl,
    executable = True,
    attrs = {
        "headless": attr.bool(
            default = False,
            doc = "Append `--headless=new` to the command line.",
        ),
        "user_data_dir_mode": attr.string(
            default = "ephemeral",
            values = ["ephemeral", "workspace", "system"],
            doc = "How to seed `--user-data-dir`:\n" +
                  "* `ephemeral` (default): a fresh `$TMPDIR/chrome_run.XXXXXX` per invocation, " +
                  "cleaned on exit. Safe for tests and parallel runs.\n" +
                  "* `workspace`: a persistent directory under " +
                  "`$BUILD_WORKSPACE_DIRECTORY/<user_data_dir>` (cookies, extensions, signed-in " +
                  "state survive across `bazel run`). Requires `bazel run`.\n" +
                  "* `system`: omit `--user-data-dir` entirely. Chrome uses the real per-user " +
                  "profile — almost never what you want for automation.",
        ),
        "user_data_dir": attr.string(
            default = "",
            doc = "Workspace-relative profile path used when " +
                  "`user_data_dir_mode = \"workspace\"`. Defaults to " +
                  "`.cache/rules_chrome/<target name>`.",
        ),
        "extra_args": attr.string_list(
            default = [],
            doc = "Extra command-line flags appended after the rules_chrome defaults but " +
                  "before any args passed on the CLI. Use this to bake in test-specific " +
                  "flags (e.g. `--remote-debugging-port=9222`).",
        ),
    },
    toolchains = ["@rules_chrome//chrome:toolchain_type"],
    doc = "Run Chrome for Testing via `bazel run`, with a managed user-data-dir and " +
          "the standard automation flags pre-applied. Additional CLI arguments are " +
          "forwarded to chrome verbatim.",
)

def _chromedriver_run_impl(ctx):
    tc = ctx.toolchains["@rules_chrome//chrome:toolchain_type"].chromeinfo
    if tc.chromedriver == None:
        fail("rules_chrome: the registered toolchain has no chromedriver. " +
             "Either register the default `@chrome//:chrome_toolchain_def` or wire a " +
             "chromedriver attribute on your custom chrome_toolchain.")
    driver_target = tc.chromedriver
    driver_executable = driver_target[DefaultInfo].files_to_run.executable
    driver_runfiles = driver_target[DefaultInfo].default_runfiles

    default_args = []
    if ctx.attr.port:
        default_args.append("--port=" + str(ctx.attr.port))

    return _runner_script(
        ctx = ctx,
        binary_short_path = driver_executable.short_path,
        binary_runfiles = driver_runfiles,
        default_args = default_args,
        extra_setup = "",
    )

chromedriver_run = rule(
    implementation = _chromedriver_run_impl,
    executable = True,
    attrs = {
        "port": attr.int(
            default = 0,
            doc = "Listen port. `0` (default) lets chromedriver pick — read the chosen " +
                  "port from its first line of stdout.",
        ),
        "extra_args": attr.string_list(
            default = [],
            doc = "Extra command-line flags appended after the configured `--port` and " +
                  "before any args passed on the CLI.",
        ),
    },
    toolchains = ["@rules_chrome//chrome:toolchain_type"],
    doc = "Run chromedriver via `bazel run`. The matching driver version is resolved " +
          "through the registered chrome toolchain; extra CLI arguments are forwarded " +
          "to chromedriver verbatim.",
)
