"""SHA-256 pins for prebuilt Chrome for Testing binaries.

Generated by `tools/refresh_versions.py`. Bumping a version means
running:

    tools/refresh_versions.py --version <X.Y.Z.W>

…which appends a new entry here. Unpinned versions still build
(warning emitted) but lose hermeticity. Always prefer pinning.
"""

# Map: binary -> version -> platform -> sha256.
KNOWN_VERSIONS = {
    "chrome": {
        "148.0.7778.167": {
            "linux64": "7096879de995091dff2eb3f4b5e7d36ca3395c07fb552a9a391887cb5def574a",
            "mac-arm64": "bbfd1f2e5094f45c2c76eb19da79fa068afcfa787bfc0a8e5a02ce45e71901cf",
            "mac-x64": "b275d62a557cd3d38e08817edaaedb5e15d2bee3c1e4c266826b725752fb72d6",
            "win32": "d08c371d39f4d1342d1e31dfd9da77295b8ec9989a65e39d65739a821020a1d7",
            "win64": "d7254ddc0360af8a65485c927a89864b63098a9e6201cd31a91dd60303827fcb",
        },
    },
    "chromedriver": {
        "148.0.7778.167": {
            "linux64": "f730a232329f133f3f6f992a9fb8b25745328b43b7b6244bd8168d95bc727c7e",
            "mac-arm64": "a41984c9442ab07ca6d0af4eb10c0e36834265021388f58069b6c331ca03a924",
            "mac-x64": "78ab4a8617696e9f2a8d969d5239d9d05ba9e1cacd04d2f3529fe8895cded36d",
            "win32": "c172922e064888108076b56c48a47fb9904f7adfdb7e74c2449306bdbafd2934",
            "win64": "fae4ccf8cd3175f8b894d588c9c129442b3e40e18612bc22a8eae292d7a69325",
        },
    },
}

# Upstream URL template. Common across both chrome + chromedriver; the
# tool name is interpolated as part of the path *and* the filename.
URL_TEMPLATE = (
    "https://storage.googleapis.com/chrome-for-testing-public/" +
    "{version}/{platform}/{binary}-{platform}.zip"
)

DEFAULT_VERSION = "148.0.7778.167"
