#!/usr/bin/env bash
# Generated by rules_huggingface — do not edit.
#
# hf_upload runner: ensure the repo exists (creating it with the
# requested privacy if missing), then sync a local directory into it.
# Idempotent — HF upload overwrites changed files.
#
# A trailing `bazel run :<name>.push -- <other_dir>` overrides the
# baked-in local dir (useful when the dir is produced by a separate
# `bazel run` export step).
set -uo pipefail

# --- bazel bash runfiles preamble (canonical) ---
set +e
f=bazel_tools/tools/bash/runfiles/runfiles.bash
source "${RUNFILES_DIR:-/dev/null}/$f" 2>/dev/null || \
  source "$(grep -sm1 "^$f " "${RUNFILES_MANIFEST_FILE:-/dev/null}" | cut -f2- -d' ')" 2>/dev/null || \
  source "$0.runfiles/$f" 2>/dev/null || \
  source "$(grep -sm1 "^$f " "$0.runfiles_manifest" | cut -f2- -d' ')" 2>/dev/null || \
  source "$(grep -sm1 "^$f " "$0.exe.runfiles_manifest" | cut -f2- -d' ')" 2>/dev/null || \
  { echo >&2 "ERROR: cannot find $f"; exit 1; }
set -e
# --- end preamble ---

HF_BIN="$(rlocation "%%HF_RLOCATION%%")"
if [[ -z "${HF_BIN:-}" || ! -x "$HF_BIN" ]]; then
    echo "fatal: hermetic hf binary not found in runfiles (%%HF_RLOCATION%%)" >&2
    exit 3
fi

REPO="%%REPO%%"
REPO_TYPE="%%REPO_TYPE%%"
PRIVATE="%%PRIVATE%%"
LOCAL_DIR="%%LOCAL_DIR%%"

# Run against the user's workspace, not the runfiles tree.
cd "${BUILD_WORKSPACE_DIRECTORY:-$(pwd)}"

# Optional runtime override of the local dir.
if [[ $# -ge 1 && -n "${1:-}" ]]; then
    LOCAL_DIR="$1"
    shift
fi

if [[ -z "${HF_TOKEN:-}" ]]; then
    echo "warning: HF_TOKEN not set; relying on a prior 'hf auth login'" >&2
fi

if [[ ! -d "$LOCAL_DIR" ]]; then
    echo "fatal: local dir '$LOCAL_DIR' not found (run the export step first?)" >&2
    exit 3
fi

echo "===> ensuring repo $REPO ($REPO_TYPE) exists" >&2
CREATE_ARGS=(repos create "$REPO" --repo-type "$REPO_TYPE" --exist-ok)
if [[ "$PRIVATE" == "1" ]]; then
    CREATE_ARGS+=(--private)
fi
"$HF_BIN" "${CREATE_ARGS[@]}" || {
    echo "warning: repo create returned non-zero (may already exist); continuing" >&2
}

echo "===> uploading $LOCAL_DIR -> $REPO" >&2
exec "$HF_BIN" upload --repo-type "$REPO_TYPE" "$REPO" "$LOCAL_DIR" . "$@"
