"""Module extension for rules_chrome.

Auto-fetches the prebuilt Chrome for Testing + chromedriver binaries
for the host platform. Versions are pinned by sha256 in
`private/known_versions.bzl`. Consumers can override the version via
the `toolchain` tag class.

Default usage (pulls the default-pinned Chrome + chromedriver):

    chrome = use_extension("@rules_chrome//chrome:extensions.bzl", "chrome")
    use_repo(chrome, "chrome", "chromedriver")
    register_toolchains("@chrome//:chrome_toolchain_def")

Pin a specific Chrome for Testing version:

    chrome = use_extension("@rules_chrome//chrome:extensions.bzl", "chrome")
    chrome.toolchain(version = "148.0.7778.167")
    use_repo(chrome, "chrome", "chromedriver")
"""

load(
    "//chrome/private:known_versions.bzl",
    "DEFAULT_VERSION",
    "KNOWN_VERSIONS",
    "URL_TEMPLATE",
)

def _resolve_platform(rctx):
    os = rctx.os.name.lower()
    arch = rctx.os.arch.lower()
    if "linux" in os and arch in ("x86_64", "amd64"):
        return "linux64"
    if ("mac" in os or "darwin" in os) and arch in ("aarch64", "arm64"):
        return "mac-arm64"
    if ("mac" in os or "darwin" in os) and arch in ("x86_64", "amd64"):
        return "mac-x64"
    if "windows" in os and arch in ("x86_64", "amd64"):
        return "win64"
    if "windows" in os and arch in ("x86", "i386", "i686"):
        return "win32"
    fail("rules_chrome: unsupported platform os=%s arch=%s" % (os, arch))

# The Chrome for Testing zips extract to a folder named like
# `chrome-mac-arm64/` or `chromedriver-linux64/`. We pass the folder
# name to `rctx.download_and_extract` as stripPrefix so the binary
# lands at the repo root with a predictable relative path.
_BINARY_LAYOUTS = {
    "chrome": {
        "linux64": ("chrome-linux64", "chrome"),
        "mac-arm64": ("chrome-mac-arm64", "Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing"),
        "mac-x64": ("chrome-mac-x64", "Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing"),
        "win32": ("chrome-win32", "chrome.exe"),
        "win64": ("chrome-win64", "chrome.exe"),
    },
    "chromedriver": {
        "linux64": ("chromedriver-linux64", "chromedriver"),
        "mac-arm64": ("chromedriver-mac-arm64", "chromedriver"),
        "mac-x64": ("chromedriver-mac-x64", "chromedriver"),
        "win32": ("chromedriver-win32", "chromedriver.exe"),
        "win64": ("chromedriver-win64", "chromedriver.exe"),
    },
}

def _binary_repo_impl(rctx, *, binary, version, platform, sha256, with_toolchain):
    url = URL_TEMPLATE.format(version = version, platform = platform, binary = binary)
    if not sha256:
        # buildifier: disable=print
        print(("rules_chrome: WARNING — no pinned sha256 for {b}@{v} on {p}; " +
               "downloading unverified. Run `tools/refresh_versions.py " +
               "--version {v}` to lock it.").format(b = binary, v = version, p = platform))

    folder, exe_relpath = _BINARY_LAYOUTS[binary][platform]

    # Extract the zip with the upstream folder layout intact — we need
    # the whole bundle on macOS (the .app wrapper has resource files
    # that chrome refuses to launch without). Linux/Windows also benefit
    # from keeping nearby shared libs alongside the executable.
    rctx.download_and_extract(
        url = url,
        sha256 = sha256 or "",
        stripPrefix = "",
    )

    # The chrome binary on macOS uses `@executable_path/../Frameworks/`
    # in its load commands. dyld resolves @executable_path from argv[0],
    # so invoking through a flat symlink at the repo root breaks the
    # Frameworks lookup. Instead, write a launcher that exec's the real
    # bundle binary by its absolute path — argv[0] then points into
    # `Contents/MacOS/`, where `../Frameworks` resolves correctly.
    is_windows = platform.startswith("win")
    launcher_name = binary + ("_launcher.bat" if is_windows else "_launcher.sh")
    if is_windows:
        rctx.file(launcher_name, """\
@echo off
set "_dir=%~dp0"
"%_dir%{folder}\\{exe}" %*
""".format(folder = folder, exe = exe_relpath.replace("/", "\\")))
    else:
        # readlink -f isn't portable to macOS; substitute a portable
        # idiom that walks symlinks until it lands on the realpath.
        rctx.file(launcher_name, """\
#!/usr/bin/env bash
# Launcher generated by rules_chrome. Exec's the real {binary} binary
# inside its extracted bundle so dyld / ld.so resolve neighbouring
# resources via @executable_path / $ORIGIN.
set -euo pipefail
src="${{BASH_SOURCE[0]}}"
while [ -L "$src" ]; do
  dir="$(cd -P "$(dirname "$src")" >/dev/null 2>&1 && pwd)"
  src="$(readlink "$src")"
  [[ "$src" != /* ]] && src="$dir/$src"
done
dir="$(cd -P "$(dirname "$src")" >/dev/null 2>&1 && pwd)"
exec "$dir/{folder}/{exe}" "$@"
""".format(binary = binary, folder = folder, exe = exe_relpath))

    toolchain_block = ""
    if with_toolchain:
        # The @chrome repo also registers a toolchain that bundles both
        # the chrome binary *and*, if @chromedriver is materialized, its
        # driver — via @rules_chrome's central toolchain rule.
        toolchain_block = """
load("@rules_chrome//chrome:toolchains.bzl", "chrome_toolchain")

chrome_toolchain(
    name = "chrome_toolchain",
    chrome = ":chrome",
    chromedriver = "@chromedriver//:chromedriver",
)

toolchain(
    name = "chrome_toolchain_def",
    toolchain = ":chrome_toolchain",
    toolchain_type = "@rules_chrome//chrome:toolchain_type",
)
"""

    # The binary target is a launcher script that exec's into the
    # extracted bundle. `data` carries the whole bundle so chrome's
    # runtime resources resolve relative to the real executable.
    rctx.file("BUILD.bazel", """\
load("@bazel_skylib//rules:native_binary.bzl", "native_binary")

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "all_files",
    srcs = glob(["{folder}/**"], allow_empty = False),
)

native_binary(
    name = "{binary}",
    src = "{launcher}",
    out = "{binary_out}",
    data = [":all_files"],
)
{toolchain_block}""".format(
        folder = folder,
        binary = binary,
        binary_out = binary + (".exe" if is_windows else ""),
        launcher = launcher_name,
        toolchain_block = toolchain_block,
    ))

def _chrome_repository_impl(rctx):
    platform = _resolve_platform(rctx)
    version = rctx.attr.version
    sha256 = KNOWN_VERSIONS.get("chrome", {}).get(version, {}).get(platform, "")
    _binary_repo_impl(
        rctx,
        binary = "chrome",
        version = version,
        platform = platform,
        sha256 = sha256,
        with_toolchain = True,
    )

def _chromedriver_repository_impl(rctx):
    platform = _resolve_platform(rctx)
    version = rctx.attr.version
    sha256 = KNOWN_VERSIONS.get("chromedriver", {}).get(version, {}).get(platform, "")
    _binary_repo_impl(
        rctx,
        binary = "chromedriver",
        version = version,
        platform = platform,
        sha256 = sha256,
        with_toolchain = False,
    )

_chrome_repository = repository_rule(
    implementation = _chrome_repository_impl,
    attrs = {
        "version": attr.string(
            mandatory = True,
            doc = "Chrome for Testing version (e.g. \"148.0.7778.167\").",
        ),
    },
    doc = "Fetch the prebuilt Chrome for Testing binary for the host platform.",
)

_chromedriver_repository = repository_rule(
    implementation = _chromedriver_repository_impl,
    attrs = {
        "version": attr.string(
            mandatory = True,
            doc = "Chrome for Testing chromedriver version (must match the chrome version).",
        ),
    },
    doc = "Fetch the matching chromedriver binary for the host platform.",
)

def _chrome_extension_impl(mctx):
    # Reduce all toolchain tags across the dep graph to one version.
    # Root module wins; otherwise the latest tag seen.
    version = DEFAULT_VERSION
    for mod in mctx.modules:
        for tag in mod.tags.toolchain:
            if tag.version:
                version = tag.version

    _chrome_repository(name = "chrome", version = version)
    _chromedriver_repository(name = "chromedriver", version = version)

_toolchain_tag = tag_class(attrs = {
    "version": attr.string(
        default = "",
        doc = "Override the Chrome for Testing version. Defaults to the value in known_versions.bzl.",
    ),
})

chrome = module_extension(
    implementation = _chrome_extension_impl,
    tag_classes = {"toolchain": _toolchain_tag},
    doc = "Sets up @chrome and @chromedriver as Bazel-fetched prebuilt binaries.",
)
