"""User-facing Bazel rules for rules_podman.

Three `bazel run`-friendly wrappers around the Podman binary resolved
through `@rules_podman//podman:toolchain_type`:

- `podman_run`: a thin launcher — exec podman with optional
  `--connection`/`--url`, an optional isolated storage root, and any
  baked-in `extra_args`, forwarding CLI arguments verbatim.
- `podman_build`: stage a tracked build context (the rule's `srcs`)
  into a temp dir and `podman build` it. Inputs are real Bazel deps, so
  edits to the Containerfile / context invalidate the run.
- `podman_image_load`: `podman load -i <tarball>` an OCI/docker archive
  produced elsewhere in the graph (e.g. `@rules_oci`'s `oci_load`).

Daemonless on Linux: the default toolchain there is the static
`mgoltzsche/podman-static` engine, so these rules run containers with no
service — podman forks conmon → crun directly. On macOS/Windows the
toolchain is the official client, which needs a `podman machine`; point
it at one via `CONTAINER_HOST`, `url`/`connection`, or a running machine.

Storage isolation (`storage = "ephemeral"|"workspace"`) injects
`--root`/`--runroot`/`--storage-driver=vfs` so a run gets a clean,
host-independent container store. It only applies to engine toolchains
(those flags are server-side; a remote client ignores them).

For the bare binary depend directly on `@podman//:podman`.
"""

def _shell_quote(s):
    """Single-quote a string for safe inclusion in /bin/sh -c contexts."""
    return "'" + s.replace("'", "'\\''") + "'"

def _conn_flags(ctx):
    """`--connection` / `--url` global flags, as a quoted string."""
    flags = []
    if ctx.attr.connection:
        flags += ["--connection", ctx.attr.connection]
    if ctx.attr.url:
        flags += ["--url", ctx.attr.url]
    return " ".join([_shell_quote(f) for f in flags])

def _storage(ctx, engine):
    """Return (setup_bash, global_flags) for the requested storage mode.

    Only engine (daemonless) toolchains get isolated stores — `--root`
    et al. are server-side and a remote client rejects them. The flags
    reference the bash var `$PODMAN_STORE` defined by `setup_bash`, so
    they are emitted raw (not shell-quoted).
    """
    mode = getattr(ctx.attr, "storage", "default")
    if mode == "default" or not engine:
        return ("", "")

    if mode == "ephemeral":
        setup = "\n".join([
            'PODMAN_STORE="$(mktemp -d "${TMPDIR:-/tmp}/podman_store.XXXXXX")"',
            "trap 'rm -rf \"$PODMAN_STORE\"' EXIT",
        ])
    else:  # "workspace"
        rel = ctx.attr.storage_dir or (".cache/rules_podman/" + ctx.label.name)
        setup = "\n".join([
            'if [[ -z "${BUILD_WORKSPACE_DIRECTORY:-}" ]]; then',
            '  echo "rules_podman: storage=\\"workspace\\" requires bazel run" >&2',
            "  exit 3",
            "fi",
            'PODMAN_STORE="$BUILD_WORKSPACE_DIRECTORY/' + rel + '"',
            'mkdir -p "$PODMAN_STORE"',
        ])
    flags = '--root "$PODMAN_STORE/root" --runroot "$PODMAN_STORE/runroot" --storage-driver vfs'
    return (setup, flags)

# Common preamble: locate the toolchain's podman binary inside runfiles
# and define a `resolve` helper that maps any runfiles short_path to an
# absolute path (external-repo paths are "../"-prefixed; main-repo paths
# nest under the workspace name).
_PREAMBLE = """\
#!/usr/bin/env bash
# Generated by rules_podman.
set -euo pipefail

if [[ -z "${{RUNFILES_DIR:-}}" ]]; then
  if [[ -d "$0.runfiles" ]]; then
    RUNFILES_DIR="$0.runfiles"
  fi
fi

WS_NAME={ws_name}

resolve() {{
  local sp="$1"
  if [[ "$sp" == ../* ]]; then
    printf '%s/%s' "${{RUNFILES_DIR}}" "${{sp#../}}"
  else
    printf '%s/%s/%s' "${{RUNFILES_DIR}}" "${{WS_NAME}}" "$sp"
  fi
}}

PODMAN="$(resolve {podman_sp})"
if [[ ! -x "$PODMAN" ]]; then
  echo "rules_podman: podman not executable at $PODMAN" >&2
  exit 2
fi
"""

def _toolchain_podman(ctx):
    """Return (executable File, runfiles, engine bool) for the resolved podman."""
    tc = ctx.toolchains["@rules_podman//podman:toolchain_type"].podmaninfo
    target = tc.podman
    return (
        target[DefaultInfo].files_to_run.executable,
        target[DefaultInfo].default_runfiles,
        tc.engine,
    )

def _emit_runner(ctx, *, podman_short_path, podman_runfiles, extra_files, body):
    runner = ctx.actions.declare_file(ctx.label.name + ".sh")
    ctx.actions.write(
        output = runner,
        is_executable = True,
        content = _PREAMBLE.format(
            ws_name = _shell_quote(ctx.workspace_name),
            podman_sp = _shell_quote(podman_short_path),
        ) + body,
    )
    runfiles = ctx.runfiles(files = [runner] + extra_files).merge(podman_runfiles)
    return [DefaultInfo(executable = runner, runfiles = runfiles)]

# Attrs shared by every rule.
_CONNECTION_ATTRS = {
    "connection": attr.string(
        default = "",
        doc = "Named Podman system connection to target (`--connection`).",
    ),
    "url": attr.string(
        default = "",
        doc = "Podman service URL to target (`--url`), e.g. " +
              "`unix:///run/podman/podman.sock` or an `ssh://` endpoint. " +
              "Overrides $CONTAINER_HOST for this invocation.",
    ),
    "extra_args": attr.string_list(
        default = [],
        doc = "Flags appended after the rules_podman defaults but before any " +
              "args passed on the CLI.",
    ),
}

# Attrs for rules that support an isolated container store.
_STORAGE_ATTRS = {
    "storage": attr.string(
        default = "default",
        values = ["default", "ephemeral", "workspace"],
        doc = "Container-store isolation (engine/daemonless toolchains only):\n" +
              "* `default`: use podman's standard rootless store (shared, persists).\n" +
              "* `ephemeral`: a fresh `$TMPDIR/podman_store.XXXXXX` with " +
              "`--storage-driver=vfs`, removed on exit. Hermetic, but images don't " +
              "persist across runs.\n" +
              "* `workspace`: a persistent store under " +
              "`$BUILD_WORKSPACE_DIRECTORY/<storage_dir>` (requires `bazel run`).",
    ),
    "storage_dir": attr.string(
        default = "",
        doc = "Workspace-relative store path used when `storage = \"workspace\"`. " +
              "Defaults to `.cache/rules_podman/<target name>`.",
    ),
}

# -----------------------------------------------------------------------------
# podman_run
# -----------------------------------------------------------------------------

def _podman_run_impl(ctx):
    podman_exe, podman_rf, engine = _toolchain_podman(ctx)
    setup, store_flags = _storage(ctx, engine)
    extra = " ".join([_shell_quote(a) for a in ctx.attr.extra_args])
    body = """
{setup}
exec "$PODMAN" {conn} {store} {extra} "$@"
""".format(
        setup = setup,
        conn = _conn_flags(ctx),
        store = store_flags,
        extra = extra,
    )
    return _emit_runner(
        ctx,
        podman_short_path = podman_exe.short_path,
        podman_runfiles = podman_rf,
        extra_files = [],
        body = body,
    )

podman_run = rule(
    implementation = _podman_run_impl,
    executable = True,
    attrs = dict(_CONNECTION_ATTRS, **_STORAGE_ATTRS),
    toolchains = ["@rules_podman//podman:toolchain_type"],
    doc = "Run Podman via `bazel run`. Daemonless on Linux; CLI arguments are " +
          "forwarded verbatim (`bazel run //:podman -- ps -a`).",
)

# -----------------------------------------------------------------------------
# podman_build
# -----------------------------------------------------------------------------

def _podman_build_impl(ctx):
    podman_exe, podman_rf, engine = _toolchain_podman(ctx)
    setup, store_flags = _storage(ctx, engine)

    # Stage every src into a fresh context dir under its path relative to
    # this rule's package, so `COPY ./x` in the Containerfile resolves
    # the way it would from the source tree. Files outside the package
    # keep their full short_path (advanced/escape-hatch case).
    stage_lines = [
        "stage {}".format(_shell_quote(f.short_path))
        for f in ctx.files.srcs
    ]

    flags = []
    for t in ctx.attr.image_tags:
        flags += ["-t", t]
    for k, v in ctx.attr.build_args.items():
        flags += ["--build-arg", "{}={}".format(k, v)]
    extra = list(ctx.attr.extra_args)

    body = """
{setup}
PKG={pkg}
CTX="$(mktemp -d "${{TMPDIR:-/tmp}}/podman_build.XXXXXX")"
trap 'rm -rf "$CTX"' EXIT

stage() {{
  local sp="$1" abs rel
  abs="$(resolve "$sp")"
  if [[ "$sp" == "$PKG/"* ]]; then rel="${{sp#$PKG/}}"; else rel="$sp"; fi
  mkdir -p "$CTX/$(dirname "$rel")"
  cp -RL "$abs" "$CTX/$rel"
}}
{stage_lines}

exec "$PODMAN" {conn} {store} build -f "$CTX/{containerfile}" {flags} {extra} "$CTX" "$@"
""".format(
        setup = setup,
        pkg = _shell_quote(ctx.label.package),
        stage_lines = "\n".join(stage_lines),
        conn = _conn_flags(ctx),
        store = store_flags,
        containerfile = ctx.attr.containerfile,
        flags = " ".join([_shell_quote(x) for x in flags]),
        extra = " ".join([_shell_quote(x) for x in extra]),
    )

    return _emit_runner(
        ctx,
        podman_short_path = podman_exe.short_path,
        podman_runfiles = podman_rf,
        extra_files = ctx.files.srcs,
        body = body,
    )

podman_build = rule(
    implementation = _podman_build_impl,
    executable = True,
    attrs = dict(_CONNECTION_ATTRS, **dict(_STORAGE_ATTRS, **{
        "srcs": attr.label_list(
            allow_files = True,
            mandatory = True,
            doc = "The build context: the Containerfile plus everything it " +
                  "COPYs/ADDs. Staged into the build context preserving each " +
                  "file's path relative to this rule's package.",
        ),
        "containerfile": attr.string(
            default = "Containerfile",
            doc = "Path of the Containerfile within the staged context " +
                  "(i.e. relative to this rule's package). Must be among `srcs`.",
        ),
        "image_tags": attr.string_list(
            default = [],
            doc = "Image tags to apply (`-t`). (Named `image_tags`, not `tags`, " +
                  "which is Bazel's reserved target-tags attribute.)",
        ),
        "build_args": attr.string_dict(
            default = {},
            doc = "`--build-arg KEY=VALUE` pairs passed to `podman build`.",
        ),
    })),
    toolchains = ["@rules_podman//podman:toolchain_type"],
    doc = "Build an image from a tracked build context via `bazel run`. Stages " +
          "`srcs` into a temp context and runs `podman build` (daemonless on Linux).",
)

# -----------------------------------------------------------------------------
# podman_image_load
# -----------------------------------------------------------------------------

def _podman_image_load_impl(ctx):
    podman_exe, podman_rf, engine = _toolchain_podman(ctx)
    setup, store_flags = _storage(ctx, engine)
    tar = ctx.file.image
    extra = " ".join([_shell_quote(a) for a in ctx.attr.extra_args])
    body = """
{setup}
IMG="$(resolve {image_sp})"
exec "$PODMAN" {conn} {store} load -i "$IMG" {extra} "$@"
""".format(
        setup = setup,
        image_sp = _shell_quote(tar.short_path),
        conn = _conn_flags(ctx),
        store = store_flags,
        extra = extra,
    )
    return _emit_runner(
        ctx,
        podman_short_path = podman_exe.short_path,
        podman_runfiles = podman_rf,
        extra_files = [tar],
        body = body,
    )

podman_image_load = rule(
    implementation = _podman_image_load_impl,
    executable = True,
    attrs = dict(_CONNECTION_ATTRS, **dict(_STORAGE_ATTRS, **{
        "image": attr.label(
            allow_single_file = True,
            mandatory = True,
            doc = "An OCI-archive or docker-archive tarball to `podman load`, " +
                  "e.g. the output of `@rules_oci`'s `oci_load` rule.",
        ),
    })),
    toolchains = ["@rules_podman//podman:toolchain_type"],
    doc = "`podman load -i <tarball>` an image archive into the target store via " +
          "`bazel run`. Use `storage = \"workspace\"` to load into a persistent store.",
)
