"""Module extension for rules_podman.

Hermetically fetches Podman for the host platform, pinned by sha256
(see `private/known_versions.bzl`), and exposes it as `@podman//:podman`
plus a ready-to-register toolchain (`@podman//:podman_toolchain_def`).

On Linux it fetches the fully-static `mgoltzsche/podman-static` bundle
and generates a launcher that wires podman to its **bundled** OCI
runtime (crun), conmon, netavark, and configs — a real **daemonless,
rootless** engine, no service to start. On macOS/Windows it fetches the
official client binary (which talks to a `podman machine`).

Default usage:

    podman = use_extension("@rules_podman//podman:extensions.bzl", "podman")
    use_repo(podman, "podman")
    register_toolchains("@podman//:podman_toolchain_def")

Pin a specific Podman version:

    podman = use_extension("@rules_podman//podman:extensions.bzl", "podman")
    podman.toolchain(version = "5.8.2")
    use_repo(podman, "podman")
"""

load(
    "//podman/private:known_versions.bzl",
    "DEFAULT_VERSION",
    "GITHUB_DOWNLOAD",
    "KNOWN_VERSIONS",
    "PLATFORMS",
)

def _resolve_platform(rctx):
    os = rctx.os.name.lower()
    arch = rctx.os.arch.lower()
    if "linux" in os and arch in ("x86_64", "amd64"):
        return "linux_amd64"
    if "linux" in os and arch in ("aarch64", "arm64"):
        return "linux_arm64"
    if ("mac" in os or "darwin" in os) and arch in ("aarch64", "arm64"):
        return "darwin_arm64"
    if ("mac" in os or "darwin" in os) and arch in ("x86_64", "amd64"):
        return "darwin_amd64"
    if "windows" in os and arch in ("x86_64", "amd64"):
        return "windows_amd64"
    if "windows" in os and arch in ("aarch64", "arm64"):
        return "windows_arm64"
    fail("rules_podman: unsupported platform os=%s arch=%s" % (os, arch))

# Launcher for the daemonless Linux engine. Resolves its own real path
# (walking symlinks) to find the extracted bundle sitting beside it, then
# points podman at the bundled runtimes/helpers/configs before exec. All
# wiring is overridable from the environment so callers can still supply
# their own containers.conf etc. `{top}` is the bundle's top-level dir.
_LINUX_LAUNCHER = """\
#!/usr/bin/env bash
# Generated by rules_podman — daemonless rootless Podman launcher.
set -euo pipefail

src="${{BASH_SOURCE[0]}}"
while [ -L "$src" ]; do
  d="$(cd -P "$(dirname "$src")" >/dev/null 2>&1 && pwd)"
  src="$(readlink "$src")"
  [[ "$src" != /* ]] && src="$d/$src"
done
HERE="$(cd -P "$(dirname "$src")" >/dev/null 2>&1 && pwd)"
ROOT="$HERE/{top}"

# Bundled crun/runc/pasta/fuse-overlayfs come first on PATH; conmon,
# netavark, aardvark-dns, rootlessport, catatonit live in the helper dir.
export PATH="$ROOT/usr/local/bin:${{PATH:-}}"
export CONTAINERS_HELPER_BINARY_DIR="${{CONTAINERS_HELPER_BINARY_DIR:-$ROOT/usr/local/lib/podman}}"
export CONTAINERS_CONF="${{CONTAINERS_CONF:-$ROOT/etc/containers/containers.conf}}"
export CONTAINERS_REGISTRIES_CONF="${{CONTAINERS_REGISTRIES_CONF:-$ROOT/etc/containers/registries.conf}}"

# conmon and the OCI runtime are NOT found via $PATH or
# CONTAINERS_HELPER_BINARY_DIR — podman reads their locations from
# containers.conf's `[engine] conmon_path` / `runtime`. The bundle's
# containers.conf doesn't set them, so podman falls back to compiled-in
# *absolute* defaults (/usr/local/lib/podman/conmon, /usr/bin/conmon, …)
# that don't exist once Bazel relocates the tree into runfiles — hence
# "could not find a working conmon binary". Emit a CONTAINERS_CONF_OVERRIDE
# (the last/highest-priority layer) re-pointing them at the relocated
# $ROOT. Other base-conf keys (cgroup_manager, events_logger) still apply.
if [[ -z "${{CONTAINERS_CONF_OVERRIDE:-}}" ]]; then
  _conf_override="$(mktemp "${{TMPDIR:-/tmp}}/rules_podman_conf.XXXXXX")"
  cat >"$_conf_override" <<EOF
[engine]
conmon_path = ["$ROOT/usr/local/lib/podman/conmon"]
helper_binaries_dir = ["$ROOT/usr/local/lib/podman"]
runtime = "crun"
[engine.runtimes]
crun = ["$ROOT/usr/local/bin/crun"]
runc = ["$ROOT/usr/local/bin/runc"]
EOF
  export CONTAINERS_CONF_OVERRIDE="$_conf_override"
fi

# podman has no env var or global flag for the image signature policy; it only
# reads /etc/containers/policy.json or $HOME/.config/containers/policy.json. On
# a host with neither (e.g. a from-scratch CI image) every pull/run aborts with
# "no policy.json file found". If neither exists, seed the bundle's (permissive)
# policy.json at the user-level default path — best-effort, and never clobbering
# an existing one. Storage is left to podman's rootless defaults; the bundle's
# storage.conf is root-oriented (graphroot=/var/lib/containers), wrong for a
# rootless nonroot user.
if [[ ! -f /etc/containers/policy.json &&
      -n "${{HOME:-}}" &&
      ! -f "$HOME/.config/containers/policy.json" &&
      -f "$ROOT/etc/containers/policy.json" ]]; then
  mkdir -p "$HOME/.config/containers" 2>/dev/null &&
    cp "$ROOT/etc/containers/policy.json" "$HOME/.config/containers/policy.json" 2>/dev/null ||
    true
fi

exec "$ROOT/usr/local/bin/podman" "$@"
"""

def _engine_build(top, version):
    """Generated BUILD for a daemonless Linux engine bundle."""
    return """\
load("@bazel_skylib//rules:native_binary.bzl", "native_binary")
load("@rules_podman//podman:toolchains.bzl", "podman_toolchain")

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "all_files",
    srcs = glob(["{top}/**"], allow_empty = False),
)

# The launcher is the executable; the whole bundle rides along as
# runfiles so the launcher can locate the runtimes/helpers/configs.
native_binary(
    name = "podman",
    src = "launcher.sh",
    out = "podman",
    data = [":all_files"],
)

podman_toolchain(
    name = "podman_toolchain",
    podman = ":podman",
    version = "{version}",
    engine = True,
)

toolchain(
    name = "podman_toolchain_def",
    toolchain = ":podman_toolchain",
    toolchain_type = "@rules_podman//podman:toolchain_type",
)
""".format(top = top, version = version)

def _client_build(binary_rel, exe_suffix, version):
    """Generated BUILD for a single client binary (macOS/Windows)."""
    return """\
load("@bazel_skylib//rules:native_binary.bzl", "native_binary")
load("@rules_podman//podman:toolchains.bzl", "podman_toolchain")

package(default_visibility = ["//visibility:public"])

native_binary(
    name = "podman",
    src = "{binary_rel}",
    out = "podman{exe_suffix}",
)

podman_toolchain(
    name = "podman_toolchain",
    podman = ":podman",
    version = "{version}",
    engine = False,
)

toolchain(
    name = "podman_toolchain_def",
    toolchain = ":podman_toolchain",
    toolchain_type = "@rules_podman//podman:toolchain_type",
)
""".format(
        binary_rel = binary_rel,
        exe_suffix = exe_suffix,
        version = version,
    )

def _podman_repository_impl(rctx):
    platform = _resolve_platform(rctx)
    version = rctx.attr.version
    layout = PLATFORMS[platform]
    asset = layout["asset"].format(version = version)
    url = GITHUB_DOWNLOAD.format(repo = layout["repo"], version = version, asset = asset)

    sha256 = KNOWN_VERSIONS.get(version, {}).get(platform, "")
    if not sha256:
        # buildifier: disable=print
        print(("rules_podman: WARNING — no pinned sha256 for podman@{v} on {p}; " +
               "downloading unverified. Run `tools/refresh_versions.py " +
               "--version {v}` to lock it.").format(v = version, p = platform))

    # Keep the upstream layout intact (no stripPrefix); the launcher /
    # native_binary reference files by their full in-archive path.
    rctx.download_and_extract(url = url, sha256 = sha256 or "")

    if layout["engine"]:
        top = layout["bundle_top"]
        rctx.file("launcher.sh", _LINUX_LAUNCHER.format(top = top))
        rctx.file("BUILD.bazel", _engine_build(top, version))
    else:
        binary_rel = layout["binary"].format(version = version)
        exe_suffix = ".exe" if platform.startswith("windows") else ""
        rctx.file("BUILD.bazel", _client_build(binary_rel, exe_suffix, version))

_podman_repository = repository_rule(
    implementation = _podman_repository_impl,
    attrs = {
        "version": attr.string(
            mandatory = True,
            doc = "Podman release version to fetch (e.g. \"5.8.2\").",
        ),
    },
    doc = "Fetch the prebuilt Podman engine (Linux) or client (macOS/Windows) for the host.",
)

def _podman_extension_impl(mctx):
    # Reduce all toolchain tags across the dep graph to one version.
    # Root module wins; otherwise the last tag seen.
    version = DEFAULT_VERSION
    for mod in mctx.modules:
        for tag in mod.tags.toolchain:
            if tag.version:
                version = tag.version

    _podman_repository(name = "podman", version = version)

_toolchain_tag = tag_class(attrs = {
    "version": attr.string(
        default = "",
        doc = "Override the Podman version. Defaults to the value in known_versions.bzl.",
    ),
})

podman = module_extension(
    implementation = _podman_extension_impl,
    tag_classes = {"toolchain": _toolchain_tag},
    doc = "Sets up @podman: a daemonless static engine on Linux, the official client on macOS/Windows.",
)
