"""Emit a Starlark map `CFN_TYPES = {kind_id: cfn_type, ...}` from the
assembled CloudFormation Resource Specification.

Motivation: the spec-derived rules in `defs.bzl` use snake-cased kind
ids (`aws_s3_bucket`, `aws_application_auto_scaling_scalable_target`)
in the shard filenames the stack aggregator reads. The CFN
`Type` string the aggregator needs to emit (`AWS::S3::Bucket`,
`AWS::ApplicationAutoScaling::ScalableTarget`) is NOT recoverable
from the snake-cased id — segment boundaries are lost.

The assembler-produced schema keys preserve the original
`AWS_Service_Resource` form (one underscore per `::`), so we can
reconstruct Type strings by walking the assembled schema. This
script does that and emits a frozen Starlark dict the aggregator
loads at analysis time.

Argv: `--schema=PATH --output=PATH`.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path


_KIND_KEY_RE = re.compile(r"^AWS_[^_]+_[^_]+$")


def to_snake_case(key: str) -> str:
    # Mirrors the snake_case derivation in
    # rules_jsonschema/tools/schema_to_starlark/src/main.rs so
    # filename kind ids round-trip through this map cleanly.
    out: list[str] = []
    prev_lower = False
    for ch in key:
        if ch.isalnum():
            if ch.isupper() and prev_lower:
                out.append("_")
            out.append(ch.lower())
            prev_lower = ch.islower() or ch.isdigit()
        else:
            if out and out[-1] != "_":
                out.append("_")
            prev_lower = False
    return "".join(out).strip("_")


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--schema", required=True, type=Path)
    ap.add_argument("--output", required=True, type=Path)
    args = ap.parse_args(argv)

    schema = json.loads(args.schema.read_text())
    definitions = schema.get("definitions", {})

    mapping: dict[str, str] = {}
    for raw_key in sorted(definitions.keys()):
        if not _KIND_KEY_RE.match(raw_key):
            continue
        cfn_type = raw_key.replace("_", "::")
        mapping[to_snake_case(raw_key)] = cfn_type

    lines = [
        '"""Generated by extract_cfn_types.py. DO NOT EDIT.',
        "",
        "Maps snake-cased kind ids (the form used in rules_jsonschema",
        "schema_to_starlark shard filenames) to their CFN Type strings",
        "(`AWS::Service::Resource`).",
        '"""',
        "",
        "CFN_TYPES = {",
    ]
    for kind_id, cfn_type in sorted(mapping.items()):
        lines.append(f'    "{kind_id}": "{cfn_type}",')
    lines.append("}")
    lines.append("")

    args.output.write_text("\n".join(lines))
    print(f"extract_cfn_types: wrote {len(mapping)} entries to {args.output}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
