//! Bulk-lift codegen: emit one `pg_finfo_NAME` per entry in
//! manifest.json. The C macro expansion (see fmgr.h:415) is:
//!
//!   const Pg_finfo_record *pg_finfo_NAME(void) {
//!       static const Pg_finfo_record my_finfo = { 1 };
//!       return &my_finfo;
//!   }
//!
//! Every one of the 871 entries is literally that — only the suffix
//! NAME varies. The Rust template mirrors it with a `static FINFO`
//! per function, returning a raw pointer through `extern "C"` so the
//! ABI matches Postgres' shared-lib loader.
//!
//! This is the trivial half of the fmgr-V1 lift cluster (companion to
//! the 983 `Datum fn(FunctionCallInfo)` bodies — those are the real
//! datatype operators and ship in a sibling crate).

use std::env;
use std::fs;
use std::path::PathBuf;

use serde::Deserialize;

#[derive(Deserialize)]
struct Entry {
    ident: String,
    fmgr_name: String,
    #[allow(dead_code)]
    tu: String,
}

fn main() {
    println!("cargo:rerun-if-changed=manifest.json");
    println!("cargo:rerun-if-changed=build.rs");

    let manifest_text = fs::read_to_string("manifest.json")
        .expect("read manifest.json (expected at crate root)");
    let entries: Vec<Entry> =
        serde_json::from_str(&manifest_text).expect("parse manifest.json");

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let gen_path = out_dir.join("generated.rs");

    let mut out = String::with_capacity(64 * entries.len());
    out.push_str(
        "// THIS FILE IS GENERATED BY build.rs. DO NOT EDIT BY HAND.\n\
         //\n\
         // One `pg_finfo_NAME` stub per entry in manifest.json. Lifts\n\
         // Postgres' PG_FUNCTION_INFO_V1 macro expansion verbatim.\n\
         // Included via `include!()` from src/lib.rs, so PgFinfoRecord\n\
         // resolves to the same-module definition (no `use` needed).\n\
         \n",
    );
    for e in &entries {
        // Each stub gets a private static. The compiler de-dupes
        // these into rodata as identical instances, but keeping them
        // separate matches C's per-function `static const my_finfo`.
        out.push_str(&format!(
            "#[no_mangle]\n\
             pub unsafe extern \"C\" fn {ident}() -> *const PgFinfoRecord {{\n\
             \x20   static FINFO: PgFinfoRecord = PgFinfoRecord {{ api_version: 1 }};\n\
             \x20   &FINFO\n\
             }}\n\
             \n",
            ident = e.ident,
        ));
    }

    // Also emit a const slice listing every (fmgr_name, fn-pointer)
    // pair so tests can iterate the whole set without re-parsing the
    // manifest. Format chosen for trivial `&'static [(&str, ...)]`
    // consumption.
    out.push_str(
        "/// All `pg_finfo_*` stubs in this crate, as `(fmgr_name, fn_ptr)` pairs.\n\
         /// Iterated by the smoke test to assert each returns api_version == 1.\n\
         pub const PG_FINFO_TABLE: &[(&str, unsafe extern \"C\" fn() -> *const PgFinfoRecord)] = &[\n",
    );
    for e in &entries {
        out.push_str(&format!(
            "    ({:?}, {}),\n",
            e.fmgr_name, e.ident,
        ));
    }
    out.push_str("];\n");

    fs::write(&gen_path, out).expect("write generated.rs");

    println!(
        "cargo:warning=pg_finfo_v1: emitted {} stubs to {}",
        entries.len(),
        gen_path.display()
    );
}
