"""SHA-256 pin for the prebuilt vfkit binary.

Generated by `tools/refresh_versions.py`. Bump with:

    tools/refresh_versions.py --version <X.Y.Z>

vfkit (crc-org/vfkit) ships ONE asset per release named `vfkit`: a
signed **universal** (x86_64 + arm64) Mach-O carrying the
`com.apple.security.virtualization` entitlement — that entitlement is
what grants access to Apple's Virtualization.framework. The release also
publishes `vfkit-unsigned`, which lacks the entitlement; rules_macvm
never uses it. A byte-identical copy (what `native_binary` makes)
preserves the embedded signature, so the fetched binary stays valid.
"""

# Map: version -> sha256 of the signed universal `vfkit` asset.
KNOWN_VERSIONS = {
    "0.6.3": "19d0695d40d996ec38529a22b73cdaa84ff67ba15f4b44927292e7fe885cee0e",
}

DEFAULT_VERSION = "0.6.3"

URL_TEMPLATE = "https://github.com/crc-org/vfkit/releases/download/v{version}/vfkit"
