"""SHA-256 pins for the prebuilt Podman binaries.

Generated by `tools/refresh_versions.py`. Bumping the pinned version is:

    tools/refresh_versions.py --version <X.Y.Z>

…which downloads each per-platform release asset, hashes it, and
rewrites this file. Unpinned versions still build (a warning is emitted)
but lose hermeticity. Always prefer pinning.

Source split — this is what makes Linux daemonless:

  * Linux (amd64/arm64): the fully-static, **rootless + daemonless**
    bundle from `mgoltzsche/podman-static` — podman plus its OCI
    runtimes (crun/runc), conmon, netavark/aardvark-dns/pasta, and
    fuse-overlayfs. `podman` forks conmon → crun directly; there is no
    service to start. This is a real container engine, fully hermetic.

  * macOS / Windows: the official `containers/podman` client. Those
    OSes have no Linux kernel, so Podman can only run Linux containers
    via a `podman machine` VM (which runs a service inside). The client
    is fetched + pinned hermetically; it is NOT daemonless — that's an
    OS limitation, not ours. Kept for local development. See README.md.
"""

# Map: version -> platform_key -> sha256. Platform keys are
# "<os>_<arch>" matching `_resolve_platform` in extensions.bzl.
KNOWN_VERSIONS = {
    "5.8.2": {
        "linux_amd64": "228b9adf1ba3585d1d72f0a4bb9a669de5ea806d13884b2c43b5e65601a1a580",
        "linux_arm64": "1f58a8318034f9af44b96af88326a4fd44cc4c5ba8de682d7d35b054d76e65b6",
        "darwin_amd64": "8c54f845651fd606512debd509a273f7a8d20e6ab0adb372a46863608275aa78",
        "darwin_arm64": "2379bcb0bf320df5deccf84115337109d3f9051f7d017948ee68a92ce932e798",
        "windows_amd64": "1b60aae4bd4879c3932c283d2070bb87116ec1f0ab3a4a98eff7e65f318f9e4e",
        "windows_arm64": "06c64d11267232ba21d3e43962c0e9036f24550d87fb811bc995195d82c32fca",
    },
}

DEFAULT_VERSION = "5.8.2"

# Asset URL: github.com/<repo>/releases/download/v<version>/<asset>.
GITHUB_DOWNLOAD = "https://github.com/{repo}/releases/download/v{version}/{asset}"

# Per host platform. `{version}` interpolates the release version where
# the archive nests under a versioned dir.
#
# Fields:
#   repo        : GitHub repo the asset is published from.
#   asset       : release asset filename to download.
#   engine      : True  -> daemonless local engine bundle (Linux). The
#                          repository rule generates a launcher that
#                          points podman at the bundled runtimes,
#                          helpers, and configs.
#                 False -> single client binary (macOS/Windows); needs a
#                          reachable Podman service / `podman machine`.
#   bundle_top  : (engine) top-level dir the tarball extracts into; the
#                 binary is <bundle_top>/usr/local/bin/podman.
#   binary      : (client) path to the podman binary inside the archive.
PLATFORMS = {
    "linux_amd64": {
        "repo": "mgoltzsche/podman-static",
        "asset": "podman-linux-amd64.tar.gz",
        "engine": True,
        "bundle_top": "podman-linux-amd64",
    },
    "linux_arm64": {
        "repo": "mgoltzsche/podman-static",
        "asset": "podman-linux-arm64.tar.gz",
        "engine": True,
        "bundle_top": "podman-linux-arm64",
    },
    "darwin_amd64": {
        "repo": "containers/podman",
        "asset": "podman-remote-release-darwin_amd64.zip",
        "engine": False,
        "binary": "podman-{version}/usr/bin/podman",
    },
    "darwin_arm64": {
        "repo": "containers/podman",
        "asset": "podman-remote-release-darwin_arm64.zip",
        "engine": False,
        "binary": "podman-{version}/usr/bin/podman",
    },
    "windows_amd64": {
        "repo": "containers/podman",
        "asset": "podman-remote-release-windows_amd64.zip",
        "engine": False,
        "binary": "podman-{version}/usr/bin/podman.exe",
    },
    "windows_arm64": {
        "repo": "containers/podman",
        "asset": "podman-remote-release-windows_arm64.zip",
        "engine": False,
        "binary": "podman-{version}/usr/bin/podman.exe",
    },
}
