//! schema_to_rust: turn a JSON Schema document into Rust type
//! definitions. Default codegen toolchain behind rules_jsonschema's
//! `jsonschema_rust_library` rule.
//!
//! Wraps [`typify::TypeSpace`] — most of the heavy lifting (ref
//! resolution, `oneOf`/`allOf` handling, enum generation, snake_case
//! conversion) lives upstream. This CLI exists so the codegen step
//! is one hermetic action.
//!
//! ## Contract
//!
//! Implements the rules_jsonschema plugin contract (see
//! [`jsonschema/plugin_contract.md`](../../jsonschema/plugin_contract.md)):
//!
//!   * stdin: schema file contents (JSON)
//!   * argv: `--schema-name=NAME`, `--rule-name=NAME`
//!   * stdout: generated Rust source
//!   * stderr: warnings + errors
//!   * exit: 0 success, non-zero failure
//!
//! The generated file always begins with a `#![allow(...)]` preamble
//! because typify-generated code uses non-snake-case identifiers
//! when the schema does, and serde's typed enums can introduce dead
//! code paths for variants that aren't constructed in any one
//! binary.

use std::collections::HashSet;
use std::io::{self, Read, Write};

use anyhow::{Context, Result};
use schemars::schema::RootSchema;
use typify::{TypeSpace, TypeSpaceSettings};

fn main() -> Result<()> {
    let args = parse_args()?;

    let mut schema_bytes = Vec::new();
    io::stdin()
        .read_to_end(&mut schema_bytes)
        .context("reading schema from stdin")?;
    let mut raw: serde_json::Value = serde_json::from_slice(&schema_bytes)
        .context("parsing schema from stdin")?;
    normalize_schema(&mut raw);
    let schema: RootSchema = serde_json::from_value(raw)
        .context("re-deserialising normalized schema")?;

    let mut settings = TypeSpaceSettings::default();
    settings.with_struct_builder(false);

    let mut type_space = TypeSpace::new(&settings);
    type_space
        .add_root_schema(schema)
        .context("typify failed to ingest schema")?;

    let tokens = type_space.to_stream();

    // prettyplease wants a `syn::File`. Parse our TokenStream through
    // it, then format. If parsing fails (typify emitted something
    // that doesn't round-trip cleanly), fall back to the raw stream —
    // the result is still valid Rust, just not formatted.
    let formatted = match syn::parse2::<syn::File>(tokens.clone()) {
        Ok(file) => prettyplease::unparse(&file),
        Err(e) => {
            eprintln!(
                "schema_to_rust: prettyplease parse failed ({e}); emitting raw token stream"
            );
            tokens.to_string()
        }
    };

    let source_line = if args.schema_name.is_empty() {
        String::new()
    } else {
        format!("//\n// Source schema: {}\n", args.schema_name)
    };
    let preamble = format!(
        "// @generated by rules_jsonschema//tools/schema_to_rust. DO NOT EDIT.\n\
        {source_line}\
        #![allow(clippy::all, dead_code, non_camel_case_types, non_snake_case, unused_imports)]\n"
    );

    let body = format!("{preamble}\n{formatted}");
    io::stdout()
        .write_all(body.as_bytes())
        .context("writing generated source to stdout")?;
    Ok(())
}

#[derive(Debug, Default)]
struct Args {
    schema_name: String,
    #[allow(dead_code)] // accepted for protocol conformance; not used by this plugin
    rule_name: String,
}

/// Pre-processes the schema to dodge typify limitations on
/// real-world schemas. Currently only one fixup: string enums whose
/// values collide under Rust's case-insensitive identifier mangling
/// (e.g. `["z", "Z"]` in compose-spec's selinux option) blow up
/// typify's variant-naming pass. We drop the `enum` constraint in
/// that case — the field stays typed `String`, just without the
/// closed value set.
fn normalize_schema(value: &mut serde_json::Value) {
    match value {
        serde_json::Value::Object(obj) => {
            if let Some(enum_value) = obj.get("enum").cloned() {
                if let Some(arr) = enum_value.as_array() {
                    let strings: Option<Vec<&str>> =
                        arr.iter().map(|v| v.as_str()).collect();
                    if let Some(strings) = strings {
                        let mut seen: HashSet<String> = HashSet::new();
                        let mut collides = false;
                        for s in &strings {
                            if !seen.insert(s.to_lowercase()) {
                                collides = true;
                                break;
                            }
                        }
                        if collides {
                            obj.remove("enum");
                            eprintln!(
                                "schema_to_rust: stripped case-colliding enum {strings:?} to dodge typify variant-naming"
                            );
                        }
                    }
                }
            }
            for (_, v) in obj.iter_mut() {
                normalize_schema(v);
            }
        }
        serde_json::Value::Array(arr) => {
            for v in arr {
                normalize_schema(v);
            }
        }
        _ => {}
    }
}

/// Parses the contract's standard `--schema-name` and `--rule-name`
/// flags. Unknown flags are a hard error per contract.
fn parse_args() -> Result<Args> {
    let mut args = Args::default();
    for raw in std::env::args().skip(1) {
        if raw == "-h" || raw == "--help" {
            eprintln!(
                "Usage: schema_to_rust < schema.json > types.rs \\\n  [--schema-name=NAME] [--rule-name=NAME]"
            );
            std::process::exit(0);
        }
        let Some((key, value)) = raw.split_once('=') else {
            anyhow::bail!("expected --key=value, got: {raw}");
        };
        match key {
            "--schema-name" => args.schema_name = value.to_string(),
            "--rule-name" => args.rule_name = value.to_string(),
            other => anyhow::bail!("unknown flag: {other}"),
        }
    }
    Ok(args)
}
