import Pg.Ir.Emit.ByteaCommon

/-!
# Pg.Ir.Emit.Bytea — Rust emit for the bytea cluster.

Emits two definitions per family:
  1. The `<fn>_catenate`-style static internal helper (the algorithm).
  2. The fmgr stub `<fn>(fcinfo)` (decode args + delegate + return).
-/

namespace Pg.Ir.Emit.Bytea.Rust

open Pg.Ir.Emit.Bytea (ByteaBody ByteaFamily families)

/-- For `catenate` we emit a `<fn>_catenate` static helper. For
`octetLen` and `eq` the body is small enough to inline into the fmgr
stub; no internal helper is needed. -/
def renderInternal (fam : ByteaFamily) : Option String :=
  match fam.body with
  | .catenate => some (
      "unsafe fn bytea_catenate(t1: *const u8, t2: *const u8) -> *mut u8 {\n" ++
      "    let len1 = varsize_any_exhdr(t1);\n" ++
      "    let len2 = varsize_any_exhdr(t2);\n" ++
      "\n" ++
      "    // Postgres has `if (lenN < 0) lenN = 0;` paranoia checks;\n" ++
      "    // with usize typing this is statically impossible.\n" ++
      "\n" ++
      "    let total = len1 + len2 + VARHDRSZ;\n" ++
      "    let result = palloc(total);\n" ++
      "\n" ++
      "    set_varsize_4b(result, total);\n" ++
      "\n" ++
      "    let payload = vardata_4b_mut(result);\n" ++
      "    if len1 > 0 {\n" ++
      "        std::ptr::copy_nonoverlapping(vardata_any(t1), payload, len1);\n" ++
      "    }\n" ++
      "    if len2 > 0 {\n" ++
      "        std::ptr::copy_nonoverlapping(vardata_any(t2), payload.add(len1), len2);\n" ++
      "    }\n" ++
      "\n" ++
      "    result\n" ++
      "}\n")
  | _ => none

def renderFmgrStub (fam : ByteaFamily) : String :=
  match fam.body with
  | .catenate =>
      "#[no_mangle]\n" ++
      "pub unsafe extern \"C\" fn " ++ fam.fnName ++
        "(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {\n" ++
      "    let f = &mut *fcinfo;\n" ++
      "    let t1 = decode_bytea_p(f.args[0].value);\n" ++
      "    let t2 = decode_bytea_p(f.args[1].value);\n" ++
      "    encode_bytea_p(bytea_catenate(t1, t2))\n" ++
      "}\n"
  | .octetLen =>
      -- byteaoctetlen body (verbatim shape of Postgres source):
      --   Datum str = PG_GETARG_DATUM(0);
      --   PG_RETURN_INT32(toast_raw_datum_size(str) - VARHDRSZ);
      "#[no_mangle]\n" ++
      "pub unsafe extern \"C\" fn " ++ fam.fnName ++
        "(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {\n" ++
      "    let f = &mut *fcinfo;\n" ++
      "    let str = f.args[0].value;\n" ++
      "    encode_i32((toast_raw_datum_size(str) - VARHDRSZ) as i32)\n" ++
      "}\n"
  | .eq =>
      -- byteaeq body (fast-path length check, then memcmp):
      --   len1 = toast_raw_datum_size(arg1); len2 = toast_raw_datum_size(arg2);
      --   if (len1 != len2) result = false;
      --   else result = memcmp(VARDATA_ANY(barg1), VARDATA_ANY(barg2),
      --                        len1 - VARHDRSZ) == 0;
      "#[no_mangle]\n" ++
      "pub unsafe extern \"C\" fn " ++ fam.fnName ++
        "(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {\n" ++
      "    let f = &mut *fcinfo;\n" ++
      "    let arg1 = f.args[0].value;\n" ++
      "    let arg2 = f.args[1].value;\n" ++
      "    let len1 = toast_raw_datum_size(arg1);\n" ++
      "    let len2 = toast_raw_datum_size(arg2);\n" ++
      "    let result = if len1 != len2 {\n" ++
      "        false\n" ++
      "    } else {\n" ++
      "        let barg1 = decode_bytea_p(arg1);\n" ++
      "        let barg2 = decode_bytea_p(arg2);\n" ++
      "        let p1 = vardata_any(barg1);\n" ++
      "        let p2 = vardata_any(barg2);\n" ++
      "        let n = len1 - VARHDRSZ;\n" ++
      "        std::slice::from_raw_parts(p1, n) == std::slice::from_raw_parts(p2, n)\n" ++
      "    };\n" ++
      "    encode_bool(result)\n" ++
      "}\n"

def rustSource : String :=
  let header :=
    "// Generated by `rules_postgres/lean/Pg/Ir/Emit/Bytea.lean`.\n" ++
    "// DO NOT EDIT BY HAND. Regenerate via\n" ++
    "// `rules_postgres/tools/regen/regen-bytea.sh`.\n" ++
    "//\n" ++
    "// First varlena-using Pg.Ir cluster. Each family emits a pair:\n" ++
    "//   1. A static internal helper (the algorithm).\n" ++
    "//   2. The V1 fmgr stub (decode args + delegate + return).\n" ++
    "\n" ++
    "#![allow(clippy::missing_safety_doc)]\n" ++
    "\n" ++
    "use pg_fcinfo::{\n" ++
    "    decode_bytea_p, encode_bool, encode_bytea_p, encode_i32,\n" ++
    "    set_varsize_4b, toast_raw_datum_size,\n" ++
    "    vardata_4b_mut, vardata_any, varsize_any_exhdr,\n" ++
    "    FunctionCallInfoBaseData, VARHDRSZ,\n" ++
    "};\n" ++
    "use pg_palloc::palloc;\n"
  Id.run do
    let mut s := header
    for fam in families do
      match renderInternal fam with
      | some internal => s := s ++ "\n" ++ internal ++ "\n" ++ renderFmgrStub fam
      | none          => s := s ++ "\n" ++ renderFmgrStub fam
    return s

end Pg.Ir.Emit.Bytea.Rust

def main : IO Unit := IO.print Pg.Ir.Emit.Bytea.Rust.rustSource
