import Pg.Ir.Emit.ByteaCommon

/-!
# Pg.Ir.Emit.ByteaC — emit real-style Postgres C for the bytea cluster
(AST grounding companion to Bytea.lean).
-/

namespace Pg.Ir.Emit.Bytea.C

open Pg.Ir.Emit.Bytea (ByteaBody ByteaFamily families)

def renderCInternal (fam : ByteaFamily) : Option String :=
  match fam.body with
  | .catenate => some (
      "static bytea *\n" ++
      "bytea_catenate(bytea *t1, bytea *t2)\n" ++
      "{\n" ++
      "\tbytea\t   *result;\n" ++
      "\tint\t\t\tlen1,\n" ++
      "\t\t\t\tlen2,\n" ++
      "\t\t\t\tlen;\n" ++
      "\tchar\t   *ptr;\n" ++
      "\n" ++
      "\tlen1 = VARSIZE_ANY_EXHDR(t1);\n" ++
      "\tlen2 = VARSIZE_ANY_EXHDR(t2);\n" ++
      "\n" ++
      "\t/* paranoia ... probably should throw error instead? */\n" ++
      "\tif (len1 < 0)\n" ++
      "\t\tlen1 = 0;\n" ++
      "\tif (len2 < 0)\n" ++
      "\t\tlen2 = 0;\n" ++
      "\n" ++
      "\tlen = len1 + len2 + VARHDRSZ;\n" ++
      "\tresult = (bytea *) palloc(len);\n" ++
      "\n" ++
      "\t/* Set size of result string... */\n" ++
      "\tSET_VARSIZE(result, len);\n" ++
      "\n" ++
      "\t/* Fill data field of result string... */\n" ++
      "\tptr = VARDATA(result);\n" ++
      "\tif (len1 > 0)\n" ++
      "\t\tmemcpy(ptr, VARDATA_ANY(t1), len1);\n" ++
      "\tif (len2 > 0)\n" ++
      "\t\tmemcpy(ptr + len1, VARDATA_ANY(t2), len2);\n" ++
      "\n" ++
      "\treturn result;\n" ++
      "}\n")
  | _ => none

def renderCFmgrStub (fam : ByteaFamily) : String :=
  let body :=
    match fam.body with
    | .catenate =>
        "\tbytea\t   *t1 = PG_GETARG_BYTEA_PP(0);\n" ++
        "\tbytea\t   *t2 = PG_GETARG_BYTEA_PP(1);\n" ++
        "\n" ++
        "\tPG_RETURN_BYTEA_P(bytea_catenate(t1, t2));\n"
    | .octetLen =>
        "\tDatum\t\tstr = PG_GETARG_DATUM(0);\n" ++
        "\n" ++
        "\t/* We need not detoast the input at all */\n" ++
        "\tPG_RETURN_INT32(toast_raw_datum_size(str) - VARHDRSZ);\n"
    | .eq =>
        "\tDatum\t\targ1 = PG_GETARG_DATUM(0);\n" ++
        "\tDatum\t\targ2 = PG_GETARG_DATUM(1);\n" ++
        "\tbool\t\tresult;\n" ++
        "\tSize\t\tlen1,\n" ++
        "\t\t\t\tlen2;\n" ++
        "\n" ++
        "\t/*\n" ++
        "\t * We can use a fast path for unequal lengths, which might save us from\n" ++
        "\t * having to detoast one or both values.\n" ++
        "\t */\n" ++
        "\tlen1 = toast_raw_datum_size(arg1);\n" ++
        "\tlen2 = toast_raw_datum_size(arg2);\n" ++
        "\tif (len1 != len2)\n" ++
        "\t\tresult = false;\n" ++
        "\telse\n" ++
        "\t{\n" ++
        "\t\tbytea\t   *barg1 = DatumGetByteaPP(arg1);\n" ++
        "\t\tbytea\t   *barg2 = DatumGetByteaPP(arg2);\n" ++
        "\n" ++
        "\t\tresult = (memcmp(VARDATA_ANY(barg1), VARDATA_ANY(barg2),\n" ++
        "\t\t\t\t\t\t len1 - VARHDRSZ) == 0);\n" ++
        "\n" ++
        "\t\tPG_FREE_IF_COPY(barg1, 0);\n" ++
        "\t\tPG_FREE_IF_COPY(barg2, 1);\n" ++
        "\t}\n" ++
        "\n" ++
        "\tPG_RETURN_BOOL(result);\n"
  "Datum\n" ++
  fam.fnName ++ "(PG_FUNCTION_ARGS)\n" ++
  "{\n" ++
  body ++
  "}\n"

def cSource : String :=
  let header :=
    "/*\n" ++
    " * Generated by `rules_postgres/lean/Pg/Ir/Emit/ByteaC.lean`.\n" ++
    " * DO NOT EDIT BY HAND.\n" ++
    " */\n" ++
    "\n" ++
    "#include \"postgres.h\"\n" ++
    "#include <string.h>\n" ++
    "#include \"varatt.h\"\n" ++         -- VARDATA_ANY / VARSIZE_ANY macros
    "#include \"access/detoast.h\"\n" ++  -- toast_raw_datum_size prototype
    "#include \"utils/fmgrprotos.h\"\n" ++
    "#include \"utils/varlena.h\"\n"
  Id.run do
    let mut s := header
    for fam in families do
      match renderCInternal fam with
      | some internal => s := s ++ "\n" ++ internal ++ "\n" ++ renderCFmgrStub fam
      | none          => s := s ++ "\n" ++ renderCFmgrStub fam
    return s

end Pg.Ir.Emit.Bytea.C

def main : IO Unit := IO.print Pg.Ir.Emit.Bytea.C.cSource
