import Pg.Ir.Types
import Pg.Ir.Datum
import Pg.Ir.Emit.Common
import Pg.Ir.Emit.CashArithCommon

/-!
# Pg.Ir.Emit.CashArith — codegen the cash-arithmetic V1 fmgr cluster
as Rust source.

Sister to `Pg.Ir.Emit.IntArith`. Cash is typedef'd as `int64` in Postgres.
v1 covers 6 functions:
  - cash_pl, cash_mi: overflow-checked add/sub of two cash values
  - cash_mul_int4: overflow-checked multiply cash by int4
  - cash_div_int4: divide cash by int4 with zero-check
  - cashlarger, cashsmaller: compare and return max/min (no overflow)

The canonical body shape (cash_pl, cash_mi, cash_mul_int4):

```rust
#[no_mangle]
pub unsafe extern "C" fn cash_pl(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_i64(f.args[0].value);
    let arg2 = decode_i64(f.args[1].value);
    let mut result: i64 = 0;
    if pg_add_s64_overflow(arg1, arg2, &mut result) {
        pg_ereport_numeric_value_out_of_range();
        return 0;
    }
    encode_i64(result)
}
```

For cashlarger/cashsmaller:

```rust
#[no_mangle]
pub unsafe extern "C" fn cashlarger(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let c1 = decode_i64(f.args[0].value);
    let c2 = decode_i64(f.args[1].value);
    let result = if c1 > c2 { c1 } else { c2 };
    encode_i64(result)
}
```

For cash_div_int4:

```rust
#[no_mangle]
pub unsafe extern "C" fn cash_div_int4(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let c = decode_i64(f.args[0].value);
    let i = decode_i32(f.args[1].value);
    if i == 0 {
        pg_ereport_division_by_zero();
        return 0;
    }
    encode_i64(c / (i as i64))
}
```
-/

namespace Pg.Ir.Emit.CashArith

open Pg.Ir.Emit.CashArith (CashOp BodyShape CashFamily families)

/-- Render the first operand expression — either bare `arg1` or
`arg1 as i64`. Cast is needed exactly when the family has a
non-empty `rustCast1`. -/
def operand1Expr (fam : CashFamily) : String :=
  if fam.rustCast1 == "" then "arg1"
  else "arg1 as i64"

def operand2Expr (fam : CashFamily) : String :=
  if fam.rustCast2 == "" then "arg2"
  else "arg2 as i64"

/-- Render overflow primitive call for add/sub/mul. -/
def overflowPrim (op : CashOp) : String :=
  "pg_" ++ op.primitive ++ "_s64_overflow"

/-- Render the Rust body for overflow-checked operations (add/sub/mul). -/
def renderBodyOverflow (fam : CashFamily) : String :=
  let decoder2 := fam.decoder2
  let op1 := operand1Expr fam
  let op2 := operand2Expr fam
  let prim := overflowPrim fam.op
  "    let f = &mut *fcinfo;\n" ++
  "    let arg1 = decode_i64(f.args[0].value);\n" ++
  "    let arg2 = " ++ decoder2 ++ "(f.args[1].value);\n" ++
  "    let mut result: i64 = 0;\n" ++
  "    if " ++ prim ++ "(" ++ op1 ++ ", " ++ op2 ++ ", &mut result) {\n" ++
  "        pg_ereport_numeric_value_out_of_range();\n" ++
  "        return 0;\n" ++
  "    }\n" ++
  "    encode_i64(result)\n"

/-- Render the Rust body for comparison operations (larger/smaller). -/
def renderBodyCompare (fam : CashFamily) : String :=
  let cmp := if fam.fnName == "cashlarger" then ">" else "<"
  "    let f = &mut *fcinfo;\n" ++
  "    let c1 = decode_i64(f.args[0].value);\n" ++
  "    let c2 = decode_i64(f.args[1].value);\n" ++
  "    let result = if c1 " ++ cmp ++ " c2 { c1 } else { c2 };\n" ++
  "    encode_i64(result)\n"

/-- Render the Rust body for division-by-zero check. -/
def renderBodyDivInt (_fam : CashFamily) : String :=
  "    let f = &mut *fcinfo;\n" ++
  "    let c = decode_i64(f.args[0].value);\n" ++
  "    let i = decode_i32(f.args[1].value);\n" ++
  "    if i == 0 {\n" ++
  "        pg_ereport_division_by_zero();\n" ++
  "        return 0;\n" ++
  "    }\n" ++
  "    encode_i64(c / (i as i64))\n"

/-- Render the appropriate body based on body shape. -/
def renderBody (fam : CashFamily) : String :=
  match fam.op.bodyShape with
  | .binaryAddSub => renderBodyOverflow fam
  | .binaryMulInt => renderBodyOverflow fam
  | .binaryCompare => renderBodyCompare fam
  | .binaryDivInt => renderBodyDivInt fam

def renderFn (fam : CashFamily) : String :=
  "#[no_mangle]\n" ++
  "pub unsafe extern \"C\" fn " ++ fam.fnName ++
    "(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {\n" ++
  renderBody fam ++
  "}\n"

/-- The full Rust source. -/
def rustSource : String :=
  let header :=
    "// Generated by `rules_postgres/lean/Pg/Ir/Emit/CashArith.lean`.\n" ++
    "// DO NOT EDIT BY HAND. Regenerate via\n" ++
    "// `rules_postgres/tools/regen/regen-cash-arith.sh`.\n" ++
    "//\n" ++
    "// Cash-arithmetic V1 fmgr cluster: 6 functions =\n" ++
    "// {pl, mi, mul_int4, div_int4} × {cash} (4 ops) +\n" ++
    "// {larger, smaller} × {cash} (2 compare ops).\n" ++
    "//\n" ++
    "// Each body decodes operand(s), performs the operation\n" ++
    "// (overflow-checked for pl/mi/mul_int4, zero-checked for div_int4,\n" ++
    "// simple comparison for larger/smaller), and returns the Cash result.\n" ++
    "// On overflow/division-by-zero, signals via the corresponding\n" ++
    "// pg_ereport_* helper + returns Datum 0. This mirrors Postgres'\n" ++
    "// ereport(ERROR, ...) path: the diff-test harness checks the\n" ++
    "// (out, err) tuple round-trips against the vendored C oracle.\n" ++
    "\n" ++
    "#![allow(clippy::missing_safety_doc)]\n" ++
    "\n" ++
    "use pg_fcinfo::{\n" ++
    "    decode_i32, decode_i64,\n" ++
    "    encode_i64,\n" ++
    "    pg_add_s64_overflow, pg_sub_s64_overflow, pg_mul_s64_overflow,\n" ++
    "    pg_ereport_numeric_value_out_of_range, pg_ereport_division_by_zero,\n" ++
    "    FunctionCallInfoBaseData,\n" ++
    "};\n"
  Id.run do
    let mut s := header
    for fam in families do
      s := s ++ "\n" ++ renderFn fam
    return s

end Pg.Ir.Emit.CashArith

def main : IO Unit := IO.print Pg.Ir.Emit.CashArith.rustSource
