import Pg.Ir.Emit.DateArithCommon

/-!
# Pg.Ir.Emit.DateArithC — codegen real-style Postgres C source for the
date-arithmetic V1 fmgr cluster.

Sister to `Pg.Ir.Emit.DateArith` (which emits Rust). Body shapes follow
Postgres' real source (`date.c`) to enable AST-diff grounding.

Body shapes are three distinct functions:

1. `date_pli` (date + int32 → date):
```
Datum
date_pli(PG_FUNCTION_ARGS)
{
    DateADT        dateVal = PG_GETARG_DATEADT(0);
    int32          days = PG_GETARG_INT32(1);
    DateADT        result;

    if (DATE_NOT_FINITE(dateVal))
        PG_RETURN_DATEADT(dateVal);

    result = dateVal + days;

    if ((days >= 0 ? (result < dateVal) : (result > dateVal)) ||
        !IS_VALID_DATE(result))
        ereport(ERROR,
                (errcode(ERRCODE_DATETIME_VALUE_OUT_OF_RANGE),
                 errmsg("date out of range")));

    PG_RETURN_DATEADT(result);
}
```

2. `date_mii` (date - int32 → date):
```
Datum
date_mii(PG_FUNCTION_ARGS)
{
    DateADT        dateVal = PG_GETARG_DATEADT(0);
    int32          days = PG_GETARG_INT32(1);
    DateADT        result;

    if (DATE_NOT_FINITE(dateVal))
        PG_RETURN_DATEADT(dateVal);

    result = dateVal - days;

    if ((days >= 0 ? (result > dateVal) : (result < dateVal)) ||
        !IS_VALID_DATE(result))
        ereport(ERROR,
                (errcode(ERRCODE_DATETIME_VALUE_OUT_OF_RANGE),
                 errmsg("date out of range")));

    PG_RETURN_DATEADT(result);
}
```

3. `date_mi` (date - date → int32):
```
Datum
date_mi(PG_FUNCTION_ARGS)
{
    DateADT        dateVal1 = PG_GETARG_DATEADT(0);
    DateADT        dateVal2 = PG_GETARG_DATEADT(1);

    if (DATE_NOT_FINITE(dateVal1) || DATE_NOT_FINITE(dateVal2))
        ereport(ERROR,
                (errcode(ERRCODE_DATETIME_VALUE_OUT_OF_RANGE),
                 errmsg("cannot subtract infinite dates")));

    PG_RETURN_INT32((int32) (dateVal1 - dateVal2));
}
```
-/

namespace Pg.Ir.Emit.DateArithC

open Pg.Ir.Emit.DateArith (DateOp ops)

def renderCPliBody : String :=
  "\tDateADT\t\tdateVal = PG_GETARG_DATEADT(0);\n" ++
  "\tint32\t\tdays = PG_GETARG_INT32(1);\n" ++
  "\tDateADT\t\tresult;\n\n" ++
  "\tif (DATE_NOT_FINITE(dateVal))\n" ++
  "\t\tPG_RETURN_DATEADT(dateVal); /* can't change infinity */\n\n" ++
  "\tresult = dateVal + days;\n\n" ++
  "\t/* Check for integer overflow and out-of-allowed-range */\n" ++
  "\tif ((days >= 0 ? (result < dateVal) : (result > dateVal)) ||\n" ++
  "\t\t!IS_VALID_DATE(result))\n" ++
  "\t\tereport(ERROR,\n" ++
  "\t\t\t\t(errcode(ERRCODE_DATETIME_VALUE_OUT_OF_RANGE),\n" ++
  "\t\t\t\t errmsg(\"date out of range\")));\n\n" ++
  "\tPG_RETURN_DATEADT(result);\n"

def renderCMiiBody : String :=
  "\tDateADT\t\tdateVal = PG_GETARG_DATEADT(0);\n" ++
  "\tint32\t\tdays = PG_GETARG_INT32(1);\n" ++
  "\tDateADT\t\tresult;\n\n" ++
  "\tif (DATE_NOT_FINITE(dateVal))\n" ++
  "\t\tPG_RETURN_DATEADT(dateVal); /* can't change infinity */\n\n" ++
  "\tresult = dateVal - days;\n\n" ++
  "\t/* Check for integer overflow and out-of-allowed-range */\n" ++
  "\tif ((days >= 0 ? (result > dateVal) : (result < dateVal)) ||\n" ++
  "\t\t!IS_VALID_DATE(result))\n" ++
  "\t\tereport(ERROR,\n" ++
  "\t\t\t\t(errcode(ERRCODE_DATETIME_VALUE_OUT_OF_RANGE),\n" ++
  "\t\t\t\t errmsg(\"date out of range\")));\n\n" ++
  "\tPG_RETURN_DATEADT(result);\n"

def renderCMiBody : String :=
  "\tDateADT\t\tdateVal1 = PG_GETARG_DATEADT(0);\n" ++
  "\tDateADT\t\tdateVal2 = PG_GETARG_DATEADT(1);\n\n" ++
  "\tif (DATE_NOT_FINITE(dateVal1) || DATE_NOT_FINITE(dateVal2))\n" ++
  "\t\tereport(ERROR,\n" ++
  "\t\t\t\t(errcode(ERRCODE_DATETIME_VALUE_OUT_OF_RANGE),\n" ++
  "\t\t\t\t errmsg(\"cannot subtract infinite dates\")));\n\n" ++
  "\tPG_RETURN_INT32((int32) (dateVal1 - dateVal2));\n"

def renderCFn (op : DateOp) : String :=
  let body := match op with
    | .pli => renderCPliBody
    | .mii => renderCMiiBody
    | .mi  => renderCMiBody
  "Datum\n" ++
  "date_" ++ op.suffix ++ "(PG_FUNCTION_ARGS)\n" ++
  "{\n" ++
  body ++
  "}\n"

def cSource : String :=
  let header :=
    "/*\n" ++
    " * Generated by `rules_postgres/lean/Pg/Ir/Emit/DateArithC.lean`.\n" ++
    " * DO NOT EDIT BY HAND. Regenerate via\n" ++
    " * `rules_postgres/tools/regen/check-date-arith-grounding.sh`.\n" ++
    " *\n" ++
    " * This file exists to be `clang -ast-dump=json`-ed alongside\n" ++
    " * real `src/backend/utils/adt/date.c` and structurally diffed\n" ++
    " * function-by-function. A passing diff means the Lean spec\n" ++
    " * captures the same algorithm Postgres wrote.\n" ++
    " */\n" ++
    "\n" ++
    "#include \"postgres.h\"\n" ++
    "#include <ctype.h>\n" ++
    "#include <limits.h>\n" ++
    "#include <float.h>\n" ++
    "#include <math.h>\n" ++
    "#include <time.h>\n" ++
    "#include \"access/xact.h\"\n" ++
    "#include \"catalog/pg_type.h\"\n" ++
    "#include \"common/hashfn.h\"\n" ++
    "#include \"common/int.h\"\n" ++
    "#include \"libpq/pqformat.h\"\n" ++
    "#include \"miscadmin.h\"\n" ++
    "#include \"nodes/supportnodes.h\"\n" ++
    "#include \"fmgr.h\"\n" ++
    "#include \"utils/fmgrprotos.h\"\n" ++
    "#include \"utils/date.h\"\n"
  Id.run do
    let mut s := header
    for op in ops do
      s := s ++ "\n" ++ renderCFn op
    return s

end Pg.Ir.Emit.DateArithC

def main : IO Unit := IO.print Pg.Ir.Emit.DateArithC.cSource
