import Pg.Ir.Types
import Pg.Ir.Datum
import Pg.Ir.Emit.Common
import Pg.Ir.Emit.DateArithCommon

/-!
# Pg.Ir.Emit.DateArith — codegen the date-arithmetic V1 fmgr cluster as
Rust source.

3 functions:
- `date_pli` (date + int → date) — wraps addition with infinity check + range
  validation.
- `date_mii` (date - int → date) — wraps subtraction with infinity check +
  range validation.
- `date_mi` (date - date → int) — returns elapsed days; raises on infinite
  operands.

Each body:
1. Decodes the operands (DateADT = int32).
2. Checks DATE_NOT_FINITE for infinity sentinels.
3. For pli/mii: checks for wraparound by comparing sign flips, then validates
   the result with IS_VALID_DATE.
4. For mi: no overflow check needed (subtraction of two int32s always fits in
   int32); just checks that neither operand is infinite.
5. On error, calls pg_ereport_datetime_value_out_of_range and returns 0.

Attribution: function bodies are PostgreSQL Global Development Group, released
under the PostgreSQL License (BSD-style).
-/

namespace Pg.Ir.Emit.DateArith

/-- Render the `date_pli` (date + int → date) body in Rust. -/
def renderPliBody : String :=
  "    let f = &mut *fcinfo;\n" ++
  "    let date_val = decode_i32(f.args[0].value);\n" ++
  "    let days = decode_i32(f.args[1].value);\n" ++
  "\n" ++
  "    if is_date_not_finite(date_val) {\n" ++
  "        return encode_i32(date_val);\n" ++
  "    }\n" ++
  "\n" ++
  "    let result = date_val.wrapping_add(days);\n" ++
  "\n" ++
  "    /* Check for integer overflow by sign flip and validate date range. */\n" ++
  "    let overflow = if days >= 0 {\n" ++
  "        result < date_val\n" ++
  "    } else {\n" ++
  "        result > date_val\n" ++
  "    };\n" ++
  "\n" ++
  "    if overflow || !is_valid_date(result) {\n" ++
  "        pg_ereport_datetime_value_out_of_range();\n" ++
  "        return 0;\n" ++
  "    }\n" ++
  "\n" ++
  "    encode_i32(result)\n"

/-- Render the `date_mii` (date - int → date) body in Rust. -/
def renderMiiBody : String :=
  "    let f = &mut *fcinfo;\n" ++
  "    let date_val = decode_i32(f.args[0].value);\n" ++
  "    let days = decode_i32(f.args[1].value);\n" ++
  "\n" ++
  "    if is_date_not_finite(date_val) {\n" ++
  "        return encode_i32(date_val);\n" ++
  "    }\n" ++
  "\n" ++
  "    let result = date_val.wrapping_sub(days);\n" ++
  "\n" ++
  "    /* Check for integer overflow by sign flip and validate date range. */\n" ++
  "    let overflow = if days >= 0 {\n" ++
  "        result > date_val\n" ++
  "    } else {\n" ++
  "        result < date_val\n" ++
  "    };\n" ++
  "\n" ++
  "    if overflow || !is_valid_date(result) {\n" ++
  "        pg_ereport_datetime_value_out_of_range();\n" ++
  "        return 0;\n" ++
  "    }\n" ++
  "\n" ++
  "    encode_i32(result)\n"

/-- Render the `date_mi` (date - date → int) body in Rust. -/
def renderMiBody : String :=
  "    let f = &mut *fcinfo;\n" ++
  "    let date_val1 = decode_i32(f.args[0].value);\n" ++
  "    let date_val2 = decode_i32(f.args[1].value);\n" ++
  "\n" ++
  "    if is_date_not_finite(date_val1) || is_date_not_finite(date_val2) {\n" ++
  "        pg_ereport_datetime_value_out_of_range();\n" ++
  "        return 0;\n" ++
  "    }\n" ++
  "\n" ++
  "    encode_i32(date_val1 - date_val2)\n"

def renderFn (op : DateOp) : String :=
  let body := match op with
    | .pli => renderPliBody
    | .mii => renderMiiBody
    | .mi  => renderMiBody
  "#[no_mangle]\n" ++
  "pub unsafe extern \"C\" fn date_" ++ op.suffix ++
    "(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {\n" ++
  body ++
  "}\n"

/-- The full Rust source. -/
def rustSource : String :=
  let header :=
    "// Generated by `rules_postgres/lean/Pg/Ir/Emit/DateArith.lean`.\n" ++
    "// DO NOT EDIT BY HAND. Regenerate via\n" ++
    "// `rules_postgres/tools/regen/regen-date-arith.sh`.\n" ++
    "//\n" ++
    "// Date-arithmetic V1 fmgr cluster: 3 functions:\n" ++
    "// - date_pli (date + int32 → date): wraps addition, checks for overflow\n" ++
    "//   and valid date range.\n" ++
    "// - date_mii (date - int32 → date): wraps subtraction, checks for\n" ++
    "//   overflow and valid date range.\n" ++
    "// - date_mi (date - date → int32): returns elapsed days; rejects\n" ++
    "//   infinite operands.\n" ++
    "//\n" ++
    "// Each body decodes operands, checks DATE_NOT_FINITE (Int32::MIN and\n" ++
    "// Int32::MAX sentinels), and on pli/mii checks IS_VALID_DATE. On error\n" ++
    "// signals via pg_ereport_datetime_value_out_of_range() + returning\n" ++
    "// Datum 0, mirroring Postgres' ereport(ERROR, ...) path.\n" ++
    "//\n" ++
    "// Attribution: function bodies are PostgreSQL Global Development Group,\n" ++
    "// released under the PostgreSQL License (BSD-style).\n" ++
    "\n" ++
    "#![allow(clippy::missing_safety_doc)]\n" ++
    "\n" ++
    "use pg_fcinfo::{\n" ++
    "    decode_i32, encode_i32,\n" ++
    "    pg_ereport_datetime_value_out_of_range, FunctionCallInfoBaseData,\n" ++
    "};\n" ++
    "\n" ++
    "/* Date sentinels: DATEVAL_NOBEGIN = i32::MIN, DATEVAL_NOEND = i32::MAX */\n" ++
    "#[inline]\n" ++
    "fn is_date_not_finite(d: i32) -> bool {\n" ++
    "    d == i32::MIN || d == i32::MAX\n" ++
    "}\n" ++
    "\n" ++
    "/* Valid date range: Unix epoch is day 0; Postgres uses days around\n" ++
    " * 1970-01-01 ± ~178 million years. Finite dates must not be sentinels.\n" ++
    " */\n" ++
    "#[inline]\n" ++
    "fn is_valid_date(d: i32) -> bool {\n" ++
    "    d != i32::MIN && d != i32::MAX\n" ++
    "}\n"
  Id.run do
    let mut s := header
    for op in ops do
      s := s ++ "\n" ++ renderFn op
    return s

end Pg.Ir.Emit.DateArith

def main : IO Unit := IO.print Pg.Ir.Emit.DateArith.rustSource
