import Pg.Ir.Emit.FloatArithCommon

/-!
# Pg.Ir.Emit.FloatArithC — emit real-style Postgres C for the float arithmetic
cluster (AST grounding companion to FloatArith.lean).

Bodies match real Postgres source structure byte-equivalent (modulo
whitespace clang normalizes) so the per-function AST diff is clean.
-/

namespace Pg.Ir.Emit.FloatArith.C

open Pg.Ir.Emit.FloatArith (ArithBody ArithFamily families)

def helperFn (fam : ArithFamily) : String :=
  match fam.body with
  | .plWithCheck => "float4_pl"
  | .miWithCheck => "float4_mi"
  | .mulWithCheck => "float4_mul"
  | .divWithCheck => "float4_div"

def renderCBody (fam : ArithFamily) : String :=
  let fnSuffix := if fam.cWidth == "float4" then "4" else "8"
  let helper :=
    match fam.body with
    | .plWithCheck => "float" ++ fnSuffix ++ "_pl"
    | .miWithCheck => "float" ++ fnSuffix ++ "_mi"
    | .mulWithCheck => "float" ++ fnSuffix ++ "_mul"
    | .divWithCheck => "float" ++ fnSuffix ++ "_div"
  "\t" ++ fam.cWidth ++ "\t\targ1 = " ++ fam.pgGetArg ++ "(0);\n" ++
  "\t" ++ fam.cWidth ++ "\t\targ2 = " ++ fam.pgGetArg ++ "(1);\n\n" ++
  "\t" ++ fam.pgReturn ++ "(" ++ helper ++ "(arg1, arg2));\n"

def renderCFn (fam : ArithFamily) : String :=
  "Datum\n" ++
  fam.fnName ++ "(PG_FUNCTION_ARGS)\n" ++
  "{\n" ++
  renderCBody fam ++
  "}\n"

def cSource : String :=
  let header :=
    "/*\n" ++
    " * Generated by `rules_postgres/lean/Pg/Ir/Emit/FloatArithC.lean`.\n" ++
    " * DO NOT EDIT BY HAND. Regenerate via\n" ++
    " * `rules_postgres/tools/regen/check-float-arith-grounding.sh`.\n" ++
    " *\n" ++
    " * This file exists to be `clang -ast-dump=json`-ed alongside\n" ++
    " * real `src/backend/utils/adt/float.c` and structurally\n" ++
    " * diffed function-by-function. A passing diff means the Lean spec\n" ++
    " * captures the same algorithm Postgres wrote.\n" ++
    " */\n" ++
    "\n" ++
    "#include \"postgres.h\"\n" ++
    "#include <math.h>\n" ++
    "#include \"utils/float.h\"\n" ++
    "#include \"utils/fmgrprotos.h\"\n"
  Id.run do
    let mut s := header
    for fam in families do
      s := s ++ "\n" ++ renderCFn fam
    return s

end Pg.Ir.Emit.FloatArith.C

def main : IO Unit := IO.print Pg.Ir.Emit.FloatArith.C.cSource
