import Pg.Ir.Emit.FloatArithCommon

/-!
# Pg.Ir.Emit.FloatArith — Rust emit for the float arithmetic V1 fmgr cluster.
-/

namespace Pg.Ir.Emit.FloatArith.Rust

open Pg.Ir.Emit.FloatArith (ArithBody ArithFamily families)

def renderBody (fam : ArithFamily) : String :=
  let prelude :=
    "    let f = &mut *fcinfo;\n" ++
    "    let arg1 = " ++ fam.decoder ++ "(f.args[0].value);\n" ++
    "    let arg2 = " ++ fam.decoder ++ "(f.args[1].value);\n"
  match fam.body with
  | .plWithCheck =>
      prelude ++
      "    let result: " ++ fam.rustTy ++ " = arg1 + arg2;\n" ++
      "    if result.is_infinite() && !arg1.is_infinite() && !arg2.is_infinite() {\n" ++
      "        pg_ereport_numeric_value_out_of_range();\n" ++
      "        return 0;\n" ++
      "    }\n" ++
      "    " ++ fam.encoder ++ "(result)\n"
  | .miWithCheck =>
      prelude ++
      "    let result: " ++ fam.rustTy ++ " = arg1 - arg2;\n" ++
      "    if result.is_infinite() && !arg1.is_infinite() && !arg2.is_infinite() {\n" ++
      "        pg_ereport_numeric_value_out_of_range();\n" ++
      "        return 0;\n" ++
      "    }\n" ++
      "    " ++ fam.encoder ++ "(result)\n"
  | .mulWithCheck =>
      prelude ++
      "    let result: " ++ fam.rustTy ++ " = arg1 * arg2;\n" ++
      "    if result.is_infinite() && !arg1.is_infinite() && !arg2.is_infinite() {\n" ++
      "        pg_ereport_numeric_value_out_of_range();\n" ++
      "        return 0;\n" ++
      "    }\n" ++
      "    if result == 0.0 && arg1 != 0.0 && arg2 != 0.0 {\n" ++
      "        pg_ereport_numeric_value_out_of_range();\n" ++
      "        return 0;\n" ++
      "    }\n" ++
      "    " ++ fam.encoder ++ "(result)\n"
  | .divWithCheck =>
      prelude ++
      "    if arg2 == 0.0 && !arg1.is_nan() {\n" ++
      "        pg_ereport_division_by_zero();\n" ++
      "        return 0;\n" ++
      "    }\n" ++
      "    let result: " ++ fam.rustTy ++ " = arg1 / arg2;\n" ++
      "    if result.is_infinite() && !arg1.is_infinite() {\n" ++
      "        pg_ereport_numeric_value_out_of_range();\n" ++
      "        return 0;\n" ++
      "    }\n" ++
      "    if result == 0.0 && arg1 != 0.0 && !arg2.is_infinite() {\n" ++
      "        pg_ereport_numeric_value_out_of_range();\n" ++
      "        return 0;\n" ++
      "    }\n" ++
      "    " ++ fam.encoder ++ "(result)\n"

def renderFn (fam : ArithFamily) : String :=
  "#[no_mangle]\n" ++
  "pub unsafe extern \"C\" fn " ++ fam.fnName ++
    "(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {\n" ++
  renderBody fam ++
  "}\n"

def rustSource : String :=
  let header :=
    "// Generated by `rules_postgres/lean/Pg/Ir/Emit/FloatArith.lean`.\n" ++
    "// DO NOT EDIT BY HAND. Regenerate via\n" ++
    "// `rules_postgres/tools/regen/regen-float-arith.sh`.\n" ++
    "//\n" ++
    "// Float arithmetic V1 fmgr cluster: 8 functions = {pl, mi, mul, div} × {float4, float8}.\n" ++
    "// Each body decodes two arguments, applies IEEE-754 arithmetic, and checks\n" ++
    "// for overflow/underflow conditions matching Postgres' float.h helpers:\n" ++
    "//   - pl/mi: check overflow (result inf but neither input inf)\n" ++
    "//   - mul: check overflow AND underflow (result 0 but neither input 0)\n" ++
    "//   - div: divide-by-zero first, then overflow/underflow checks\n" ++
    "\n" ++
    "#![allow(clippy::missing_safety_doc)]\n" ++
    "\n" ++
    "use pg_fcinfo::{\n" ++
    "    decode_f32, decode_f64,\n" ++
    "    encode_f32, encode_f64,\n" ++
    "    pg_ereport_numeric_value_out_of_range,\n" ++
    "    pg_ereport_division_by_zero,\n" ++
    "    FunctionCallInfoBaseData,\n" ++
    "};\n"
  Id.run do
    let mut s := header
    for fam in families do
      s := s ++ "\n" ++ renderFn fam
    return s

end Pg.Ir.Emit.FloatArith.Rust

def main : IO Unit := IO.print Pg.Ir.Emit.FloatArith.Rust.rustSource
