import Pg.Ir.Emit.FloatUnaryCommon

/-!
# Pg.Ir.Emit.FloatUnaryC — emit real-style Postgres C for the float unary
cluster (AST grounding companion to FloatUnary.lean).

Bodies match real Postgres source structure byte-equivalent (modulo
whitespace clang normalizes) so the per-function AST diff is clean.
-/

namespace Pg.Ir.Emit.FloatUnary.C

open Pg.Ir.Emit.FloatUnary (UnaryBody UnaryFamily families)

def renderCBody (fam : UnaryFamily) : String :=
  match fam.body with
  | .absFlat =>
      "\t" ++ fam.cWidth ++ "\t\targ1 = " ++ fam.pgGetArg ++ "(0);\n" ++
      "\n" ++
      "\t" ++ fam.pgReturn ++ "(" ++ fam.cAbsFunc ++ "(arg1));\n"
  | .umWithResult =>
      "\t" ++ fam.cWidth ++ "\t\targ1 = " ++ fam.pgGetArg ++ "(0);\n" ++
      "\t" ++ fam.cWidth ++ "\t\tresult;\n" ++
      "\n" ++
      "\tresult = -arg1;\n" ++
      "\t" ++ fam.pgReturn ++ "(result);\n"

def renderCFn (fam : UnaryFamily) : String :=
  "Datum\n" ++
  fam.fnName ++ "(PG_FUNCTION_ARGS)\n" ++
  "{\n" ++
  renderCBody fam ++
  "}\n"

def cSource : String :=
  let header :=
    "/*\n" ++
    " * Generated by `rules_postgres/lean/Pg/Ir/Emit/FloatUnaryC.lean`.\n" ++
    " * DO NOT EDIT BY HAND. Regenerate via\n" ++
    " * `rules_postgres/tools/regen/check-float-unary-grounding.sh`.\n" ++
    " */\n" ++
    "\n" ++
    "#include \"postgres.h\"\n" ++
    "#include <math.h>\n" ++
    "#include \"utils/fmgrprotos.h\"\n"
  Id.run do
    let mut s := header
    for fam in families do
      s := s ++ "\n" ++ renderCFn fam
    return s

end Pg.Ir.Emit.FloatUnary.C

def main : IO Unit := IO.print Pg.Ir.Emit.FloatUnary.C.cSource
