import Pg.Ir.Emit.FloatUnaryCommon

/-!
# Pg.Ir.Emit.FloatUnary — Rust emit for the float unary V1 fmgr cluster.
-/

namespace Pg.Ir.Emit.FloatUnary.Rust

open Pg.Ir.Emit.FloatUnary (UnaryBody UnaryFamily families)

def renderBody (fam : UnaryFamily) : String :=
  let prelude :=
    "    let f = &mut *fcinfo;\n" ++
    "    let arg = " ++ fam.decoder ++ "(f.args[0].value);\n"
  match fam.body with
  | .absFlat =>
      prelude ++ "    " ++ fam.encoder ++ "(arg.abs())\n"
  | .umWithResult =>
      prelude ++
      "    let result: " ++ fam.rustTy ++ " = -arg;\n" ++
      "    " ++ fam.encoder ++ "(result)\n"

def renderFn (fam : UnaryFamily) : String :=
  "#[no_mangle]\n" ++
  "pub unsafe extern \"C\" fn " ++ fam.fnName ++
    "(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {\n" ++
  renderBody fam ++
  "}\n"

def rustSource : String :=
  let header :=
    "// Generated by `rules_postgres/lean/Pg/Ir/Emit/FloatUnary.lean`.\n" ++
    "// DO NOT EDIT BY HAND. Regenerate via\n" ++
    "// `rules_postgres/tools/regen/regen-float-unary.sh`.\n" ++
    "//\n" ++
    "// Float unary V1 fmgr cluster: 4 functions = {um, abs} × {float4, float8}.\n" ++
    "// Each body decodes the single argument, applies the operation (abs via\n" ++
    "// f32::abs()/f64::abs(), um via negation), and encodes the result.\n" ++
    "// No ereport or special NaN handling — standard IEEE-754 semantics.\n" ++
    "\n" ++
    "#![allow(clippy::missing_safety_doc)]\n" ++
    "\n" ++
    "use pg_fcinfo::{\n" ++
    "    decode_f32, decode_f64,\n" ++
    "    encode_f32, encode_f64,\n" ++
    "    FunctionCallInfoBaseData,\n" ++
    "};\n"
  Id.run do
    let mut s := header
    for fam in families do
      s := s ++ "\n" ++ renderFn fam
    return s

end Pg.Ir.Emit.FloatUnary.Rust

def main : IO Unit := IO.print Pg.Ir.Emit.FloatUnary.Rust.rustSource
