import Pg.Ir.Emit.FloatToIntCommon

/-!
# Pg.Ir.Emit.FloatToIntC — emit real-style Postgres C for the float-to-int
cast cluster (AST grounding companion to FloatToInt.lean).

Bodies match real Postgres source structure byte-equivalent (modulo
whitespace clang normalizes) so the per-function AST diff is clean.
-/

namespace Pg.Ir.Emit.FloatToInt.C

open Pg.Ir.Emit.FloatToInt (CastBody CastFamily families)

def renderCBody (fam : CastFamily) : String :=
  "\t" ++ fam.cFloatWidth ++ "\t\tnum = " ++ fam.pgGetArg ++ "(0);\n\n" ++
  "\t/*\n" ++
  "\t * Get rid of any fractional part in the input.  This is so we don't fail\n" ++
  "\t * on just-out-of-range values that would round into range.  Note\n" ++
  "\t * assumption that rint() will pass through a NaN or Inf unchanged.\n" ++
  "\t */\n" ++
  "\tnum = rint(num);\n\n" ++
  "\t/* Range check */\n" ++
  match fam.body with
  | .toInt16 =>
      "\tif (unlikely(isnan(num) || !FLOAT" ++
      (if fam.cCheckSuffix == "f" then "4" else "8") ++
      "_FITS_IN_INT16(num)))\n" ++
      "\t\tereport(ERROR,\n" ++
      "\t\t\t(errcode(ERRCODE_NUMERIC_VALUE_OUT_OF_RANGE),\n" ++
      "\t\t\t errmsg(\"" ++ fam.errWord ++ " out of range\")));\n\n" ++
      "\t" ++ fam.pgReturn ++ "((" ++ fam.cIntWidth ++ ") num);\n"
  | .toInt32 =>
      "\tif (unlikely(isnan(num) || !FLOAT" ++
      (if fam.cCheckSuffix == "f" then "4" else "8") ++
      "_FITS_IN_INT32(num)))\n" ++
      "\t\tereport(ERROR,\n" ++
      "\t\t\t(errcode(ERRCODE_NUMERIC_VALUE_OUT_OF_RANGE),\n" ++
      "\t\t\t errmsg(\"" ++ fam.errWord ++ " out of range\")));\n\n" ++
      "\t" ++ fam.pgReturn ++ "((" ++ fam.cIntWidth ++ ") num);\n"

def renderCFn (fam : CastFamily) : String :=
  "Datum\n" ++
  fam.fnName ++ "(PG_FUNCTION_ARGS)\n" ++
  "{\n" ++
  renderCBody fam ++
  "}\n"

def cSource : String :=
  let header :=
    "/*\n" ++
    " * Generated by `rules_postgres/lean/Pg/Ir/Emit/FloatToIntC.lean`.\n" ++
    " * DO NOT EDIT BY HAND. Regenerate via\n" ++
    " * `rules_postgres/tools/regen/check-float-to-int-grounding.sh`.\n" ++
    " *\n" ++
    " * This file exists to be `clang -ast-dump=json`-ed alongside\n" ++
    " * real `src/backend/utils/adt/float.c` and structurally\n" ++
    " * diffed function-by-function. A passing diff means the Lean spec\n" ++
    " * captures the same algorithm Postgres wrote.\n" ++
    " */\n" ++
    "\n" ++
    "#include \"postgres.h\"\n" ++
    "#include <math.h>\n" ++
    "#include \"utils/fmgrprotos.h\"\n"
  Id.run do
    let mut s := header
    for fam in families do
      s := s ++ "\n" ++ renderCFn fam
    return s

end Pg.Ir.Emit.FloatToInt.C

def main : IO Unit := IO.print Pg.Ir.Emit.FloatToInt.C.cSource
