import Pg.Ir.Types
import Pg.Ir.Datum
import Pg.Ir.Emit.Common
import Pg.Ir.Emit.IntArithCommon

/-!
# Pg.Ir.Emit.IntArith — codegen the integer-arithmetic V1 fmgr cluster
as Rust source.

Sister to `Pg.Ir.Emit.IntHash`. Same Pg.Ir architecture; different
cluster shape: **two arguments + overflow-checked arithmetic** instead
of hash. v1 covers {pl, mi, mul} × {int2, int4, int8} + 6 cross-type
families — 21 functions total. Division is deferred (different
overflow semantics: INT_MIN / -1 special-case + division-by-zero
errcode).

The canonical body shape (int4pl, by way of the existing hand-written
smoke-test at `translated/pg_int4_arith/src/lib.rs`):

```rust
#[no_mangle]
pub unsafe extern "C" fn int4pl(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_i32(f.args[0].value);
    let arg2 = decode_i32(f.args[1].value);
    let mut result: i32 = 0;
    if pg_add_s32_overflow(arg1, arg2, &mut result) {
        pg_ereport_numeric_value_out_of_range();
        return 0;
    }
    encode_i32(result)
}
```

Cross-type families differ only in (a) which `decode_*` is used per
operand, (b) explicit `as`-cast to the result type before the overflow
primitive, and (c) the overflow primitive width — always equal to the
result type's width (mirrors what real Postgres does in `int.c`/`int8.c`).
-/

namespace Pg.Ir.Emit.IntArith

/-- Build the Rust function name from a family + op. -/
def fnName (fam : ArithFamily) (op : ArithOp) : String :=
  fam.namePrefix ++ op.suffix

/-- The Rust overflow-primitive call: `pg_<add|sub|mul>_s<W>_overflow`. -/
def overflowPrim (fam : ArithFamily) (op : ArithOp) : String :=
  "pg_" ++ op.primitive ++ "_" ++ fam.overflowWidth ++ "_overflow"

/-- Render the first operand expression — either bare `arg1` or
`arg1 as <wider>`. Cast is needed exactly when the family has a
non-empty `rustCast1`. -/
def operand1Expr (fam : ArithFamily) : String :=
  if fam.rustCast1 == "" then "arg1"
  else "arg1 as " ++ fam.rustResultTy

def operand2Expr (fam : ArithFamily) : String :=
  if fam.rustCast2 == "" then "arg2"
  else "arg2 as " ++ fam.rustResultTy

/-- Render the Rust body. -/
def renderBody (fam : ArithFamily) (op : ArithOp) : String :=
  let decoder2 := if fam.decoder2 == "" then fam.decoder1 else fam.decoder2
  let op1 := operand1Expr fam
  let op2 := operand2Expr fam
  "    let f = &mut *fcinfo;\n" ++
  "    let arg1 = " ++ fam.decoder1 ++ "(f.args[0].value);\n" ++
  "    let arg2 = " ++ decoder2     ++ "(f.args[1].value);\n" ++
  "    let mut result: " ++ fam.rustResultTy ++ " = 0;\n" ++
  "    if " ++ overflowPrim fam op ++ "(" ++ op1 ++ ", " ++ op2 ++ ", &mut result) {\n" ++
  "        pg_ereport_numeric_value_out_of_range();\n" ++
  "        return 0;\n" ++
  "    }\n" ++
  "    " ++ fam.rustEncoder ++ "(result)\n"

def renderFn (fam : ArithFamily) (op : ArithOp) : String :=
  "#[no_mangle]\n" ++
  "pub unsafe extern \"C\" fn " ++ fnName fam op ++
    "(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {\n" ++
  renderBody fam op ++
  "}\n"

/-- The full Rust source. -/
def rustSource : String :=
  let header :=
    "// Generated by `rules_postgres/lean/Pg/Ir/Emit/IntArith.lean`.\n" ++
    "// DO NOT EDIT BY HAND. Regenerate via\n" ++
    "// `rules_postgres/tools/regen/regen-int-arith.sh`.\n" ++
    "//\n" ++
    "// Integer-arithmetic V1 fmgr cluster: 21 functions =\n" ++
    "// {pl, mi, mul} × {int2, int4, int8} (same-type, 9 fns) +\n" ++
    "// {pl, mi, mul} × {int24, int42, int48, int84, int28, int82}\n" ++
    "// (cross-type, 12 fns).\n" ++
    "//\n" ++
    "// Each body decodes both operands, calls the matching\n" ++
    "// pg_<op>_s<W>_overflow primitive (W = result-type width), and\n" ++
    "// on overflow signals via pg_ereport_numeric_value_out_of_range()\n" ++
    "// + returning Datum 0. This mirrors Postgres' ereport(ERROR, ...)\n" ++
    "// path: a real backend catches the longjmp at the SPI/transaction\n" ++
    "// boundary; our Rust side just sets a TLS error flag and returns 0,\n" ++
    "// with the diff-test harness checking the (out, err) tuple round-\n" ++
    "// trips against the vendored C oracle.\n" ++
    "\n" ++
    "#![allow(clippy::missing_safety_doc)]\n" ++
    "\n" ++
    "use pg_fcinfo::{\n" ++
    "    decode_i16, decode_i32, decode_i64,\n" ++
    "    encode_i16, encode_i32, encode_i64,\n" ++
    "    pg_add_s16_overflow, pg_add_s32_overflow, pg_add_s64_overflow,\n" ++
    "    pg_sub_s16_overflow, pg_sub_s32_overflow, pg_sub_s64_overflow,\n" ++
    "    pg_mul_s16_overflow, pg_mul_s32_overflow, pg_mul_s64_overflow,\n" ++
    "    pg_ereport_numeric_value_out_of_range, FunctionCallInfoBaseData,\n" ++
    "};\n"
  Id.run do
    let mut s := header
    for fam in families do
      for op in ops do
        s := s ++ "\n" ++ renderFn fam op
    return s

end Pg.Ir.Emit.IntArith

def main : IO Unit := IO.print Pg.Ir.Emit.IntArith.rustSource
