import Pg.Ir.Emit.IntArithCommon

/-!
# Pg.Ir.Emit.IntArithC — codegen real-style Postgres C source for the
integer-arithmetic V1 fmgr cluster.

Sister to `Pg.Ir.Emit.IntArith` (which emits Rust). Same
`ArithFamily` table, but renders Postgres-idiomatic C so the result
AST-diffs cleanly against real `src/backend/utils/adt/int.c` and
`int8.c`.

Body shape (matches the byte-level formatting of real `int.c` /
`int8.c`):

```
Datum
<fn>(PG_FUNCTION_ARGS)
{
	<T1>		arg1 = <GETARG1>(0);
	<T2>		arg2 = <GETARG2>(1);
	<TR>		result;

	if (unlikely(pg_<op>_s<W>_overflow(<cast1>arg1, <cast2>arg2, &result)))
		ereport(ERROR,
				(errcode(ERRCODE_NUMERIC_VALUE_OUT_OF_RANGE),
				 errmsg("<word> out of range")));
	<RETURN>(result);
}
```
-/

namespace Pg.Ir.Emit.IntArithC

open Pg.Ir.Emit.IntArith (ArithOp ArithFamily families ops)

def fnName (fam : ArithFamily) (op : ArithOp) : String :=
  fam.namePrefix ++ op.suffix

/-- C `pg_<op>_s<W>_overflow` primitive name. -/
def overflowPrim (fam : ArithFamily) (op : ArithOp) : String :=
  "pg_" ++ op.primitive ++ "_" ++ fam.overflowWidth ++ "_overflow"

def renderCBody (fam : ArithFamily) (op : ArithOp) : String :=
  let prim := overflowPrim fam op
  "\t" ++ fam.cWidth1   ++ "\t\targ1 = " ++ fam.pgGetArg1 ++ "(0);\n" ++
  "\t" ++ fam.cWidth2   ++ "\t\targ2 = " ++ fam.pgGetArg2 ++ "(1);\n" ++
  "\t" ++ fam.cResultTy ++ "\t\tresult;\n\n" ++
  "\tif (unlikely(" ++ prim ++ "(" ++ fam.cCast1 ++ "arg1, " ++ fam.cCast2 ++ "arg2, &result)))\n" ++
  "\t\tereport(ERROR,\n" ++
  "\t\t\t\t(errcode(ERRCODE_NUMERIC_VALUE_OUT_OF_RANGE),\n" ++
  "\t\t\t\t errmsg(\"" ++ fam.errWord ++ " out of range\")));\n" ++
  "\t" ++ fam.pgReturn ++ "(result);\n"

def renderCFn (fam : ArithFamily) (op : ArithOp) : String :=
  "Datum\n" ++
  fnName fam op ++ "(PG_FUNCTION_ARGS)\n" ++
  "{\n" ++
  renderCBody fam op ++
  "}\n"

def cSource : String :=
  let header :=
    "/*\n" ++
    " * Generated by `rules_postgres/lean/Pg/Ir/Emit/IntArithC.lean`.\n" ++
    " * DO NOT EDIT BY HAND. Regenerate via\n" ++
    " * `rules_postgres/tools/regen/check-int-arith-grounding.sh`.\n" ++
    " *\n" ++
    " * This file exists to be `clang -ast-dump=json`-ed alongside\n" ++
    " * real `src/backend/utils/adt/int.c` and `int8.c` and structurally\n" ++
    " * diffed function-by-function. A passing diff means the Lean spec\n" ++
    " * captures the same algorithm Postgres wrote.\n" ++
    " */\n" ++
    "\n" ++
    "#include \"postgres.h\"\n" ++
    "#include \"common/int.h\"\n" ++
    "#include \"fmgr.h\"\n" ++
    "#include \"utils/fmgrprotos.h\"\n"
  Id.run do
    let mut s := header
    for fam in families do
      for op in ops do
        s := s ++ "\n" ++ renderCFn fam op
    return s

end Pg.Ir.Emit.IntArithC

def main : IO Unit := IO.print Pg.Ir.Emit.IntArithC.cSource
