import Pg.Ir.Emit.IntBitwiseCommon

namespace Pg.Ir.Emit.IntBitwise.Rust

open Pg.Ir.Emit.IntBitwise (BitwiseBody BitwiseOp BitwiseFamily families opRustSymbol)

def renderBody (fam : BitwiseFamily) : String :=
  let read1 :=
    "    let f = &mut *fcinfo;\n" ++
    "    let arg1 = " ++ fam.decoder ++ "(f.args[0].value);\n"
  match fam.body with
  | .binarySameType =>
      read1 ++
      "    let arg2 = " ++ fam.decoder ++ "(f.args[1].value);\n" ++
      "    " ++ fam.encoder ++ "(arg1 " ++ opRustSymbol fam.op ++ " arg2)\n"
  | .unary =>
      read1 ++
      "    " ++ fam.encoder ++ "(" ++ opRustSymbol fam.op ++ "arg1)\n"
  | .shift =>
      -- Shifts: arg2 is always int32 (decode_i32) regardless of arg1
      -- width. Use wrapping_shl/_shr for C-x86_64-equivalent mod-width
      -- semantics across all arg2 values (including arg2 < 0 or ≥ width).
      read1 ++
      "    let arg2 = decode_i32(f.args[1].value);\n" ++
      "    " ++ fam.encoder ++ "(arg1." ++ opRustSymbol fam.op ++ "(arg2 as u32))\n"

def renderFn (fam : BitwiseFamily) : String :=
  "#[no_mangle]\n" ++
  "pub unsafe extern \"C\" fn " ++ fam.fnName ++
    "(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {\n" ++
  renderBody fam ++
  "}\n"

def rustSource : String :=
  let header :=
    "// Generated by `rules_postgres/lean/Pg/Ir/Emit/IntBitwise.lean`.\n" ++
    "// DO NOT EDIT BY HAND. Regenerate via\n" ++
    "// `rules_postgres/tools/regen/regen-int-bitwise.sh`.\n" ++
    "//\n" ++
    "// 18 functions = 6 ops × 3 widths.\n" ++
    "// {and, or, xor} × {int2, int4, int8} — binary same-type.\n" ++
    "// {not}            × {int2, int4, int8} — unary.\n" ++
    "// {shl, shr}       × {int2, int4, int8} — binary with int32 shift count.\n" ++
    "//\n" ++
    "// Pure: no ereport, no palloc. Shifts use wrapping_shl/_shr to\n" ++
    "// match C's x86_64 mod-width semantics across all arg2 values.\n" ++
    "\n" ++
    "#![allow(clippy::missing_safety_doc)]\n" ++
    "\n" ++
    "use pg_fcinfo::{\n" ++
    "    decode_i16, decode_i32, decode_i64,\n" ++
    "    encode_i16, encode_i32, encode_i64,\n" ++
    "    FunctionCallInfoBaseData,\n" ++
    "};\n"
  Id.run do
    let mut s := header
    for fam in families do
      s := s ++ "\n" ++ renderFn fam
    return s

end Pg.Ir.Emit.IntBitwise.Rust

def main : IO Unit := IO.print Pg.Ir.Emit.IntBitwise.Rust.rustSource
