import Pg.Ir.Emit.IntBitwiseCommon

namespace Pg.Ir.Emit.IntBitwise.C

open Pg.Ir.Emit.IntBitwise (BitwiseBody BitwiseFamily families opCSymbol)

def renderCBody (fam : BitwiseFamily) : String :=
  let arg1Line := "\t" ++ fam.cType ++ "\t\targ1 = " ++ fam.pgGetArg ++ "(0);\n"
  match fam.body with
  | .binarySameType =>
      arg1Line ++
      "\t" ++ fam.cType ++ "\t\targ2 = " ++ fam.pgGetArg ++ "(1);\n" ++
      "\n" ++
      "\t" ++ fam.pgReturn ++ "(arg1 " ++ opCSymbol fam.op ++ " arg2);\n"
  | .unary =>
      arg1Line ++
      "\n" ++
      "\t" ++ fam.pgReturn ++ "(" ++ opCSymbol fam.op ++ "arg1);\n"
  | .shift =>
      arg1Line ++
      "\tint32\t\targ2 = PG_GETARG_INT32(1);\n" ++
      "\n" ++
      "\t" ++ fam.pgReturn ++ "(arg1 " ++ opCSymbol fam.op ++ " arg2);\n"

def renderCFn (fam : BitwiseFamily) : String :=
  "Datum\n" ++
  fam.fnName ++ "(PG_FUNCTION_ARGS)\n" ++
  "{\n" ++
  renderCBody fam ++
  "}\n"

def cSource : String :=
  let header :=
    "/*\n" ++
    " * Generated by `rules_postgres/lean/Pg/Ir/Emit/IntBitwiseC.lean`.\n" ++
    " * DO NOT EDIT BY HAND.\n" ++
    " */\n" ++
    "\n" ++
    "#include \"postgres.h\"\n" ++
    "#include \"utils/fmgrprotos.h\"\n"
  Id.run do
    let mut s := header
    for fam in families do
      s := s ++ "\n" ++ renderCFn fam
    return s

end Pg.Ir.Emit.IntBitwise.C

def main : IO Unit := IO.print Pg.Ir.Emit.IntBitwise.C.cSource
