import Pg.Ir.Emit.IntCastsCommon

/-!
# Pg.Ir.Emit.IntCastsC — codegen real-style Postgres C source for the
integer width-cast V1 fmgr cluster.

Sister to `Pg.Ir.Emit.IntCasts` (which emits Rust). Same
`CastFamily` table, but renders Postgres-idiomatic C so the result
AST-diffs cleanly against real `src/backend/utils/adt/int.c` and
`int8.c`.

Body shape (widening, e.g. i2toi4):
```c
Datum
i2toi4(PG_FUNCTION_ARGS)
{
	int16		arg = PG_GETARG_INT16(0);

	PG_RETURN_INT32((int32) arg);
}
```

Body shape (narrowing, e.g. i4toi2):
```c
Datum
i4toi2(PG_FUNCTION_ARGS)
{
	int32		arg = PG_GETARG_INT32(0);

	if (unlikely(arg < SHRT_MIN) || unlikely(arg > SHRT_MAX))
		ereport(ERROR,
				(errcode(ERRCODE_NUMERIC_VALUE_OUT_OF_RANGE),
				 errmsg("smallint out of range")));

	PG_RETURN_INT16((int16) arg);
}
```
-/

namespace Pg.Ir.Emit.IntCastsC

open Pg.Ir.Emit.IntCasts (CastFamily families)

-- Helper: use arg1 for i2toi4, i4toi2 (from int.c); arg for others (from int8.c)
def argName (fam : CastFamily) : String :=
  if fam.fnName == "i2toi4" || fam.fnName == "i4toi2" then "arg1" else "arg"

def renderCBody (fam : CastFamily) : String :=
  let argVar := argName fam
  if fam.isWidening then
    "\t" ++ fam.cSrcTy ++ "\t\t" ++ argVar ++ " = " ++ fam.pgGetArg ++ "(0);\n" ++
    "\n" ++
    "\t" ++ fam.pgReturn ++ "((" ++ fam.cResTy ++ ") " ++ argVar ++ ");\n"
  else
    -- Narrowing cast: check bounds with ereport
    "\t" ++ fam.cSrcTy ++ "\t\t" ++ argVar ++ " = " ++ fam.pgGetArg ++ "(0);\n" ++
    "\n" ++
    "\tif (unlikely(" ++ argVar ++ " < " ++ fam.minBound ++ ") || unlikely(" ++ argVar ++ " > " ++ fam.maxBound ++ "))\n" ++
    "\t\tereport(ERROR,\n" ++
    "\t\t\t\t(errcode(ERRCODE_NUMERIC_VALUE_OUT_OF_RANGE),\n" ++
    "\t\t\t\t errmsg(\"" ++ fam.errmsg ++ "\")));\n" ++
    "\n" ++
    "\t" ++ fam.pgReturn ++ "((" ++ fam.cResTy ++ ") " ++ argVar ++ ");\n"

def renderCFn (fam : CastFamily) : String :=
  "Datum\n" ++
  fam.fnName ++ "(PG_FUNCTION_ARGS)\n" ++
  "{\n" ++
  renderCBody fam ++
  "}\n"

def cSource : String :=
  let header :=
    "/*\n" ++
    " * Generated by `rules_postgres/lean/Pg/Ir/Emit/IntCastsC.lean`.\n" ++
    " * DO NOT EDIT BY HAND. Regenerate via\n" ++
    " * `rules_postgres/tools/regen/check-int-casts-grounding.sh`.\n" ++
    " *\n" ++
    " * This file exists to be `clang -ast-dump=json`-ed alongside\n" ++
    " * real `src/backend/utils/adt/int.c` and `int8.c` and structurally\n" ++
    " * diffed function-by-function. A passing diff means the Lean spec\n" ++
    " * captures the same algorithm Postgres wrote.\n" ++
    " */\n" ++
    "\n" ++
    "#include \"postgres.h\"\n" ++
    "#include <limits.h>\n" ++           -- SHRT_MIN/SHRT_MAX/INT_MIN/INT_MAX
    "#include \"common/int.h\"\n" ++
    "#include \"fmgr.h\"\n" ++
    "#include \"utils/fmgrprotos.h\"\n"
  Id.run do
    let mut s := header
    for fam in families do
      s := s ++ "\n" ++ renderCFn fam
    return s

end Pg.Ir.Emit.IntCastsC

def main : IO Unit := IO.print Pg.Ir.Emit.IntCastsC.cSource
