import Pg.Ir.Types
import Pg.Ir.Datum
import Pg.Ir.Cmp
import Pg.Ir.Emit.Common

/-!
# Pg.Ir.Emit.IntCmp — codegen the int/date/timestamp/cash/pg_lsn/oid
comparison cluster as Rust source.

Generates the Rust functions in
`rules_lang/translated/pg_int4_cmp/src/lib.rs` from the polymorphic
operations in `Pg.Ir.Cmp` instantiated at the Postgres type families
in `Pg.Ir.Types`.

48 Rust functions total = 8 type families × 6 operations:
  int2 / int4 / int8 / date / timestamp / cash / pg_lsn / oid
  × {eq, ne, lt, le, gt, ge}

The codegen is structurally simple — template + per-family
(name_prefix, decoder, comparison_op) triple. The emitted Rust calls
into the same `pg_fcinfo::decode_*` helpers the hand-written version
uses, so the diff-test gate is preserved unchanged.

This file is the v0 prototype of the "Lean source-of-truth for Rust
emits" pattern applied to the C→Rust translation pipeline. The
klad/lean/Klad/Emit.lean precedent established the regen flow for
the bucket-key bijection; this scales it to a 48-function cluster.

The emitted file lives in the sibling `rules_lang` repo, not here —
this Lean module is the spec, the regen script crosses the repo
boundary. See `tools/regen/regen-int-cmp.sh`.
-/

namespace Pg.Ir.Emit.IntCmp

open Pg.Ir.Emit (CmpStyle Family families ops effectiveCmpStyle decoderForArg1 decoderForArg2)

/-- Format an operand reference: just `a`/`b` when no promotion is
needed; `(a as <wider>)` when the family needs Rust to widen for
cross-type comparison. -/
def formatOperand (fam : Family) (name : String) : String :=
  if fam.rustPromote == "" then name
  else "(" ++ name ++ " as " ++ fam.rustPromote ++ ")"

/-- Render the body line that computes the comparison result, given
the operand expressions for `a` and `b`. -/
def renderBody (fam : Family) (suffix opStr : String) : String :=
  let a := formatOperand fam "a"
  let b := formatOperand fam "b"
  let style := effectiveCmpStyle fam suffix
  match style with
  | .native                   =>
      "    encode_bool(" ++ a ++ " " ++ opStr ++ " " ++ b ++ ")\n"
  | .nativeCastBoth _ rustCast =>
      "    encode_bool((" ++ a ++ " as " ++ rustCast ++ ") " ++ opStr ++
      " (" ++ b ++ " as " ++ rustCast ++ "))\n"
  | .pgFloat32                =>
      "    encode_bool(pg_fcinfo::pgcmp_" ++ suffix ++ "_f32(" ++ a ++ ", " ++ b ++ "))\n"
  | .pgFloat64                =>
      "    encode_bool(pg_fcinfo::pgcmp_" ++ suffix ++ "_f64(" ++ a ++ ", " ++ b ++ "))\n"
  | .pgCmpInternal name       =>
      "    encode_bool(pg_fcinfo::" ++ name ++ "(" ++ a ++ ", " ++ b ++ ") " ++
      opStr ++ " 0)\n"

/-- Render one Rust function. -/
def renderFn (fam : Family) (suffix opStr : String) : String :=
  let fnName := fam.namePrefix ++ suffix
  let dec1   := decoderForArg1 fam
  let dec2   := decoderForArg2 fam
  "#[no_mangle]\n" ++
  "pub unsafe extern \"C\" fn " ++ fnName ++ "(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {\n" ++
  "    let f = &mut *fcinfo;\n" ++
  "    let a = " ++ dec1 ++ "(f.args[0].value);\n" ++
  "    let b = " ++ dec2 ++ "(f.args[1].value);\n" ++
  renderBody fam suffix opStr ++
  "}\n"

/-- Render a family-section header comment. -/
def renderHeader (fam : Family) : String :=
  "// ─── " ++ fam.namePrefix ++ " family (decoder: " ++ fam.decoder ++ ") ──\n"

/-- Render all 6 ops for one family. -/
def renderFamily (fam : Family) : String :=
  Id.run do
    let mut s := renderHeader fam
    for (suffix, opStr) in ops do
      s := s ++ "\n" ++ renderFn fam suffix opStr
    return s

/-- The full Rust source for all 48 functions. -/
def rustSource : String :=
  let header :=
    "// Generated by `rules_postgres/lean/Pg/Ir/Emit/IntCmp.lean`.\n" ++
    "// DO NOT EDIT BY HAND. Regenerate via\n" ++
    "// `rules_postgres/tools/regen/regen-int-cmp.sh`.\n" ++
    "//\n" ++
    "// Source of truth: the polymorphic comparison primitives in\n" ++
    "// `Pg.Ir.Cmp` instantiated at the Postgres type families in\n" ++
    "// `Pg.Ir.Types`. Each emitted function matches the corresponding\n" ++
    "// cmp* spec theorem in Pg.Ir.Cmp (see `cmpEq_spec` etc.). The C\n" ++
    "// side is gated by the diff-test in tests/diff_int4_cmp.rs (~98K\n" ++
    "// cases passing against real Postgres 17.6).\n" ++
    "//\n" ++
    "// 48 functions = 8 type families × 6 comparison operations.\n" ++
    "\n" ++
    "#![allow(clippy::missing_safety_doc)]\n" ++
    "\n" ++
    "use pg_fcinfo::{\n" ++
    "    decode_bool, decode_f32, decode_f64, decode_i8,\n" ++
    "    decode_i16, decode_i32, decode_i64, decode_u32, decode_u64,\n" ++
    "    encode_bool, FunctionCallInfoBaseData,\n" ++
    "};\n"
  Id.run do
    let mut s := header
    for fam in families do
      s := s ++ "\n" ++ renderFamily fam
    return s

end Pg.Ir.Emit.IntCmp

/-- `main` entrypoint: print the Rust source to stdout. -/
def main : IO Unit := IO.print Pg.Ir.Emit.IntCmp.rustSource
