import Pg.Ir.Types
import Pg.Ir.Datum
import Pg.Ir.Emit.Common
import Pg.Ir.Emit.IntCastsCommon

/-!
# Pg.Ir.Emit.IntCasts — codegen the integer width-cast V1 fmgr cluster
as Rust source.

Sister to `Pg.Ir.Emit.IntArith`. Simpler cluster: single argument,
no overflow primitives. Widening casts are trivial; narrowing casts
check bounds and ereport on overflow.

v1 covers 6 functions: {i2toi4, i4toi2, i2toi8, i8toi2, i4toi8, i8toi4}.

Body shape (widening, e.g. i2toi4):
```rust
pub unsafe extern "C" fn i2toi4(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg = decode_i16(f.args[0].value);
    encode_i32(arg as i32)
}
```

Body shape (narrowing, e.g. i4toi2):
```rust
pub unsafe extern "C" fn i4toi2(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg = decode_i32(f.args[0].value);
    if arg < i16::MIN as i32 || arg > i16::MAX as i32 {
        pg_ereport_numeric_value_out_of_range();
        return 0;
    }
    encode_i16(arg as i16)
}
```
-/

namespace Pg.Ir.Emit.IntCasts.Rust

open Pg.Ir.Emit.IntCasts (CastFamily families)

/-- Render the Rust body. -/
def renderBody (fam : CastFamily) : String :=
  if fam.isWidening then
    "    let f = &mut *fcinfo;\n" ++
    "    let arg = " ++ fam.srcDecoder ++ "(f.args[0].value);\n" ++
    "    " ++ fam.resEncoder ++ "(arg as " ++ fam.rustResTy ++ ")\n"
  else
    -- Narrowing cast: check bounds
    let minVal := if fam.rustResTy == "i16" then "i16::MIN as " ++ fam.rustSrcTy
                  else if fam.rustResTy == "i32" then "i32::MIN as " ++ fam.rustSrcTy
                  else "i64::MIN as " ++ fam.rustSrcTy
    let maxVal := if fam.rustResTy == "i16" then "i16::MAX as " ++ fam.rustSrcTy
                  else if fam.rustResTy == "i32" then "i32::MAX as " ++ fam.rustSrcTy
                  else "i64::MAX as " ++ fam.rustSrcTy
    "    let f = &mut *fcinfo;\n" ++
    "    let arg = " ++ fam.srcDecoder ++ "(f.args[0].value);\n" ++
    "    if arg < " ++ minVal ++ " || arg > " ++ maxVal ++ " {\n" ++
    "        pg_ereport_numeric_value_out_of_range();\n" ++
    "        return 0;\n" ++
    "    }\n" ++
    "    " ++ fam.resEncoder ++ "(arg as " ++ fam.rustResTy ++ ")\n"

def renderFn (fam : CastFamily) : String :=
  "#[no_mangle]\n" ++
  "pub unsafe extern \"C\" fn " ++ fam.fnName ++
    "(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {\n" ++
  renderBody fam ++
  "}\n"

/-- The full Rust source. -/
def rustSource : String :=
  let header :=
    "// Generated by `rules_postgres/lean/Pg/Ir/Emit/IntCasts.lean`.\n" ++
    "// DO NOT EDIT BY HAND. Regenerate via\n" ++
    "// `rules_postgres/tools/regen/regen-int-casts.sh`.\n" ++
    "//\n" ++
    "// Integer width-cast V1 fmgr cluster: 6 functions =\n" ++
    "// {i2toi4, i4toi2, i2toi8, i8toi2, i4toi8, i8toi4}.\n" ++
    "//\n" ++
    "// Widening casts (i2→i4, i2→i8, i4→i8) are pure — direct cast.\n" ++
    "// Narrowing casts (i4→i2, i8→i2, i8→i4) check overflow bounds and\n" ++
    "// ereport on range violation. This mirrors Postgres' ereport(ERROR, ...)\n" ++
    "// path: a real backend catches the longjmp at the SPI/transaction\n" ++
    "// boundary; our Rust side just sets a TLS error flag and returns 0,\n" ++
    "// with the diff-test harness checking the (out, err) tuple round-\n" ++
    "// trips against the vendored C oracle.\n" ++
    "\n" ++
    "#![allow(clippy::missing_safety_doc)]\n" ++
    "\n" ++
    "use pg_fcinfo::{\n" ++
    "    decode_i16, decode_i32, decode_i64,\n" ++
    "    encode_i16, encode_i32, encode_i64,\n" ++
    "    pg_ereport_numeric_value_out_of_range, FunctionCallInfoBaseData,\n" ++
    "};\n"
  Id.run do
    let mut s := header
    for fam in families do
      s := s ++ "\n" ++ renderFn fam
    return s

end Pg.Ir.Emit.IntCasts.Rust

def main : IO Unit := IO.print Pg.Ir.Emit.IntCasts.Rust.rustSource
