import Pg.Ir.Emit.IntDivCommon

/-!
# Pg.Ir.Emit.IntDivC — codegen real-style Postgres C source for the
integer-division V1 fmgr cluster.

Sister to `Pg.Ir.Emit.IntDiv` (which emits Rust). Same `DivFamilySpec`
table, but renders Postgres-idiomatic C so the result AST-diffs cleanly
against real `src/backend/utils/adt/int.c` and `int8.c`.

Body shape (matches the byte-level formatting of real `int.c` / `int8.c`):

```
Datum
<fn>(PG_FUNCTION_ARGS)
{
	<T>		arg1 = <GETARG>(0);
	<T>		arg2 = <GETARG>(1);
	<T>		result;

	if (arg2 == 0)
	{
		ereport(ERROR,
				(errcode(ERRCODE_DIVISION_BY_ZERO),
				 errmsg("division by zero")));
		PG_RETURN_NULL();
	}

	if (arg2 == -1)
	{
		if (unlikely(arg1 == <MIN>))
			ereport(ERROR,
					(errcode(ERRCODE_NUMERIC_VALUE_OUT_OF_RANGE),
					 errmsg("<word> out of range")));
		result = -arg1;
		<RETURN>(result);
	}

	result = arg1 / arg2;

	<RETURN>(result);
}
```
-/

namespace Pg.Ir.Emit.IntDivC

open Pg.Ir.Emit.IntDiv (DivFamilySpec families)

def renderCBody (fam : DivFamilySpec) : String :=
  "\t" ++ fam.cWidth   ++ "\t\targ1 = " ++ fam.pgGetArg ++ "(0);\n" ++
  "\t" ++ fam.cWidth   ++ "\t\targ2 = " ++ fam.pgGetArg ++ "(1);\n" ++
  "\t" ++ fam.cWidth   ++ "\t\tresult;\n\n" ++
  "\tif (arg2 == 0)\n" ++
  "\t{\n" ++
  "\t\tereport(ERROR,\n" ++
  "\t\t\t\t(errcode(ERRCODE_DIVISION_BY_ZERO),\n" ++
  "\t\t\t\t errmsg(\"division by zero\")));\n" ++
  "\t\tPG_RETURN_NULL();\n" ++
  "\t}\n\n" ++
  "\tif (arg2 == -1)\n" ++
  "\t{\n" ++
  "\t\tif (unlikely(arg1 == " ++ fam.cMin ++ "))\n" ++
  "\t\t\tereport(ERROR,\n" ++
  "\t\t\t\t\t(errcode(ERRCODE_NUMERIC_VALUE_OUT_OF_RANGE),\n" ++
  "\t\t\t\t\t errmsg(\"" ++ fam.errWord ++ " out of range\")));\n" ++
  "\t\tresult = -arg1;\n" ++
  "\t\t" ++ fam.pgReturn ++ "(result);\n" ++
  "\t}\n\n" ++
  "\tresult = arg1 / arg2;\n\n" ++
  "\t" ++ fam.pgReturn ++ "(result);\n"

def renderCFn (fam : DivFamilySpec) : String :=
  "Datum\n" ++
  fam.fnName ++ "(PG_FUNCTION_ARGS)\n" ++
  "{\n" ++
  renderCBody fam ++
  "}\n"

def cSource : String :=
  let header :=
    "/*\n" ++
    " * Generated by `rules_postgres/lean/Pg/Ir/Emit/IntDivC.lean`.\n" ++
    " * DO NOT EDIT BY HAND. Regenerate via\n" ++
    " * `rules_postgres/tools/regen/check-int-div-grounding.sh`.\n" ++
    " *\n" ++
    " * This file exists to be `clang -ast-dump=json`-ed alongside\n" ++
    " * real `src/backend/utils/adt/int.c` and `int8.c` and structurally\n" ++
    " * diffed function-by-function. A passing diff means the Lean spec\n" ++
    " * captures the same algorithm Postgres wrote.\n" ++
    " */\n" ++
    "\n" ++
    "#include \"postgres.h\"\n" ++
    "#include \"fmgr.h\"\n" ++
    "#include \"utils/fmgrprotos.h\"\n"
  Id.run do
    let mut s := header
    for fam in families do
      s := s ++ "\n" ++ renderCFn fam
    return s

end Pg.Ir.Emit.IntDivC

def main : IO Unit := IO.print Pg.Ir.Emit.IntDivC.cSource
