import Pg.Ir.Types
import Pg.Ir.Datum
import Pg.Ir.Emit.Common
import Pg.Ir.Emit.IntDivCommon

/-!
# Pg.Ir.Emit.IntDiv — codegen the integer-division V1 fmgr cluster
as Rust source.

Sister to `Pg.Ir.Emit.IntArith`. Same Pg.Ir architecture; different
cluster shape: **two-argument division with dual errcodes** instead of
overflow-checked arithmetic. v1 covers {int2div, int4div, int8div} —
3 functions total.

The canonical body shape (int4div, derived from Postgres int.c):

```rust
#[no_mangle]
pub unsafe extern "C" fn int4div(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_i32(f.args[0].value);
    let arg2 = decode_i32(f.args[1].value);
    if arg2 == 0 {
        pg_ereport_division_by_zero();
        return 0;
    }
    if arg2 == -1 {
        if unlikely(arg1 == i32::MIN) {
            pg_ereport_numeric_value_out_of_range();
            return 0;
        }
        let result = -arg1;
        return encode_i32(result);
    }
    let result = arg1 / arg2;
    encode_i32(result)
}
```
-/

namespace Pg.Ir.Emit.IntDiv

/-- Render the Rust body. -/
def renderBody (fam : DivFamilySpec) : String :=
  "    let f = &mut *fcinfo;\n" ++
  "    let arg1 = " ++ fam.decoder ++ "(f.args[0].value);\n" ++
  "    let arg2 = " ++ fam.decoder ++ "(f.args[1].value);\n" ++
  "    if arg2 == 0 {\n" ++
  "        pg_ereport_division_by_zero();\n" ++
  "        return 0;\n" ++
  "    }\n" ++
  "    if arg2 == -1 {\n" ++
  "        if unlikely(arg1 == " ++ fam.rustMin ++ ") {\n" ++
  "            pg_ereport_numeric_value_out_of_range();\n" ++
  "            return 0;\n" ++
  "        }\n" ++
  "        let result = -arg1;\n" ++
  "        return " ++ fam.rustEncoder ++ "(result);\n" ++
  "    }\n" ++
  "    let result = arg1 / arg2;\n" ++
  "    " ++ fam.rustEncoder ++ "(result)\n"

def renderFn (fam : DivFamilySpec) : String :=
  "#[no_mangle]\n" ++
  "pub unsafe extern \"C\" fn " ++ fam.fnName ++
    "(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {\n" ++
  renderBody fam ++
  "}\n"

/-- The full Rust source. -/
def rustSource : String :=
  let header :=
    "// Generated by `rules_postgres/lean/Pg/Ir/Emit/IntDiv.lean`.\n" ++
    "// DO NOT EDIT BY HAND. Regenerate via\n" ++
    "// `rules_postgres/tools/regen/regen-int-div.sh`.\n" ++
    "//\n" ++
    "// Integer-division V1 fmgr cluster: 3 functions = {int2div, int4div, int8div}.\n" ++
    "//\n" ++
    "// Each body decodes both operands, checks for division by zero\n" ++
    "// (ERRCODE_DIVISION_BY_ZERO), checks for INT_MIN / -1 overflow\n" ++
    "// (ERRCODE_NUMERIC_VALUE_OUT_OF_RANGE), and returns the quotient.\n" ++
    "// On error, signals via pg_ereport_division_by_zero() or\n" ++
    "// pg_ereport_numeric_value_out_of_range() + returning Datum 0.\n" ++
    "// This mirrors Postgres' ereport(ERROR, ...) path: a real backend catches\n" ++
    "// the longjmp at the SPI/transaction boundary; our Rust side just sets a\n" ++
    "// TLS error flag and returns 0, with the diff-test harness checking the\n" ++
    "// (out, err) tuple round-trips against the vendored C oracle.\n" ++
    "\n" ++
    "#![allow(clippy::missing_safety_doc)]\n" ++
    "\n" ++
    "use pg_fcinfo::{\n" ++
    "    decode_i16, decode_i32, decode_i64,\n" ++
    "    encode_i16, encode_i32, encode_i64,\n" ++
    "    pg_ereport_division_by_zero, pg_ereport_numeric_value_out_of_range,\n" ++
    "    FunctionCallInfoBaseData,\n" ++
    "};\n" ++
    "\n" ++
    "fn unlikely(cond: bool) -> bool { cond }\n"
  Id.run do
    let mut s := header
    for fam in families do
      s := s ++ "\n" ++ renderFn fam
    return s

end Pg.Ir.Emit.IntDiv

def main : IO Unit := IO.print Pg.Ir.Emit.IntDiv.rustSource
