import Pg.Ir.Types
import Pg.Ir.Datum
import Pg.Ir.Emit.Common
import Pg.Ir.Emit.IntHashCommon

/-!
# Pg.Ir.Emit.IntHash — codegen the integer-type hash V1 fmgr cluster.

Sister to `Pg.Ir.Emit.IntCmp`. Same Pg.Ir architecture; different
cluster shape: **1 argument → uint32** (Datum-packaged) instead of
**2 arguments → bool**.

Source surface from `src/backend/access/hash/hashfunc.c` (PG 17.6):

```
hashchar  : hash_uint32((int32) PG_GETARG_CHAR(0))
hashint2  : hash_uint32((int32) PG_GETARG_INT16(0))
hashint4  : hash_uint32(PG_GETARG_INT32(0))
hashoid   : hash_uint32((uint32) PG_GETARG_OID(0))
hashenum  : hash_uint32((uint32) PG_GETARG_OID(0))
hashint8  : { lohalf, hihalf split; xor; hash_uint32(lohalf) }
```

All six route through `hash_uint32`, which is an inline wrapper over
`hash_bytes_uint32` (Postgres' Jenkins/lookup3 from
`src/common/hashfn.c`). The Rust side calls `pg_fcinfo::hash_bytes_uint32`
which is a verbatim Rust port of that primitive, validated against
the vendored C bodies in `translated/pg_int4_hash/c_oracle/`.

v1 scope: 12 functions (6 standard + 6 `*extended` siblings). The
extended variants take a uint64 seed and route through
`hash_uint32_extended`, returning uint64.
-/

namespace Pg.Ir.Emit.IntHash

/-- Render the final hash call given the prepared `u32` operand
`kExpr`. Standard variants call `hash_bytes_uint32` and `encode_u32`;
extended variants call `hash_bytes_uint32_extended` with the seed
read from `f.args[1].value` and `encode_u64` the result. -/
def renderFinalCall (extended : Bool) (kExpr : String) : String :=
  if extended then
    "    let seed: u64 = decode_i64(f.args[1].value) as u64;\n" ++
    "    encode_u64(hash_bytes_uint32_extended(" ++ kExpr ++ ", seed))\n"
  else
    "    encode_u32(hash_bytes_uint32(" ++ kExpr ++ "))\n"

/-- Render the function body lines (everything between `{` and `}`). -/
def renderBody (fam : HashFamily) : String :=
  let decode := "    let f = &mut *fcinfo;\n"
  match fam.body with
  | .signedToU32 =>
      decode ++
      "    let k = " ++ fam.decoder ++ "(f.args[0].value) as i32 as u32;\n" ++
      renderFinalCall fam.extended "k"
  | .unsignedAsU32 =>
      decode ++
      "    let k = " ++ fam.decoder ++ "(f.args[0].value);\n" ++
      renderFinalCall fam.extended "k"
  | .int8Split =>
      decode ++
      "    let val: i64 = " ++ fam.decoder ++ "(f.args[0].value);\n" ++
      "    let lohalf: u32 = val as u32;\n" ++
      "    let hihalf: u32 = (val >> 32) as u32;\n" ++
      "    let lohalf = lohalf ^ if val >= 0 { hihalf } else { !hihalf };\n" ++
      renderFinalCall fam.extended "lohalf"

/-- Render one Rust function. -/
def renderFn (fam : HashFamily) : String :=
  "#[no_mangle]\n" ++
  "pub unsafe extern \"C\" fn " ++ fam.fnName ++
    "(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {\n" ++
  renderBody fam ++
  "}\n"

/-- The full Rust source. -/
def rustSource : String :=
  let header :=
    "// Generated by `rules_postgres/lean/Pg/Ir/Emit/IntHash.lean`.\n" ++
    "// DO NOT EDIT BY HAND. Regenerate via\n" ++
    "// `rules_postgres/tools/regen/regen-int-hash.sh`.\n" ++
    "//\n" ++
    "// Integer-type hash V1 fmgr cluster: 12 functions = 6 type\n" ++
    "// families × {standard, extended}. Standard variants route through\n" ++
    "// pg_fcinfo::hash_bytes_uint32 (mirror of Postgres' Jenkins/lookup3\n" ++
    "// hash_bytes_uint32); extended variants take a uint64 seed and\n" ++
    "// route through hash_bytes_uint32_extended.\n" ++
    "\n" ++
    "#![allow(clippy::missing_safety_doc)]\n" ++
    "\n" ++
    "use pg_fcinfo::{\n" ++
    "    decode_i8, decode_i16, decode_i32, decode_i64, decode_u32,\n" ++
    "    encode_u32, encode_u64, hash_bytes_uint32, hash_bytes_uint32_extended,\n" ++
    "    FunctionCallInfoBaseData,\n" ++
    "};\n"
  Id.run do
    let mut s := header
    for fam in families do
      s := s ++ "\n" ++ renderFn fam
    return s

end Pg.Ir.Emit.IntHash

def main : IO Unit := IO.print Pg.Ir.Emit.IntHash.rustSource
