import Pg.Ir.Emit.IntHashCommon

/-!
# Pg.Ir.Emit.IntHashC — codegen real-style Postgres C source for the
hash V1 fmgr family.

Sister to `Pg.Ir.Emit.IntHash` (which emits Rust). Same `HashFamily`
table, but renders Postgres-idiomatic C so the result AST-diffs
cleanly against real `src/backend/access/hash/hashfunc.c`.
-/

namespace Pg.Ir.Emit.IntHashC

open Pg.Ir.Emit.IntHash (HashBody HashFamily)

/-- Render the trailing call. Standard families emit
`hash_uint32(<arg>)`; extended families emit
`hash_uint32_extended(<arg>, PG_GETARG_INT64(1))`. -/
def renderTailCall (extended : Bool) (argExpr : String) : String :=
  if extended then
    "\treturn hash_uint32_extended(" ++ argExpr ++ ", PG_GETARG_INT64(1));\n"
  else
    "\treturn hash_uint32(" ++ argExpr ++ ");\n"

/-- Render the C body. -/
def renderCBody (fam : HashFamily) : String :=
  match fam.body with
  | .signedToU32 | .unsignedAsU32 =>
      renderTailCall fam.extended (fam.cCast ++ fam.pgGetArg ++ "(0)")
  | .int8Split =>
      "\tint64\t\tval = PG_GETARG_INT64(0);\n" ++
      "\tuint32\t\tlohalf = (uint32) val;\n" ++
      "\tuint32\t\thihalf = (uint32) (val >> 32);\n\n" ++
      "\tlohalf ^= (val >= 0) ? hihalf : ~hihalf;\n\n" ++
      renderTailCall fam.extended "lohalf"

def renderCFn (fam : HashFamily) : String :=
  "Datum\n" ++
  fam.fnName ++ "(PG_FUNCTION_ARGS)\n" ++
  "{\n" ++
  renderCBody fam ++
  "}\n"

def cSource : String :=
  let header :=
    "/*\n" ++
    " * Generated by `rules_postgres/lean/Pg/Ir/Emit/IntHashC.lean`.\n" ++
    " * DO NOT EDIT BY HAND. Regenerate via\n" ++
    " * `rules_postgres/tools/regen/check-int-hash-grounding.sh`.\n" ++
    " *\n" ++
    " * This file exists to be `clang -ast-dump=json`-ed alongside\n" ++
    " * real `src/backend/access/hash/hashfunc.c` and structurally\n" ++
    " * diffed function-by-function. A passing diff means the Lean\n" ++
    " * spec captures the same algorithm Postgres wrote.\n" ++
    " */\n" ++
    "\n" ++
    "#include \"postgres.h\"\n" ++
    "#include \"common/hashfn.h\"\n" ++
    "#include \"utils/fmgrprotos.h\"\n"
  Id.run do
    let mut s := header
    for fam in Pg.Ir.Emit.IntHash.families do
      s := s ++ "\n" ++ renderCFn fam
    return s

end Pg.Ir.Emit.IntHashC

def main : IO Unit := IO.print Pg.Ir.Emit.IntHashC.cSource
