import Pg.Ir.Emit.IntUnaryCommon

/-!
# Pg.Ir.Emit.IntUnaryC — emit real-style Postgres C for the int unary
cluster (AST grounding companion to IntUnary.lean).

Bodies match real Postgres source structure byte-equivalent (modulo
whitespace clang normalizes) so the per-function AST diff is clean.
-/

namespace Pg.Ir.Emit.IntUnary.C

open Pg.Ir.Emit.IntUnary (UnaryBody UnaryFamily families)

def renderCBody (fam : UnaryFamily) : String :=
  match fam.body with
  | .umFlat =>
      "\t" ++ fam.cWidth ++ "\t\targ = " ++ fam.pgGetArg ++ "(0);\n" ++
      "\n" ++
      "\tif (unlikely(arg == " ++ fam.cIntMin ++ "))\n" ++
      "\t\tereport(ERROR,\n" ++
      "\t\t\t\t(errcode(ERRCODE_NUMERIC_VALUE_OUT_OF_RANGE),\n" ++
      "\t\t\t\t errmsg(\"" ++ fam.errmsg ++ "\")));\n" ++
      "\t" ++ fam.pgReturn ++ "(-arg);\n"
  | .umWithResult =>
      "\t" ++ fam.cWidth ++ "\t\targ = " ++ fam.pgGetArg ++ "(0);\n" ++
      "\t" ++ fam.cWidth ++ "\t\tresult;\n" ++
      "\n" ++
      "\tif (unlikely(arg == " ++ fam.cIntMin ++ "))\n" ++
      "\t\tereport(ERROR,\n" ++
      "\t\t\t\t(errcode(ERRCODE_NUMERIC_VALUE_OUT_OF_RANGE),\n" ++
      "\t\t\t\t errmsg(\"" ++ fam.errmsg ++ "\")));\n" ++
      "\tresult = -arg;\n" ++
      "\t" ++ fam.pgReturn ++ "(result);\n"
  | .abs =>
      "\t" ++ fam.cWidth ++ "\t\targ1 = " ++ fam.pgGetArg ++ "(0);\n" ++
      "\t" ++ fam.cWidth ++ "\t\tresult;\n" ++
      "\n" ++
      "\tif (unlikely(arg1 == " ++ fam.cIntMin ++ "))\n" ++
      "\t\tereport(ERROR,\n" ++
      "\t\t\t\t(errcode(ERRCODE_NUMERIC_VALUE_OUT_OF_RANGE),\n" ++
      "\t\t\t\t errmsg(\"" ++ fam.errmsg ++ "\")));\n" ++
      "\tresult = (arg1 < 0) ? -arg1 : arg1;\n" ++
      "\t" ++ fam.pgReturn ++ "(result);\n"

def renderCFn (fam : UnaryFamily) : String :=
  "Datum\n" ++
  fam.fnName ++ "(PG_FUNCTION_ARGS)\n" ++
  "{\n" ++
  renderCBody fam ++
  "}\n"

def cSource : String :=
  let header :=
    "/*\n" ++
    " * Generated by `rules_postgres/lean/Pg/Ir/Emit/IntUnaryC.lean`.\n" ++
    " * DO NOT EDIT BY HAND. Regenerate via\n" ++
    " * `rules_postgres/tools/regen/check-int-unary-grounding.sh`.\n" ++
    " */\n" ++
    "\n" ++
    "#include \"postgres.h\"\n" ++
    "#include \"common/int.h\"\n" ++
    "#include \"utils/fmgrprotos.h\"\n"
  Id.run do
    let mut s := header
    for fam in families do
      s := s ++ "\n" ++ renderCFn fam
    return s

end Pg.Ir.Emit.IntUnary.C

def main : IO Unit := IO.print Pg.Ir.Emit.IntUnary.C.cSource
