import Pg.Ir.Emit.IntUnaryCommon

/-!
# Pg.Ir.Emit.IntUnary — Rust emit for the int unary V1 fmgr cluster.
-/

namespace Pg.Ir.Emit.IntUnary.Rust

open Pg.Ir.Emit.IntUnary (UnaryBody UnaryFamily families)

def renderBody (fam : UnaryFamily) : String :=
  let prelude :=
    "    let f = &mut *fcinfo;\n" ++
    "    let arg = " ++ fam.decoder ++ "(f.args[0].value);\n" ++
    "    if arg == " ++ fam.rustIntMin ++ " {\n" ++
    "        pg_ereport_numeric_value_out_of_range();\n" ++
    "        return 0;\n" ++
    "    }\n"
  match fam.body with
  | .umFlat =>
      prelude ++ "    " ++ fam.encoder ++ "(-arg)\n"
  | .umWithResult =>
      prelude ++
      "    let result: " ++ fam.rustTy ++ " = -arg;\n" ++
      "    " ++ fam.encoder ++ "(result)\n"
  | .abs =>
      prelude ++
      "    let result: " ++ fam.rustTy ++ " = if arg < 0 { -arg } else { arg };\n" ++
      "    " ++ fam.encoder ++ "(result)\n"

def renderFn (fam : UnaryFamily) : String :=
  "#[no_mangle]\n" ++
  "pub unsafe extern \"C\" fn " ++ fam.fnName ++
    "(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {\n" ++
  renderBody fam ++
  "}\n"

def rustSource : String :=
  let header :=
    "// Generated by `rules_postgres/lean/Pg/Ir/Emit/IntUnary.lean`.\n" ++
    "// DO NOT EDIT BY HAND. Regenerate via\n" ++
    "// `rules_postgres/tools/regen/regen-int-unary.sh`.\n" ++
    "//\n" ++
    "// Integer unary V1 fmgr cluster: 6 functions = {um, abs} ×\n" ++
    "// {int2, int4, int8}. Each body checks the single overflow\n" ++
    "// edge (`arg == <ty>::MIN`) and ereports on hit, otherwise\n" ++
    "// returns the negated / absolute value.\n" ++
    "\n" ++
    "#![allow(clippy::missing_safety_doc)]\n" ++
    "\n" ++
    "use pg_fcinfo::{\n" ++
    "    decode_i16, decode_i32, decode_i64,\n" ++
    "    encode_i16, encode_i32, encode_i64,\n" ++
    "    pg_ereport_numeric_value_out_of_range, FunctionCallInfoBaseData,\n" ++
    "};\n"
  Id.run do
    let mut s := header
    for fam in families do
      s := s ++ "\n" ++ renderFn fam
    return s

end Pg.Ir.Emit.IntUnary.Rust

def main : IO Unit := IO.print Pg.Ir.Emit.IntUnary.Rust.rustSource
