import Pg.Ir.Types
import Pg.Ir.Datum
import Pg.Ir.Emit.MacaddrCommon

/-!
# Pg.Ir.Emit.Macaddr — codegen the macaddr cmp + hash cluster as Rust source.

Generates the Rust functions for macaddr comparison and hashing from the specs
in `Pg.Ir.Emit.MacaddrCommon` instantiated at the Postgres macaddr type.

9 Rust functions total = 6 comparison ops + 1 cmp op + 2 hash ops.

The codegen mirrors the `Pg.Ir.Emit.IntCmp` / `Pg.Ir.Emit.IntHash` pattern:
template + per-family metadata. The emitted Rust calls into `pg_fcinfo` helpers
for decoding macaddr (6-byte pointers) and hashing (Jenkins/lookup3).

This file is the source of truth; the regen script crosses repo boundary to
update the Rust target. See `tools/regen/regen-macaddr.sh`.
-/

namespace Pg.Ir.Emit.Macaddr

open Pg.Ir.Emit (MacaddrCmpFamily MacaddrHashFamily macaddrCmpOps macaddrHashFamilies)

/-- Render one macaddr comparison function (eq/ne/lt/le/gt/ge). -/
def renderCmpFn (fam : MacaddrCmpFamily) : String :=
  let fnName := "macaddr_" ++ fam.suffix
  "#[no_mangle]\n" ++
  "pub unsafe extern \"C\" fn " ++ fnName ++ "(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {\n" ++
  "    let f = &mut *fcinfo;\n" ++
  "    let arg1 = decode_macaddr_p(f.args[0].value);\n" ++
  "    let arg2 = decode_macaddr_p(f.args[1].value);\n" ++
  "    let cmp_result = macaddr_cmp_internal(arg1, arg2);\n" ++
  "    encode_bool(cmp_result " ++ fam.cmpOp ++ ")\n" ++
  "}\n"

/-- Render the macaddr 3-way comparison function (macaddr_cmp). -/
def renderCmpInternal : String :=
  "#[no_mangle]\n" ++
  "pub unsafe extern \"C\" fn macaddr_cmp(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {\n" ++
  "    let f = &mut *fcinfo;\n" ++
  "    let arg1 = decode_macaddr_p(f.args[0].value);\n" ++
  "    let arg2 = decode_macaddr_p(f.args[1].value);\n" ++
  "    let cmp_result = macaddr_cmp_internal(arg1, arg2);\n" ++
  "    encode_i32(cmp_result)\n" ++
  "}\n"

/-- The macaddr_cmp_internal helper — compares high 3 bytes, then low 3 bytes. -/
def renderMacaddrCmpHelper : String :=
  "/// Mirror of Postgres' `macaddr_cmp_internal`: compares two 6-byte MAC addresses.\n" ++
  "/// Returns -1, 0, or 1.\n" ++
  "#[inline]\n" ++
  "unsafe fn macaddr_cmp_internal(arg1: *const u8, arg2: *const u8) -> i32 {\n" ++
  "    // hibits: (a<<16) | (b<<8) | c\n" ++
  "    let h1 = ((*arg1 as u32) << 16) | ((*arg1.add(1) as u32) << 8) | (*arg1.add(2) as u32);\n" ++
  "    let h2 = ((*arg2 as u32) << 16) | ((*arg2.add(1) as u32) << 8) | (*arg2.add(2) as u32);\n" ++
  "    if h1 < h2 {\n" ++
  "        return -1;\n" ++
  "    } else if h1 > h2 {\n" ++
  "        return 1;\n" ++
  "    }\n" ++
  "    // lobits: (d<<16) | (e<<8) | f\n" ++
  "    let l1 = ((*arg1.add(3) as u32) << 16) | ((*arg1.add(4) as u32) << 8) | (*arg1.add(5) as u32);\n" ++
  "    let l2 = ((*arg2.add(3) as u32) << 16) | ((*arg2.add(4) as u32) << 8) | (*arg2.add(5) as u32);\n" ++
  "    if l1 < l2 {\n" ++
  "        return -1;\n" ++
  "    } else if l1 > l2 {\n" ++
  "        return 1;\n" ++
  "    }\n" ++
  "    0\n" ++
  "}\n"

/-- Render one macaddr hash function. -/
def renderHashFn (fam : MacaddrHashFamily) : String :=
  if fam.extended then
    "#[no_mangle]\n" ++
    "pub unsafe extern \"C\" fn " ++ fam.fnName ++ "(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {\n" ++
    "    let f = &mut *fcinfo;\n" ++
    "    let key = decode_macaddr_p(f.args[0].value);\n" ++
    "    let seed: u64 = decode_i64(f.args[1].value) as u64;\n" ++
    "    encode_u64(hash_bytes_6_extended(key, seed))\n" ++
    "}\n"
  else
    "#[no_mangle]\n" ++
    "pub unsafe extern \"C\" fn " ++ fam.fnName ++ "(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {\n" ++
    "    let f = &mut *fcinfo;\n" ++
    "    let key = decode_macaddr_p(f.args[0].value);\n" ++
    "    encode_u32(hash_bytes_6(key))\n" ++
    "}\n"

/-- The full Rust source for all 9 functions. -/
def rustSource : String :=
  let header :=
    "// Generated by `rules_postgres/lean/Pg/Ir/Emit/Macaddr.lean`.\n" ++
    "// DO NOT EDIT BY HAND. Regenerate via\n" ++
    "// `rules_postgres/tools/regen/regen-macaddr.sh`.\n" ++
    "//\n" ++
    "// Source of truth: the macaddr comparison and hash cluster specs in\n" ++
    "// `Pg.Ir.Emit.MacaddrCommon`. The comparison operators delegate to\n" ++
    "// a 3-way comparison of high and low 3-byte groups (matching real Postgres'\n" ++
    "// macaddr_cmp_internal); the hash operators use Jenkins/lookup3 hashing via\n" ++
    "// pg_fcinfo's hash_bytes_6 / hash_bytes_6_extended helpers.\n" ++
    "//\n" ++
    "// 9 functions = 6 comparison ops + 1 cmp op + 2 hash ops.\n" ++
    "\n" ++
    "#![allow(clippy::missing_safety_doc)]\n" ++
    "\n" ++
    "use pg_fcinfo::{\n" ++
    "    decode_i64, decode_macaddr_p,\n" ++
    "    encode_bool, encode_i32, encode_u32, encode_u64,\n" ++
    "    hash_bytes_6, hash_bytes_6_extended,\n" ++
    "    FunctionCallInfoBaseData,\n" ++
    "};\n"
  Id.run do
    let mut s := header
    s := s ++ "\n// ─── macaddr_cmp_internal helper ──\n"
    s := s ++ "\n" ++ renderMacaddrCmpHelper
    s := s ++ "\n// ─── macaddr comparison ops (eq, ne, lt, le, gt, ge) ──\n"
    for fam in macaddrCmpOps do
      s := s ++ "\n" ++ renderCmpFn fam
    s := s ++ "\n// ─── macaddr 3-way comparison (cmp) ──\n"
    s := s ++ "\n" ++ renderCmpInternal
    s := s ++ "\n// ─── macaddr hash ops (hashmacaddr, hashmacaddrextended) ──\n"
    for fam in macaddrHashFamilies do
      s := s ++ "\n" ++ renderHashFn fam
    return s

end Pg.Ir.Emit.Macaddr

/-- `main` entrypoint: print the Rust source to stdout. -/
def main : IO Unit := IO.print Pg.Ir.Emit.Macaddr.rustSource
