import Pg.Ir.Types
import Pg.Ir.Datum
import Pg.Ir.Emit.MacaddrCommon

/-!
# Pg.Ir.Emit.MacaddrC — codegen real-style Postgres C source for macaddr cluster.

Sibling to `Pg.Ir.Emit.Macaddr` (which emits Rust). Same `MacaddrCmpFamily` and
`MacaddrHashFamily` tables from `MacaddrCommon`, but renders **Postgres-idiomatic C**
instead of Rust.

The point: produce C that's structurally identical to what's in real
`src/backend/utils/adt/mac.c` after clang preprocessing, so that an AST-level
diff between the two reveals algorithmic divergence (vs. style differences).

The real Postgres code:
  - macaddr_eq/ne/lt/le/gt/ge all call a static helper `macaddr_cmp_internal`
  - macaddr_cmp also calls the same helper
  - hashmacaddr and hashmacaddrextended call `hash_any` / `hash_any_extended`

Our Lean emit must mirror this delegation pattern, not inline the bodies.
-/

namespace Pg.Ir.Emit.MacaddrC

open Pg.Ir.Emit (MacaddrCmpFamily MacaddrHashFamily macaddrCmpOps macaddrHashFamilies)

/-- Render the static macaddr_cmp_internal helper. This mirrors Postgres' impl
which compares high 3 bytes (hibits), then low 3 bytes (lobits). -/
def renderMacaddrInternalCmp : String :=
  "static int\n" ++
  "macaddr_cmp_internal(macaddr *a1, macaddr *a2)\n" ++
  "{\n" ++
  "\tif (hibits(a1) < hibits(a2))\n" ++
  "\t\treturn -1;\n" ++
  "\telse if (hibits(a1) > hibits(a2))\n" ++
  "\t\treturn 1;\n" ++
  "\telse if (lobits(a1) < lobits(a2))\n" ++
  "\t\treturn -1;\n" ++
  "\telse if (lobits(a1) > lobits(a2))\n" ++
  "\t\treturn 1;\n" ++
  "\telse\n" ++
  "\t\treturn 0;\n" ++
  "}\n"

/-- Render one macaddr comparison function (eq/ne/lt/le/gt/ge).
These delegate to the static helper, mirroring Postgres exactly. -/
def renderCmpFn (fam : MacaddrCmpFamily) : String :=
  let fnName := "macaddr_" ++ fam.suffix
  let opStr := match fam.cmpOp with
    | "< 0"  => "<"
    | "<= 0" => "<="
    | "== 0" => "=="
    | "!= 0" => "!="
    | ">= 0" => ">="
    | "> 0"  => ">"
    | _      => "unknown_op"
  "Datum\n" ++
  fnName ++ "(PG_FUNCTION_ARGS)\n" ++
  "{\n" ++
  "\tmacaddr    *a1 = PG_GETARG_MACADDR_P(0);\n" ++
  "\tmacaddr    *a2 = PG_GETARG_MACADDR_P(1);\n" ++
  "\n" ++
  "\tPG_RETURN_BOOL(macaddr_cmp_internal(a1, a2) " ++ opStr ++ " 0);\n" ++
  "}\n"

/-- Render the macaddr_cmp function. -/
def renderCmpInternal : String :=
  "Datum\n" ++
  "macaddr_cmp(PG_FUNCTION_ARGS)\n" ++
  "{\n" ++
  "\tmacaddr    *a1 = PG_GETARG_MACADDR_P(0);\n" ++
  "\tmacaddr    *a2 = PG_GETARG_MACADDR_P(1);\n" ++
  "\n" ++
  "\tPG_RETURN_INT32(macaddr_cmp_internal(a1, a2));\n" ++
  "}\n"

/-- Render one macaddr hash function. -/
def renderHashFn (fam : MacaddrHashFamily) : String :=
  let fnName := fam.fnName
  if fam.extended then
    "Datum\n" ++
    fnName ++ "(PG_FUNCTION_ARGS)\n" ++
    "{\n" ++
    "\tmacaddr    *key = PG_GETARG_MACADDR_P(0);\n" ++
    "\n" ++
    "\treturn hash_any_extended((unsigned char *) key, sizeof(macaddr),\n" ++
    "\t\t\t\t\t\t   PG_GETARG_INT64(1));\n" ++
    "}\n"
  else
    "Datum\n" ++
    fnName ++ "(PG_FUNCTION_ARGS)\n" ++
    "{\n" ++
    "\tmacaddr    *key = PG_GETARG_MACADDR_P(0);\n" ++
    "\n" ++
    "\treturn hash_any((unsigned char *) key, sizeof(macaddr));\n" ++
    "}\n"

/-- The full C source. -/
def cSource : String :=
  let header :=
    "/* Generated by `rules_postgres/lean/Pg/Ir/Emit/MacaddrC.lean`. */\n" ++
    "/* DO NOT EDIT BY HAND. Regenerate via */\n" ++
    "/* `rules_postgres/tools/regen/regen-macaddr.sh`. */\n" ++
    "\n" ++
    "/* Real-PG-style C for AST grounding. clang -ast-dump=json this\n" ++
    " * file with real Postgres' headers, then diff against the AST\n" ++
    " * for `src/backend/utils/adt/mac.c`. The shared header set is\n" ++
    " * what makes `macaddr`, `PG_GETARG_MACADDR_P`, etc. resolve to\n" ++
    " * the same types/macros on both sides, so the diff captures\n" ++
    " * algorithmic divergence rather than per-translation-unit type\n" ++
    " * resolution noise. */\n" ++
    "#include \"postgres.h\"\n" ++
    "#include \"common/hashfn.h\"\n" ++
    "#include \"utils/fmgrprotos.h\"\n" ++
    "#include \"utils/inet.h\"\n" ++
    "\n" ++
    "/*\n" ++
    " *\tUtility macros used for sorting and comparing:\n" ++
    " */\n" ++
    "\n" ++
    "#define hibits(addr) \\\n" ++
    "  ((unsigned long)(((addr)->a<<16)|((addr)->b<<8)|((addr)->c)))\n" ++
    "\n" ++
    "#define lobits(addr) \\\n" ++
    "  ((unsigned long)(((addr)->d<<16)|((addr)->e<<8)|((addr)->f)))\n" ++
    "\n" ++
    "/* Forward declaration of the static helper. */\n" ++
    "static int macaddr_cmp_internal(macaddr *a1, macaddr *a2);\n" ++
    "\n"
  Id.run do
    let mut s := header
    s := s ++ renderMacaddrInternalCmp
    s := s ++ "\n"
    for fam in macaddrCmpOps do
      s := s ++ "\n" ++ renderCmpFn fam
    s := s ++ "\n" ++ renderCmpInternal
    s := s ++ "\n"
    for fam in macaddrHashFamilies do
      s := s ++ "\n" ++ renderHashFn fam
    return s

end Pg.Ir.Emit.MacaddrC

/-- `main` entrypoint: print the C source to stdout. -/
def main : IO Unit := IO.print Pg.Ir.Emit.MacaddrC.cSource
