import Pg.Ir.Emit.TextCommon

/-!
# Pg.Ir.Emit.TextC — emit real-style Postgres C for the text cluster
(AST grounding companion to Text.lean).
-/

namespace Pg.Ir.Emit.Text.C

open Pg.Ir.Emit.Text (TextBody TextFamily families)

def renderCInternal (fam : TextFamily) : Option String :=
  match fam.body with
  | .catenate => some (
      "static text *\n" ++
      "text_catenate(text *t1, text *t2)\n" ++
      "{\n" ++
      "\ttext\t   *result;\n" ++
      "\tint\t\t\tlen1,\n" ++
      "\t\t\t\tlen2,\n" ++
      "\t\t\t\tlen;\n" ++
      "\tchar\t   *ptr;\n" ++
      "\n" ++
      "\tlen1 = VARSIZE_ANY_EXHDR(t1);\n" ++
      "\tlen2 = VARSIZE_ANY_EXHDR(t2);\n" ++
      "\n" ++
      "\t/* paranoia ... probably should throw error instead? */\n" ++
      "\tif (len1 < 0)\n" ++
      "\t\tlen1 = 0;\n" ++
      "\tif (len2 < 0)\n" ++
      "\t\tlen2 = 0;\n" ++
      "\n" ++
      "\tlen = len1 + len2 + VARHDRSZ;\n" ++
      "\tresult = (text *) palloc(len);\n" ++
      "\n" ++
      "\t/* Set size of result string... */\n" ++
      "\tSET_VARSIZE(result, len);\n" ++
      "\n" ++
      "\t/* Fill data field of result string... */\n" ++
      "\tptr = VARDATA(result);\n" ++
      "\tif (len1 > 0)\n" ++
      "\t\tmemcpy(ptr, VARDATA_ANY(t1), len1);\n" ++
      "\tif (len2 > 0)\n" ++
      "\t\tmemcpy(ptr + len1, VARDATA_ANY(t2), len2);\n" ++
      "\n" ++
      "\treturn result;\n" ++
      "}\n")

def renderCFmgrStub (fam : TextFamily) : String :=
  let body :=
    match fam.body with
    | .catenate =>
        "\ttext\t   *t1 = PG_GETARG_TEXT_PP(0);\n" ++
        "\ttext\t   *t2 = PG_GETARG_TEXT_PP(1);\n" ++
        "\n" ++
        "\tPG_RETURN_TEXT_P(text_catenate(t1, t2));\n"
  "Datum\n" ++
  fam.fnName ++ "(PG_FUNCTION_ARGS)\n" ++
  "{\n" ++
  body ++
  "}\n"

def cSource : String :=
  let header :=
    "/*\n" ++
    " * Generated by `rules_postgres/lean/Pg/Ir/Emit/TextC.lean`.\n" ++
    " * DO NOT EDIT BY HAND.\n" ++
    " */\n" ++
    "\n" ++
    "#include \"postgres.h\"\n" ++
    "#include <string.h>\n" ++
    "#include \"utils/fmgrprotos.h\"\n" ++
    "#include \"utils/varlena.h\"\n"
  Id.run do
    let mut s := header
    for fam in families do
      match renderCInternal fam with
      | some internal => s := s ++ "\n" ++ internal ++ "\n" ++ renderCFmgrStub fam
      | none          => s := s ++ "\n" ++ renderCFmgrStub fam
    return s

end Pg.Ir.Emit.Text.C

def main : IO Unit := IO.print Pg.Ir.Emit.Text.C.cSource
