import Pg.Ir.Emit.TextCommon

/-!
# Pg.Ir.Emit.Text — Rust emit for the text cluster.

Emits two definitions per family:
  1. The `<fn>_catenate`-style static internal helper (the algorithm).
  2. The fmgr stub `<fn>(fcinfo)` (decode args + delegate + return).

Text reuses bytea's varlena helpers at the Datum level.
-/

namespace Pg.Ir.Emit.Text.Rust

open Pg.Ir.Emit.Text (TextBody TextFamily families)

/-- For `catenate` we emit a `<fn>_catenate` static helper. -/
def renderInternal (fam : TextFamily) : Option String :=
  match fam.body with
  | .catenate => some (
      "unsafe fn text_catenate(t1: *const u8, t2: *const u8) -> *mut u8 {\n" ++
      "    let len1 = varsize_any_exhdr(t1);\n" ++
      "    let len2 = varsize_any_exhdr(t2);\n" ++
      "\n" ++
      "    let total = len1 + len2 + VARHDRSZ;\n" ++
      "    let result = palloc(total);\n" ++
      "\n" ++
      "    set_varsize_4b(result, total);\n" ++
      "\n" ++
      "    let payload = vardata_4b_mut(result);\n" ++
      "    if len1 > 0 {\n" ++
      "        std::ptr::copy_nonoverlapping(vardata_any(t1), payload, len1);\n" ++
      "    }\n" ++
      "    if len2 > 0 {\n" ++
      "        std::ptr::copy_nonoverlapping(vardata_any(t2), payload.add(len1), len2);\n" ++
      "    }\n" ++
      "\n" ++
      "    result\n" ++
      "}\n")

def renderFmgrStub (fam : TextFamily) : String :=
  match fam.body with
  | .catenate =>
      "#[no_mangle]\n" ++
      "pub unsafe extern \"C\" fn " ++ fam.fnName ++
        "(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {\n" ++
      "    let f = &mut *fcinfo;\n" ++
      "    let t1 = decode_bytea_p(f.args[0].value);\n" ++
      "    let t2 = decode_bytea_p(f.args[1].value);\n" ++
      "    encode_bytea_p(text_catenate(t1, t2))\n" ++
      "}\n"

def rustSource : String :=
  let header :=
    "// Generated by `rules_postgres/lean/Pg/Ir/Emit/Text.lean`.\n" ++
    "// DO NOT EDIT BY HAND. Regenerate via\n" ++
    "// `rules_postgres/tools/regen/regen-text.sh`.\n" ++
    "//\n" ++
    "// Second varlena-using Pg.Ir cluster. Text reuses bytea's varlena\n" ++
    "// codec at the Datum level. Each family emits a pair:\n" ++
    "//   1. A static internal helper (the algorithm).\n" ++
    "//   2. The V1 fmgr stub (decode args + delegate + return).\n" ++
    "\n" ++
    "#![allow(clippy::missing_safety_doc)]\n" ++
    "\n" ++
    "use pg_fcinfo::{\n" ++
    "    decode_bytea_p, encode_bytea_p,\n" ++
    "    set_varsize_4b,\n" ++
    "    vardata_4b_mut, vardata_any, varsize_any_exhdr,\n" ++
    "    FunctionCallInfoBaseData, VARHDRSZ,\n" ++
    "};\n" ++
    "use pg_palloc::palloc;\n"
  Id.run do
    let mut s := header
    for fam in families do
      match renderInternal fam with
      | some internal => s := s ++ "\n" ++ internal ++ "\n" ++ renderFmgrStub fam
      | none          => s := s ++ "\n" ++ renderFmgrStub fam
    return s

end Pg.Ir.Emit.Text.Rust

def main : IO Unit := IO.print Pg.Ir.Emit.Text.Rust.rustSource
