import Pg.Ir.Types
import Pg.Ir.Datum
import Pg.Ir.Emit.TidCommon

/-!
# Pg.Ir.Emit.Tid — codegen the tid cmp + hash cluster as Rust source.

Generates the Rust functions for tid comparison and hashing from the specs
in `Pg.Ir.Emit.TidCommon` instantiated at the Postgres tid (ItemPointer) type.

10 Rust functions total = 6 comparison ops + 1 cmp op + 2 clamp ops + 2 hash ops.

The codegen mirrors the `Pg.Ir.Emit.Macaddr` pattern:
template + per-family metadata. The emitted Rust calls into `pg_fcinfo` helpers
for decoding tid (6-byte pointers) and hashing (Jenkins/lookup3).

This file is the source of truth; the regen script crosses repo boundary to
update the Rust target. See `tools/regen/regen-tid.sh`.
-/

namespace Pg.Ir.Emit.Tid

open Pg.Ir.Emit (TidCmpFamily TidClampFamily TidHashFamily tidCmpOps tidClampFamilies tidHashFamilies)

/-- Render one tid comparison function (eq/ne/lt/le/gt/ge). -/
def renderCmpFn (fam : TidCmpFamily) : String :=
  let fnName := "tid" ++ fam.suffix
  "#[no_mangle]\n" ++
  "pub unsafe extern \"C\" fn " ++ fnName ++ "(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {\n" ++
  "    let f = &mut *fcinfo;\n" ++
  "    let arg1 = decode_itempointer_p(f.args[0].value);\n" ++
  "    let arg2 = decode_itempointer_p(f.args[1].value);\n" ++
  "    let cmp_result = itempointer_cmp_internal(arg1, arg2);\n" ++
  "    encode_bool(cmp_result " ++ fam.cmpOp ++ ")\n" ++
  "}\n"

/-- Render the tid 3-way comparison function (bttidcmp). -/
def renderCmpInternal : String :=
  "#[no_mangle]\n" ++
  "pub unsafe extern \"C\" fn bttidcmp(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {\n" ++
  "    let f = &mut *fcinfo;\n" ++
  "    let arg1 = decode_itempointer_p(f.args[0].value);\n" ++
  "    let arg2 = decode_itempointer_p(f.args[1].value);\n" ++
  "    let cmp_result = itempointer_cmp_internal(arg1, arg2);\n" ++
  "    encode_i32(cmp_result)\n" ++
  "}\n"

/-- The itempointer_cmp_internal helper — compares block first, then offset. -/
def renderItemPointerCmpHelper : String :=
  "/// Mirror of Postgres' `ItemPointerCompare`: compares two 6-byte ItemPointers.\n" ++
  "/// Returns -1, 0, or 1.\n" ++
  "#[inline]\n" ++
  "unsafe fn itempointer_cmp_internal(arg1: *const u8, arg2: *const u8) -> i32 {\n" ++
  "    // BlockIdData = { bi_hi: u16, bi_lo: u16 } with block number =\n" ++
  "    // (bi_hi << 16) | bi_lo. bi_hi sits at offset 0-1, bi_lo at 2-3,\n" ++
  "    // both as native (little-endian) u16. Reading bytes 0-3 as a\n" ++
  "    // single LE u32 would compare in the wrong byte order.\n" ++
  "    let b1_hi = u16::from_le_bytes([*arg1, *arg1.add(1)]) as u32;\n" ++
  "    let b1_lo = u16::from_le_bytes([*arg1.add(2), *arg1.add(3)]) as u32;\n" ++
  "    let b1 = (b1_hi << 16) | b1_lo;\n" ++
  "    let b2_hi = u16::from_le_bytes([*arg2, *arg2.add(1)]) as u32;\n" ++
  "    let b2_lo = u16::from_le_bytes([*arg2.add(2), *arg2.add(3)]) as u32;\n" ++
  "    let b2 = (b2_hi << 16) | b2_lo;\n" ++
  "    if b1 < b2 {\n" ++
  "        return -1;\n" ++
  "    } else if b1 > b2 {\n" ++
  "        return 1;\n" ++
  "    }\n" ++
  "    // OffsetNumber: bytes 4-5 (little-endian u16)\n" ++
  "    let o1 = u16::from_le_bytes([*arg1.add(4), *arg1.add(5)]);\n" ++
  "    let o2 = u16::from_le_bytes([*arg2.add(4), *arg2.add(5)]);\n" ++
  "    if o1 < o2 {\n" ++
  "        return -1;\n" ++
  "    } else if o1 > o2 {\n" ++
  "        return 1;\n" ++
  "    }\n" ++
  "    0\n" ++
  "}\n"

/-- Render one tid clamp function (tidlarger/tidsmaller). -/
def renderClampFn (fam : TidClampFamily) : String :=
  let fnName := fam.fnName
  "#[no_mangle]\n" ++
  "pub unsafe extern \"C\" fn " ++ fnName ++ "(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {\n" ++
  "    let f = &mut *fcinfo;\n" ++
  "    let arg1 = decode_itempointer_p(f.args[0].value);\n" ++
  "    let arg2 = decode_itempointer_p(f.args[1].value);\n" ++
  "    let cmp_result = itempointer_cmp_internal(arg1, arg2);\n" ++
  "    let result = if cmp_result " ++ fam.cmpOp ++ " { arg1 } else { arg2 };\n" ++
  "    encode_itempointer(result)\n" ++
  "}\n"

/-- Render one tid hash function. -/
def renderHashFn (fam : TidHashFamily) : String :=
  if fam.extended then
    "#[no_mangle]\n" ++
    "pub unsafe extern \"C\" fn " ++ fam.fnName ++ "(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {\n" ++
    "    let f = &mut *fcinfo;\n" ++
    "    let key = decode_itempointer_p(f.args[0].value);\n" ++
    "    let seed: u64 = decode_i64(f.args[1].value) as u64;\n" ++
    "    encode_u64(hash_bytes_6_extended(key, seed))\n" ++
    "}\n"
  else
    "#[no_mangle]\n" ++
    "pub unsafe extern \"C\" fn " ++ fam.fnName ++ "(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {\n" ++
    "    let f = &mut *fcinfo;\n" ++
    "    let key = decode_itempointer_p(f.args[0].value);\n" ++
    "    encode_u32(hash_bytes_6(key))\n" ++
    "}\n"

/-- The full Rust source for all 10 functions. -/
def rustSource : String :=
  let header :=
    "// Generated by `rules_postgres/lean/Pg/Ir/Emit/Tid.lean`.\n" ++
    "// DO NOT EDIT BY HAND. Regenerate via\n" ++
    "// `rules_postgres/tools/regen/regen-tid.sh`.\n" ++
    "//\n" ++
    "// Source of truth: the tid comparison, clamping and hash cluster specs in\n" ++
    "// `Pg.Ir.Emit.TidCommon`. The comparison operators delegate to\n" ++
    "// a 3-way comparison of block number then offset number (matching real Postgres'\n" ++
    "// ItemPointerCompare); the clamping operators return the larger/smaller pointer;\n" ++
    "// the hash operators use Jenkins/lookup3 hashing via pg_fcinfo's\n" ++
    "// hash_bytes_6 / hash_bytes_6_extended helpers.\n" ++
    "//\n" ++
    "// 10 functions = 6 comparison ops + 1 cmp op + 2 clamp ops + 2 hash ops.\n" ++
    "\n" ++
    "#![allow(clippy::missing_safety_doc)]\n" ++
    "\n" ++
    "use pg_fcinfo::{\n" ++
    "    decode_i64, decode_itempointer_p,\n" ++
    "    encode_bool, encode_i32, encode_u32, encode_u64, encode_itempointer,\n" ++
    "    hash_bytes_6, hash_bytes_6_extended,\n" ++
    "    FunctionCallInfoBaseData,\n" ++
    "};\n"
  Id.run do
    let mut s := header
    s := s ++ "\n// ─── itempointer_cmp_internal helper ──\n"
    s := s ++ "\n" ++ renderItemPointerCmpHelper
    s := s ++ "\n// ─── tid comparison ops (tideq, tidne, tidlt, tidle, tidgt, tidge) ──\n"
    for fam in tidCmpOps do
      s := s ++ "\n" ++ renderCmpFn fam
    s := s ++ "\n// ─── tid 3-way comparison (bttidcmp) ──\n"
    s := s ++ "\n" ++ renderCmpInternal
    s := s ++ "\n// ─── tid clamping ops (tidlarger, tidsmaller) ──\n"
    for fam in tidClampFamilies do
      s := s ++ "\n" ++ renderClampFn fam
    s := s ++ "\n// ─── tid hash ops (hashtid, hashtidextended) ──\n"
    for fam in tidHashFamilies do
      s := s ++ "\n" ++ renderHashFn fam
    return s

end Pg.Ir.Emit.Tid

/-- `main` entrypoint: print the Rust source to stdout. -/
def main : IO Unit := IO.print Pg.Ir.Emit.Tid.rustSource
