import Pg.Ir.Types
import Pg.Ir.Datum
import Pg.Ir.Emit.UuidCommon

/-!
# Pg.Ir.Emit.UuidC — codegen real-style Postgres C source for UUID cluster.

Sibling to `Pg.Ir.Emit.Uuid` (which emits Rust). Same `UuidCmpFamily` and
`UuidHashFamily` tables from `UuidCommon`, but renders **Postgres-idiomatic C**
instead of Rust.

The point: produce C that's structurally identical to what's in real
`src/backend/utils/adt/uuid.c` after clang preprocessing, so that an AST-level
diff between the two reveals algorithmic divergence (vs. style differences).

The real Postgres code:
  - uuid_eq/ne/lt/le/gt/ge all call a static helper `uuid_internal_cmp`
  - uuid_cmp also calls the same helper
  - uuid_hash and uuid_hash_extended call `hash_any` / `hash_any_extended`

Our Lean emit must mirror this delegation pattern, not inline the bodies.
-/

namespace Pg.Ir.Emit.UuidC

open Pg.Ir.Emit (UuidCmpFamily UuidHashFamily uuidCmpOps uuidHashFamilies)

/-- Render the static uuid_internal_cmp helper. This mirrors Postgres' impl
which just memcmps the 16-byte payloads. -/
def renderUuidInternalCmp : String :=
  "static int\n" ++
  "uuid_internal_cmp(const pg_uuid_t *arg1, const pg_uuid_t *arg2)\n" ++
  "{\n" ++
  "\treturn memcmp(arg1->data, arg2->data, UUID_LEN);\n" ++
  "}\n"

/-- Render one UUID comparison function (eq/ne/lt/le/gt/ge).
These delegate to the static helper, mirroring Postgres exactly. -/
def renderCmpFn (fam : UuidCmpFamily) : String :=
  let fnName := "uuid_" ++ fam.suffix
  let opStr := match fam.cmpOp with
    | "< 0"  => "<"
    | "<= 0" => "<="
    | "== 0" => "=="
    | "!= 0" => "!="
    | ">= 0" => ">="
    | "> 0"  => ">"
    | _      => "unknown_op"
  "Datum\n" ++
  fnName ++ "(PG_FUNCTION_ARGS)\n" ++
  "{\n" ++
  "\tpg_uuid_t  *arg1 = PG_GETARG_UUID_P(0);\n" ++
  "\tpg_uuid_t  *arg2 = PG_GETARG_UUID_P(1);\n" ++
  "\n" ++
  "\tPG_RETURN_BOOL(uuid_internal_cmp(arg1, arg2) " ++ opStr ++ " 0);\n" ++
  "}\n"

/-- Render the uuid_cmp function. -/
def renderCmpInternal : String :=
  "Datum\n" ++
  "uuid_cmp(PG_FUNCTION_ARGS)\n" ++
  "{\n" ++
  "\tpg_uuid_t  *arg1 = PG_GETARG_UUID_P(0);\n" ++
  "\tpg_uuid_t  *arg2 = PG_GETARG_UUID_P(1);\n" ++
  "\n" ++
  "\tPG_RETURN_INT32(uuid_internal_cmp(arg1, arg2));\n" ++
  "}\n"

/-- Render one UUID hash function. -/
def renderHashFn (fam : UuidHashFamily) : String :=
  let fnName := fam.fnName
  if fam.extended then
    "Datum\n" ++
    fnName ++ "(PG_FUNCTION_ARGS)\n" ++
    "{\n" ++
    "\tpg_uuid_t  *key = PG_GETARG_UUID_P(0);\n" ++
    "\n" ++
    "\treturn hash_any_extended(key->data, UUID_LEN, PG_GETARG_INT64(1));\n" ++
    "}\n"
  else
    "Datum\n" ++
    fnName ++ "(PG_FUNCTION_ARGS)\n" ++
    "{\n" ++
    "\tpg_uuid_t  *key = PG_GETARG_UUID_P(0);\n" ++
    "\n" ++
    "\treturn hash_any(key->data, UUID_LEN);\n" ++
    "}\n"

/-- The full C source. -/
def cSource : String :=
  let header :=
    "/* Generated by `rules_postgres/lean/Pg/Ir/Emit/UuidC.lean`. */\n" ++
    "/* DO NOT EDIT BY HAND. Regenerate via */\n" ++
    "/* `rules_postgres/tools/regen/regen-uuid.sh`. */\n" ++
    "\n" ++
    "/* Real-PG-style C for AST grounding. clang -ast-dump=json this\n" ++
    " * file with real Postgres' headers, then diff against the AST\n" ++
    " * for `src/backend/utils/adt/uuid.c`. The shared header set is\n" ++
    " * what makes `pg_uuid_t`, `PG_GETARG_UUID_P`, etc. resolve to\n" ++
    " * the same types/macros on both sides, so the diff captures\n" ++
    " * algorithmic divergence rather than per-translation-unit type\n" ++
    " * resolution noise. */\n" ++
    "#include \"postgres.h\"\n" ++
    "#include <string.h>\n" ++
    "#include \"common/hashfn.h\"\n" ++
    "#include \"utils/fmgrprotos.h\"\n" ++
    "#include \"utils/uuid.h\"\n" ++
    "\n" ++
    "/* Forward declaration of the static helper. */\n" ++
    "static int uuid_internal_cmp(const pg_uuid_t *arg1, const pg_uuid_t *arg2);\n" ++
    "\n"
  Id.run do
    let mut s := header
    s := s ++ renderUuidInternalCmp
    s := s ++ "\n"
    for fam in uuidCmpOps do
      s := s ++ "\n" ++ renderCmpFn fam
    s := s ++ "\n" ++ renderCmpInternal
    s := s ++ "\n"
    for fam in uuidHashFamilies do
      s := s ++ "\n" ++ renderHashFn fam
    return s

end Pg.Ir.Emit.UuidC

/-- `main` entrypoint: print the C source to stdout. -/
def main : IO Unit := IO.print Pg.Ir.Emit.UuidC.cSource
