import Pg.Ir.Types
import Pg.Ir.Datum
import Pg.Ir.Emit.UuidCommon

/-!
# Pg.Ir.Emit.Uuid — codegen the UUID cmp + hash cluster as Rust source.

Generates the Rust functions for UUID comparison and hashing from the specs
in `Pg.Ir.Emit.UuidCommon` instantiated at the Postgres UUID type.

9 Rust functions total = 6 comparison ops + 2 hash ops + 1 cmp op.

The codegen mirrors the `Pg.Ir.Emit.IntCmp` / `Pg.Ir.Emit.IntHash` pattern:
template + per-family metadata. The emitted Rust calls into `pg_fcinfo` helpers
for decoding UUIDs (16-byte pointers) and hashing (Jenkins/lookup3).

This file is the source of truth; the regen script crosses repo boundary to
update the Rust target. See `tools/regen/regen-uuid.sh`.
-/

namespace Pg.Ir.Emit.Uuid

open Pg.Ir.Emit (UuidCmpFamily UuidHashFamily uuidCmpOps uuidHashFamilies)

/-- Render one UUID comparison function (eq/ne/lt/le/gt/ge). -/
def renderCmpFn (fam : UuidCmpFamily) : String :=
  let fnName := "uuid_" ++ fam.suffix
  "#[no_mangle]\n" ++
  "pub unsafe extern \"C\" fn " ++ fnName ++ "(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {\n" ++
  "    let f = &mut *fcinfo;\n" ++
  "    let arg1 = decode_uuid_p(f.args[0].value);\n" ++
  "    let arg2 = decode_uuid_p(f.args[1].value);\n" ++
  "    let cmp_result = unsafe {\n" ++
  "        libc::memcmp(arg1 as *const libc::c_void, arg2 as *const libc::c_void, 16)\n" ++
  "    };\n" ++
  "    encode_bool(cmp_result " ++ fam.cmpOp ++ ")\n" ++
  "}\n"

/-- Render the UUID 3-way comparison function (uuid_cmp). -/
def renderCmpInternal : String :=
  "#[no_mangle]\n" ++
  "pub unsafe extern \"C\" fn uuid_cmp(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {\n" ++
  "    let f = &mut *fcinfo;\n" ++
  "    let arg1 = decode_uuid_p(f.args[0].value);\n" ++
  "    let arg2 = decode_uuid_p(f.args[1].value);\n" ++
  "    let cmp_result = unsafe {\n" ++
  "        libc::memcmp(arg1 as *const libc::c_void, arg2 as *const libc::c_void, 16)\n" ++
  "    };\n" ++
  "    encode_i32(cmp_result as i32)\n" ++
  "}\n"

/-- Render one UUID hash function. -/
def renderHashFn (fam : UuidHashFamily) : String :=
  if fam.extended then
    "#[no_mangle]\n" ++
    "pub unsafe extern \"C\" fn " ++ fam.fnName ++ "(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {\n" ++
    "    let f = &mut *fcinfo;\n" ++
    "    let key = decode_uuid_p(f.args[0].value);\n" ++
    "    let seed: u64 = decode_i64(f.args[1].value) as u64;\n" ++
    "    encode_u64(hash_bytes_16_extended(key, seed))\n" ++
    "}\n"
  else
    "#[no_mangle]\n" ++
    "pub unsafe extern \"C\" fn " ++ fam.fnName ++ "(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {\n" ++
    "    let f = &mut *fcinfo;\n" ++
    "    let key = decode_uuid_p(f.args[0].value);\n" ++
    "    encode_u32(hash_bytes_16(key))\n" ++
    "}\n"

/-- The full Rust source for all 9 functions. -/
def rustSource : String :=
  let header :=
    "// Generated by `rules_postgres/lean/Pg/Ir/Emit/Uuid.lean`.\n" ++
    "// DO NOT EDIT BY HAND. Regenerate via\n" ++
    "// `rules_postgres/tools/regen/regen-uuid.sh`.\n" ++
    "//\n" ++
    "// Source of truth: the UUID comparison and hash cluster specs in\n" ++
    "// `Pg.Ir.Emit.UuidCommon`. The comparison operators delegate to\n" ++
    "// a memcmp-based comparison (matching real Postgres' uuid_internal_cmp);\n" ++
    "// the hash operators use Jenkins/lookup3 hashing via pg_fcinfo's\n" ++
    "// hash_bytes_16 / hash_bytes_16_extended helpers.\n" ++
    "//\n" ++
    "// 9 functions = 6 comparison ops + 1 cmp op + 2 hash ops.\n" ++
    "\n" ++
    "#![allow(clippy::missing_safety_doc)]\n" ++
    "\n" ++
    "use pg_fcinfo::{\n" ++
    "    decode_i64, decode_uuid_p,\n" ++
    "    encode_bool, encode_i32, encode_u32, encode_u64,\n" ++
    "    hash_bytes_16, hash_bytes_16_extended,\n" ++
    "    FunctionCallInfoBaseData,\n" ++
    "};\n"
  Id.run do
    let mut s := header
    s := s ++ "\n// ─── UUID comparison ops (eq, ne, lt, le, gt, ge) ──\n"
    for fam in uuidCmpOps do
      s := s ++ "\n" ++ renderCmpFn fam
    s := s ++ "\n// ─── UUID 3-way comparison (cmp) ──\n"
    s := s ++ "\n" ++ renderCmpInternal
    s := s ++ "\n// ─── UUID hash ops (hash, hash_extended) ──\n"
    for fam in uuidHashFamilies do
      s := s ++ "\n" ++ renderHashFn fam
    return s

end Pg.Ir.Emit.Uuid

/-- `main` entrypoint: print the Rust source to stdout. -/
def main : IO Unit := IO.print Pg.Ir.Emit.Uuid.rustSource
