# @generated by rules_jsonschema//tools/schema_to_starlark. DO NOT EDIT.
#
# Source schema: compose-spec.json
#
# Refresh via the generating rule's `update` script;
# the diff_test will fail until you do.

load("@rules_jsonschema//runtime:helpers.bzl", "parse_json_or_none", "strip_empty")

ComposeServiceInfo = provider(
    doc = "A service contributed by a target. Shard JSON matches the service schema.",
    fields = {
        "service_name": "string: top-level key for this service in the rendered project.",
        "json": "File: the JSON shard.",
    },
)

def _docker_compose_service_impl(ctx):
    item_name = ctx.attr.service_name or ctx.label.name
    payload = {
        "annotations": ctx.attr.annotations,
        "attach": ctx.attr.attach,
        "blkio_config": parse_json_or_none(ctx.attr.blkio_config),
        "build": parse_json_or_none(ctx.attr.build),
        "cap_add": ctx.attr.cap_add,
        "cap_drop": ctx.attr.cap_drop,
        "cgroup": ctx.attr.cgroup,
        "cgroup_parent": ctx.attr.cgroup_parent,
        "command": ctx.attr.command,
        "configs": ctx.attr.configs,
        "container_name": ctx.attr.container_name,
        "cpu_count": parse_json_or_none(ctx.attr.cpu_count),
        "cpu_percent": parse_json_or_none(ctx.attr.cpu_percent),
        "cpu_period": ctx.attr.cpu_period,
        "cpu_quota": ctx.attr.cpu_quota,
        "cpu_rt_period": ctx.attr.cpu_rt_period,
        "cpu_rt_runtime": ctx.attr.cpu_rt_runtime,
        "cpu_shares": ctx.attr.cpu_shares,
        "cpus": ctx.attr.cpus,
        "cpuset": ctx.attr.cpuset,
        "credential_spec": parse_json_or_none(ctx.attr.credential_spec),
        "depends_on": ctx.attr.depends_on,
        "deploy": parse_json_or_none(ctx.attr.deploy),
        "develop": parse_json_or_none(ctx.attr.develop),
        "device_cgroup_rules": ctx.attr.device_cgroup_rules,
        "devices": ctx.attr.devices,
        "dns": ctx.attr.dns,
        "dns_opt": ctx.attr.dns_opt,
        "dns_search": ctx.attr.dns_search,
        "domainname": ctx.attr.domainname,
        "entrypoint": ctx.attr.entrypoint,
        "env_file": ctx.attr.env_file,
        "environment": ctx.attr.environment,
        "expose": parse_json_or_none(ctx.attr.expose),
        "extends": parse_json_or_none(ctx.attr.extends),
        "external_links": ctx.attr.external_links,
        "extra_hosts": ctx.attr.extra_hosts,
        "gpus": parse_json_or_none(ctx.attr.gpus),
        "group_add": parse_json_or_none(ctx.attr.group_add),
        "healthcheck": parse_json_or_none(ctx.attr.healthcheck),
        "hostname": ctx.attr.hostname,
        "image": ctx.attr.image,
        "init": ctx.attr.init,
        "ipc": ctx.attr.ipc,
        "isolation": ctx.attr.isolation,
        "label_file": ctx.attr.label_file,
        "labels": ctx.attr.labels,
        "links": ctx.attr.links,
        "logging": parse_json_or_none(ctx.attr.logging),
        "mac_address": ctx.attr.mac_address,
        "mem_limit": ctx.attr.mem_limit,
        "mem_reservation": ctx.attr.mem_reservation,
        "mem_swappiness": ctx.attr.mem_swappiness,
        "memswap_limit": ctx.attr.memswap_limit,
        "models": ctx.attr.models,
        "network_mode": ctx.attr.network_mode,
        "networks": ctx.attr.networks,
        "oom_kill_disable": ctx.attr.oom_kill_disable,
        "oom_score_adj": parse_json_or_none(ctx.attr.oom_score_adj),
        "pid": ctx.attr.pid,
        "pids_limit": ctx.attr.pids_limit,
        "platform": ctx.attr.platform,
        "ports": ctx.attr.ports,
        "post_start": parse_json_or_none(ctx.attr.post_start),
        "pre_stop": parse_json_or_none(ctx.attr.pre_stop),
        "privileged": ctx.attr.privileged,
        "profiles": ctx.attr.profiles,
        "provider": parse_json_or_none(ctx.attr.provider),
        "pull_policy": ctx.attr.pull_policy,
        "pull_refresh_after": ctx.attr.pull_refresh_after,
        "read_only": ctx.attr.read_only,
        "restart": ctx.attr.restart,
        "runtime": ctx.attr.runtime,
        "scale": ctx.attr.scale,
        "secrets": ctx.attr.secrets,
        "security_opt": ctx.attr.security_opt,
        "shm_size": ctx.attr.shm_size,
        "stdin_open": ctx.attr.stdin_open,
        "stop_grace_period": ctx.attr.stop_grace_period,
        "stop_signal": ctx.attr.stop_signal,
        "storage_opt": parse_json_or_none(ctx.attr.storage_opt),
        "sysctls": ctx.attr.sysctls,
        "tmpfs": ctx.attr.tmpfs,
        "tty": ctx.attr.tty,
        "ulimits": parse_json_or_none(ctx.attr.ulimits),
        "use_api_socket": ctx.attr.use_api_socket,
        "user": ctx.attr.user,
        "userns_mode": ctx.attr.userns_mode,
        "uts": ctx.attr.uts,
        "volumes": ctx.attr.volumes,
        "volumes_from": ctx.attr.volumes_from,
        "working_dir": ctx.attr.working_dir,
    }
    payload = strip_empty(payload)
    shard = ctx.actions.declare_file(ctx.label.name + ".service.json")
    ctx.actions.write(shard, json.encode(payload))
    return [
        DefaultInfo(files = depset([shard])),
        ComposeServiceInfo(service_name = item_name, json = shard),
    ]

docker_compose_service = rule(
    implementation = _docker_compose_service_impl,
    doc = "Configuration for a service.",
    provides = [ComposeServiceInfo],
    attrs = {
        "service_name": attr.string(
            doc = "Top-level key for this service in the rendered project. Defaults to the rule name.",
        ),
        "annotations": attr.string_dict(),
        "attach": attr.bool(),
        "blkio_config": attr.string(
            doc = "Block IO configuration for the service. (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "build": attr.string(
            doc = "Configuration options for building the service's image. (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "cap_add": attr.string_list(
            doc = "Add Linux capabilities. For example, 'CAP_SYS_ADMIN', 'SYS_ADMIN', or 'NET_ADMIN'.",
        ),
        "cap_drop": attr.string_list(
            doc = "Drop Linux capabilities. For example, 'CAP_SYS_ADMIN', 'SYS_ADMIN', or 'NET_ADMIN'.",
        ),
        "cgroup": attr.string(
            values = ["host", "private"],
            doc = "Specify the cgroup namespace to join. Use 'host' to use the host's cgroup namespace, or 'private' to use a private cgroup namespace.",
        ),
        "cgroup_parent": attr.string(
            doc = "Specify an optional parent cgroup for the container.",
        ),
        "command": attr.string_list(
            doc = "Override the default command declared by the container image, for example 'CMD' in Dockerfile.",
        ),
        "configs": attr.string_list(
            doc = "Grant access to Configs on a per-service basis.",
        ),
        "container_name": attr.string(
            doc = "Specify a custom container name, rather than a generated default name.",
        ),
        "cpu_count": attr.string(
            doc = "Number of usable CPUs. (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "cpu_percent": attr.string(
            doc = "Percentage of CPU resources to use. (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "cpu_period": attr.string(
            doc = "Limit the CPU CFS (Completely Fair Scheduler) period.",
        ),
        "cpu_quota": attr.string(
            doc = "Limit the CPU CFS (Completely Fair Scheduler) quota.",
        ),
        "cpu_rt_period": attr.string(
            doc = "Limit the CPU real-time period in microseconds or a duration.",
        ),
        "cpu_rt_runtime": attr.string(
            doc = "Limit the CPU real-time runtime in microseconds or a duration.",
        ),
        "cpu_shares": attr.string(
            doc = "CPU shares (relative weight) for the container.",
        ),
        "cpus": attr.string(
            doc = "Number of CPUs to use. A floating-point value is supported to request partial CPUs.",
        ),
        "cpuset": attr.string(
            doc = "CPUs in which to allow execution (0-3, 0,1).",
        ),
        "credential_spec": attr.string(
            doc = "Configure the credential spec for managed service account. (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "depends_on": attr.string_list(
            doc = "Express dependency between services. Service dependencies cause services to be started in dependency order. The dependent service will wait for the dependency to be ready before starting.",
        ),
        "deploy": attr.string(
            doc = "JSON-encoded value. The shard reader deserialises the parsed JSON straight into the typed schema model.",
        ),
        "develop": attr.string(
            doc = "JSON-encoded value. The shard reader deserialises the parsed JSON straight into the typed schema model.",
        ),
        "device_cgroup_rules": attr.string_list(
            doc = "Add rules to the cgroup allowed devices list.",
        ),
        "devices": attr.string_list(
            doc = "List of device mappings for the container.",
        ),
        "dns": attr.string_list(
            doc = "Custom DNS servers to set for the service container.",
        ),
        "dns_opt": attr.string_list(
            doc = "Custom DNS options to be passed to the container's DNS resolver.",
        ),
        "dns_search": attr.string_list(
            doc = "Custom DNS search domains to set on the service container.",
        ),
        "domainname": attr.string(
            doc = "Custom domain name to use for the service container.",
        ),
        "entrypoint": attr.string_list(
            doc = "Override the default entrypoint declared by the container image, for example 'ENTRYPOINT' in Dockerfile.",
        ),
        "env_file": attr.string_list(
            doc = "Add environment variables from a file or multiple files. Can be a single file path or a list of file paths.",
        ),
        "environment": attr.string_dict(
            doc = "Add environment variables. You can use either an array or a list of KEY=VAL pairs.",
        ),
        "expose": attr.string(
            doc = "Expose ports without publishing them to the host machine - they'll only be accessible to linked services. (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "extends": attr.string(
            doc = "Extend another service, in the current file or another file. (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "external_links": attr.string_list(
            doc = "Link to services started outside this Compose application. Specify services as <service_name>:<alias>.",
        ),
        "extra_hosts": attr.string_list(
            doc = "Add hostname mappings to the container network interface configuration.",
        ),
        "gpus": attr.string(
            doc = "Define GPU devices to use. Can be set to 'all' to use all GPUs, or a list of specific GPU devices. (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "group_add": attr.string(
            doc = "Add additional groups which user inside the container should be member of. (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "healthcheck": attr.string(
            doc = "Configure a health check for the container to monitor its health status. (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "hostname": attr.string(
            doc = "Define a custom hostname for the service container.",
        ),
        "image": attr.string(
            doc = "Specify the image to start the container from. Can be a repository/tag, a digest, or a local image ID.",
        ),
        "init": attr.bool(
            doc = "Run as an init process inside the container that forwards signals and reaps processes.",
        ),
        "ipc": attr.string(
            doc = "IPC sharing mode for the service container. Use 'host' to share the host's IPC namespace, 'service:[service_name]' to share with another service, or 'shareable' to allow other services to share this service's IPC namespace.",
        ),
        "isolation": attr.string(
            doc = "Container isolation technology to use. Supported values are platform-specific.",
        ),
        "label_file": attr.string_list(
            doc = "Add metadata to containers using files containing Docker labels.",
        ),
        "labels": attr.string_dict(
            doc = "Add metadata to containers using Docker labels. You can use either an array or a list.",
        ),
        "links": attr.string_list(
            doc = "Link to containers in another service. Either specify both the service name and a link alias (SERVICE:ALIAS), or just the service name.",
        ),
        "logging": attr.string(
            doc = "Logging configuration for the service. (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "mac_address": attr.string(
            doc = "Container MAC address to set.",
        ),
        "mem_limit": attr.string(
            doc = "Memory limit for the container. A string value can use suffix like '2g' for 2 gigabytes.",
        ),
        "mem_reservation": attr.string(
            doc = "Memory reservation for the container.",
        ),
        "mem_swappiness": attr.string(
            doc = "Container memory swappiness as percentage (0 to 100).",
        ),
        "memswap_limit": attr.string(
            doc = "Amount of memory the container is allowed to swap to disk. Set to -1 to enable unlimited swap.",
        ),
        "models": attr.string_list(
            doc = "AI Models to use, referencing entries under the top-level models key.",
        ),
        "network_mode": attr.string(
            doc = "Network mode. Values can be 'bridge', 'host', 'none', 'service:[service name]', or 'container:[container name]'.",
        ),
        "networks": attr.string_list(
            doc = "Networks to join, referencing entries under the top-level networks key. Can be a list of network names or a mapping of network name to network configuration.",
        ),
        "oom_kill_disable": attr.bool(
            doc = "Disable OOM Killer for the container.",
        ),
        "oom_score_adj": attr.string(
            doc = "Tune host's OOM preferences for the container (accepts -1000 to 1000). (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "pid": attr.string(
            doc = "PID mode for container.",
        ),
        "pids_limit": attr.string(
            doc = "Tune a container's PIDs limit. Set to -1 for unlimited PIDs.",
        ),
        "platform": attr.string(
            doc = "Target platform to run on, e.g., 'linux/amd64', 'linux/arm64', or 'windows/amd64'.",
        ),
        "ports": attr.string_list(
            doc = "Expose container ports. Short format ([HOST:]CONTAINER[/PROTOCOL]).",
        ),
        "post_start": attr.string(
            doc = "Commands to run after the container starts. If any command fails, the container stops. (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "pre_stop": attr.string(
            doc = "Commands to run before the container stops. If any command fails, the container stop is aborted. (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "privileged": attr.bool(
            doc = "Give extended privileges to the service container.",
        ),
        "profiles": attr.string_list(
            doc = "List of profiles for this service. When profiles are specified, services are only started when the profile is activated.",
        ),
        "provider": attr.string(
            doc = "Specify a service which will not be manage by Compose directly, and delegate its management to an external provider. (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "pull_policy": attr.string(
            doc = "Policy for pulling images. Options include: 'always', 'never', 'if_not_present', 'missing', 'build', or time-based refresh policies.",
        ),
        "pull_refresh_after": attr.string(
            doc = "Time after which to refresh the image. Used with pull_policy=refresh.",
        ),
        "read_only": attr.bool(
            doc = "Mount the container's filesystem as read only.",
        ),
        "restart": attr.string(
            doc = "Restart policy for the service container. Options include: 'no', 'always', 'on-failure', and 'unless-stopped'.",
        ),
        "runtime": attr.string(
            doc = "Runtime to use for this container, e.g., 'runc'.",
        ),
        "scale": attr.string(
            doc = "Number of containers to deploy for this service.",
        ),
        "secrets": attr.string_list(
            doc = "Grant access to Secrets on a per-service basis.",
        ),
        "security_opt": attr.string_list(
            doc = "Override the default labeling scheme for each container.",
        ),
        "shm_size": attr.string(
            doc = "Size of /dev/shm. A string value can use suffix like '2g' for 2 gigabytes.",
        ),
        "stdin_open": attr.bool(
            doc = "Keep STDIN open even if not attached.",
        ),
        "stop_grace_period": attr.string(
            doc = "Time to wait for the container to stop gracefully before sending SIGKILL (e.g., '1s', '1m30s').",
        ),
        "stop_signal": attr.string(
            doc = "Signal to stop the container (e.g., 'SIGTERM', 'SIGINT').",
        ),
        "storage_opt": attr.string(
            doc = "Storage driver options for the container. (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "sysctls": attr.string_dict(
            doc = "Kernel parameters to set in the container. You can use either an array or a list.",
        ),
        "tmpfs": attr.string_list(
            doc = "Mount a temporary filesystem (tmpfs) into the container. Can be a single value or a list.",
        ),
        "tty": attr.bool(
            doc = "Allocate a pseudo-TTY to service container.",
        ),
        "ulimits": attr.string(
            doc = "Override the default ulimits for a container. (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "use_api_socket": attr.bool(
            doc = "Bind mount Docker API socket and required auth.",
        ),
        "user": attr.string(
            doc = "Username or UID to run the container process as.",
        ),
        "userns_mode": attr.string(
            doc = "User namespace to use. 'host' shares the host's user namespace.",
        ),
        "uts": attr.string(
            doc = "UTS namespace to use. 'host' shares the host's UTS namespace.",
        ),
        "volumes": attr.string_list(
            doc = "Mount host paths or named volumes accessible to the container. Short syntax (VOLUME:CONTAINER_PATH[:MODE])",
        ),
        "volumes_from": attr.string_list(
            doc = "Mount volumes from another service or container. Optionally specify read-only access (ro) or read-write (rw).",
        ),
        "working_dir": attr.string(
            doc = "The working directory in which the entrypoint or command will be run",
        ),
    },
)

ComposeVolumeInfo = provider(
    doc = "A volume contributed by a target. Shard JSON matches the volume schema.",
    fields = {
        "volume_name": "string: top-level key for this volume in the rendered project.",
        "json": "File: the JSON shard.",
    },
)

def _docker_compose_volume_impl(ctx):
    item_name = ctx.attr.volume_name or ctx.label.name
    payload = {
        "driver": ctx.attr.driver,
        "driver_opts": ctx.attr.driver_opts,
        "external": ctx.attr.external,
        "labels": ctx.attr.labels,
        "name": ctx.attr.name_override,
    }
    payload = strip_empty(payload)
    shard = ctx.actions.declare_file(ctx.label.name + ".volume.json")
    ctx.actions.write(shard, json.encode(payload))
    return [
        DefaultInfo(files = depset([shard])),
        ComposeVolumeInfo(volume_name = item_name, json = shard),
    ]

docker_compose_volume = rule(
    implementation = _docker_compose_volume_impl,
    doc = "Volume configuration for the Compose application.",
    provides = [ComposeVolumeInfo],
    attrs = {
        "volume_name": attr.string(
            doc = "Top-level key for this volume in the rendered project. Defaults to the rule name.",
        ),
        "driver": attr.string(
            doc = "Specify which volume driver should be used for this volume.",
        ),
        "driver_opts": attr.string_dict(
            doc = "Specify driver-specific options.",
        ),
        "external": attr.bool(
            doc = "Specifies that this volume already exists and was created outside of Compose.",
        ),
        "labels": attr.string_dict(
            doc = "Add metadata to the volume using labels.",
        ),
        "name_override": attr.string(
            doc = "Custom name for this volume.",
        ),
    },
)

ComposeNetworkInfo = provider(
    doc = "A network contributed by a target. Shard JSON matches the network schema.",
    fields = {
        "network_name": "string: top-level key for this network in the rendered project.",
        "json": "File: the JSON shard.",
    },
)

def _docker_compose_network_impl(ctx):
    item_name = ctx.attr.network_name or ctx.label.name
    payload = {
        "attachable": ctx.attr.attachable,
        "driver": ctx.attr.driver,
        "driver_opts": ctx.attr.driver_opts,
        "enable_ipv4": ctx.attr.enable_ipv4,
        "enable_ipv6": ctx.attr.enable_ipv6,
        "external": ctx.attr.external,
        "internal": ctx.attr.internal,
        "ipam": parse_json_or_none(ctx.attr.ipam),
        "labels": ctx.attr.labels,
        "name": ctx.attr.name_override,
    }
    payload = strip_empty(payload)
    shard = ctx.actions.declare_file(ctx.label.name + ".network.json")
    ctx.actions.write(shard, json.encode(payload))
    return [
        DefaultInfo(files = depset([shard])),
        ComposeNetworkInfo(network_name = item_name, json = shard),
    ]

docker_compose_network = rule(
    implementation = _docker_compose_network_impl,
    doc = "Network configuration for the Compose application.",
    provides = [ComposeNetworkInfo],
    attrs = {
        "network_name": attr.string(
            doc = "Top-level key for this network in the rendered project. Defaults to the rule name.",
        ),
        "attachable": attr.bool(
            doc = "If true, standalone containers can attach to this network.",
        ),
        "driver": attr.string(
            doc = "Specify which driver should be used for this network. Default is 'bridge'.",
        ),
        "driver_opts": attr.string_dict(
            doc = "Specify driver-specific options defined as key/value pairs.",
        ),
        "enable_ipv4": attr.bool(
            doc = "Enable IPv4 networking.",
        ),
        "enable_ipv6": attr.bool(
            doc = "Enable IPv6 networking.",
        ),
        "external": attr.bool(
            doc = "Specifies that this network already exists and was created outside of Compose.",
        ),
        "internal": attr.bool(
            doc = "Create an externally isolated network.",
        ),
        "ipam": attr.string(
            doc = "Custom IP Address Management configuration for this network. (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "labels": attr.string_dict(
            doc = "Add metadata to the network using labels.",
        ),
        "name_override": attr.string(
            doc = "Custom name for this network.",
        ),
    },
)

